
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  FRANQUEADOR: 'FRANQUEADOR',
  MULTIFRANQUEADO: 'MULTIFRANQUEADO',
  GERENTE: 'GERENTE',
  COLABORADOR: 'COLABORADOR'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const ChurnStatus = {
  ativo: 'ativo',
  em_risco: 'em_risco',
  em_risco_alto: 'em_risco_alto',
  perdido: 'perdido'
} as const

export type ChurnStatus = (typeof ChurnStatus)[keyof typeof ChurnStatus]


export const ChurnAcaoType = {
  email: 'email',
  sms: 'sms',
  whatsapp: 'whatsapp',
  desconto: 'desconto',
  alerta: 'alerta'
} as const

export type ChurnAcaoType = (typeof ChurnAcaoType)[keyof typeof ChurnAcaoType]


export const ChurnAcaoStatus = {
  pendente: 'pendente',
  enviado: 'enviado',
  falhou: 'falhou',
  ignorado: 'ignorado',
  respondeu: 'respondeu'
} as const

export type ChurnAcaoStatus = (typeof ChurnAcaoStatus)[keyof typeof ChurnAcaoStatus]


export const ChurnProcessamentoType = {
  diario: 'diario',
  manual: 'manual',
  agendado: 'agendado'
} as const

export type ChurnProcessamentoType = (typeof ChurnProcessamentoType)[keyof typeof ChurnProcessamentoType]


export const ChurnLogStatus = {
  success: 'success',
  error: 'error'
} as const

export type ChurnLogStatus = (typeof ChurnLogStatus)[keyof typeof ChurnLogStatus]


export const Module = {
  BARBERSHOP: 'BARBERSHOP',
  LINKFOOD: 'LINKFOOD',
  WAHASEND: 'WAHASEND',
  VIPCAM: 'VIPCAM',
  VIP_DATA: 'VIP_DATA',
  TOTALIA: 'TOTALIA',
  INSTAGRAM: 'INSTAGRAM'
} as const

export type Module = (typeof Module)[keyof typeof Module]
