
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InstagramApprovalQueue` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model InstagramApprovalQueue
 * 
 */
export type InstagramApprovalQueueModel = runtime.Types.Result.DefaultSelection<Prisma.$InstagramApprovalQueuePayload>

export type AggregateInstagramApprovalQueue = {
  _count: InstagramApprovalQueueCountAggregateOutputType | null
  _min: InstagramApprovalQueueMinAggregateOutputType | null
  _max: InstagramApprovalQueueMaxAggregateOutputType | null
}

export type InstagramApprovalQueueMinAggregateOutputType = {
  id: string | null
  unitId: string | null
  accountId: string | null
  postId: string | null
  commentId: string | null
  commenterUsername: string | null
  commentText: string | null
  suggestedReply: string | null
  status: string | null
  sentiment: string | null
  expiresAt: Date | null
  approvedAt: Date | null
  rejectedAt: Date | null
  postedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InstagramApprovalQueueMaxAggregateOutputType = {
  id: string | null
  unitId: string | null
  accountId: string | null
  postId: string | null
  commentId: string | null
  commenterUsername: string | null
  commentText: string | null
  suggestedReply: string | null
  status: string | null
  sentiment: string | null
  expiresAt: Date | null
  approvedAt: Date | null
  rejectedAt: Date | null
  postedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InstagramApprovalQueueCountAggregateOutputType = {
  id: number
  unitId: number
  accountId: number
  postId: number
  commentId: number
  commenterUsername: number
  commentText: number
  suggestedReply: number
  status: number
  sentiment: number
  expiresAt: number
  approvedAt: number
  rejectedAt: number
  postedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type InstagramApprovalQueueMinAggregateInputType = {
  id?: true
  unitId?: true
  accountId?: true
  postId?: true
  commentId?: true
  commenterUsername?: true
  commentText?: true
  suggestedReply?: true
  status?: true
  sentiment?: true
  expiresAt?: true
  approvedAt?: true
  rejectedAt?: true
  postedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type InstagramApprovalQueueMaxAggregateInputType = {
  id?: true
  unitId?: true
  accountId?: true
  postId?: true
  commentId?: true
  commenterUsername?: true
  commentText?: true
  suggestedReply?: true
  status?: true
  sentiment?: true
  expiresAt?: true
  approvedAt?: true
  rejectedAt?: true
  postedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type InstagramApprovalQueueCountAggregateInputType = {
  id?: true
  unitId?: true
  accountId?: true
  postId?: true
  commentId?: true
  commenterUsername?: true
  commentText?: true
  suggestedReply?: true
  status?: true
  sentiment?: true
  expiresAt?: true
  approvedAt?: true
  rejectedAt?: true
  postedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type InstagramApprovalQueueAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InstagramApprovalQueue to aggregate.
   */
  where?: Prisma.InstagramApprovalQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstagramApprovalQueues to fetch.
   */
  orderBy?: Prisma.InstagramApprovalQueueOrderByWithRelationInput | Prisma.InstagramApprovalQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InstagramApprovalQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstagramApprovalQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstagramApprovalQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InstagramApprovalQueues
  **/
  _count?: true | InstagramApprovalQueueCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InstagramApprovalQueueMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InstagramApprovalQueueMaxAggregateInputType
}

export type GetInstagramApprovalQueueAggregateType<T extends InstagramApprovalQueueAggregateArgs> = {
      [P in keyof T & keyof AggregateInstagramApprovalQueue]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInstagramApprovalQueue[P]>
    : Prisma.GetScalarType<T[P], AggregateInstagramApprovalQueue[P]>
}




export type InstagramApprovalQueueGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InstagramApprovalQueueWhereInput
  orderBy?: Prisma.InstagramApprovalQueueOrderByWithAggregationInput | Prisma.InstagramApprovalQueueOrderByWithAggregationInput[]
  by: Prisma.InstagramApprovalQueueScalarFieldEnum[] | Prisma.InstagramApprovalQueueScalarFieldEnum
  having?: Prisma.InstagramApprovalQueueScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InstagramApprovalQueueCountAggregateInputType | true
  _min?: InstagramApprovalQueueMinAggregateInputType
  _max?: InstagramApprovalQueueMaxAggregateInputType
}

export type InstagramApprovalQueueGroupByOutputType = {
  id: string
  unitId: string
  accountId: string
  postId: string | null
  commentId: string | null
  commenterUsername: string | null
  commentText: string | null
  suggestedReply: string | null
  status: string
  sentiment: string | null
  expiresAt: Date | null
  approvedAt: Date | null
  rejectedAt: Date | null
  postedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: InstagramApprovalQueueCountAggregateOutputType | null
  _min: InstagramApprovalQueueMinAggregateOutputType | null
  _max: InstagramApprovalQueueMaxAggregateOutputType | null
}

export type GetInstagramApprovalQueueGroupByPayload<T extends InstagramApprovalQueueGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InstagramApprovalQueueGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InstagramApprovalQueueGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InstagramApprovalQueueGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InstagramApprovalQueueGroupByOutputType[P]>
      }
    >
  >



export type InstagramApprovalQueueWhereInput = {
  AND?: Prisma.InstagramApprovalQueueWhereInput | Prisma.InstagramApprovalQueueWhereInput[]
  OR?: Prisma.InstagramApprovalQueueWhereInput[]
  NOT?: Prisma.InstagramApprovalQueueWhereInput | Prisma.InstagramApprovalQueueWhereInput[]
  id?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  unitId?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  accountId?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  postId?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  commentId?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  commenterUsername?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  commentText?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  suggestedReply?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  status?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  sentiment?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  expiresAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  approvedAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  rejectedAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  postedAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"InstagramApprovalQueue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InstagramApprovalQueue"> | Date | string
  account?: Prisma.XOR<Prisma.InstagramAccountScalarRelationFilter, Prisma.InstagramAccountWhereInput>
}

export type InstagramApprovalQueueOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  postId?: Prisma.SortOrderInput | Prisma.SortOrder
  commentId?: Prisma.SortOrderInput | Prisma.SortOrder
  commenterUsername?: Prisma.SortOrderInput | Prisma.SortOrder
  commentText?: Prisma.SortOrderInput | Prisma.SortOrder
  suggestedReply?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  sentiment?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  approvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  rejectedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  postedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  account?: Prisma.InstagramAccountOrderByWithRelationInput
  _relevance?: Prisma.InstagramApprovalQueueOrderByRelevanceInput
}

export type InstagramApprovalQueueWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.InstagramApprovalQueueWhereInput | Prisma.InstagramApprovalQueueWhereInput[]
  OR?: Prisma.InstagramApprovalQueueWhereInput[]
  NOT?: Prisma.InstagramApprovalQueueWhereInput | Prisma.InstagramApprovalQueueWhereInput[]
  unitId?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  accountId?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  postId?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  commentId?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  commenterUsername?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  commentText?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  suggestedReply?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  status?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  sentiment?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  expiresAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  approvedAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  rejectedAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  postedAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"InstagramApprovalQueue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InstagramApprovalQueue"> | Date | string
  account?: Prisma.XOR<Prisma.InstagramAccountScalarRelationFilter, Prisma.InstagramAccountWhereInput>
}, "id">

export type InstagramApprovalQueueOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  postId?: Prisma.SortOrderInput | Prisma.SortOrder
  commentId?: Prisma.SortOrderInput | Prisma.SortOrder
  commenterUsername?: Prisma.SortOrderInput | Prisma.SortOrder
  commentText?: Prisma.SortOrderInput | Prisma.SortOrder
  suggestedReply?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  sentiment?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  approvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  rejectedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  postedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.InstagramApprovalQueueCountOrderByAggregateInput
  _max?: Prisma.InstagramApprovalQueueMaxOrderByAggregateInput
  _min?: Prisma.InstagramApprovalQueueMinOrderByAggregateInput
}

export type InstagramApprovalQueueScalarWhereWithAggregatesInput = {
  AND?: Prisma.InstagramApprovalQueueScalarWhereWithAggregatesInput | Prisma.InstagramApprovalQueueScalarWhereWithAggregatesInput[]
  OR?: Prisma.InstagramApprovalQueueScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InstagramApprovalQueueScalarWhereWithAggregatesInput | Prisma.InstagramApprovalQueueScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"InstagramApprovalQueue"> | string
  unitId?: Prisma.StringWithAggregatesFilter<"InstagramApprovalQueue"> | string
  accountId?: Prisma.StringWithAggregatesFilter<"InstagramApprovalQueue"> | string
  postId?: Prisma.StringNullableWithAggregatesFilter<"InstagramApprovalQueue"> | string | null
  commentId?: Prisma.StringNullableWithAggregatesFilter<"InstagramApprovalQueue"> | string | null
  commenterUsername?: Prisma.StringNullableWithAggregatesFilter<"InstagramApprovalQueue"> | string | null
  commentText?: Prisma.StringNullableWithAggregatesFilter<"InstagramApprovalQueue"> | string | null
  suggestedReply?: Prisma.StringNullableWithAggregatesFilter<"InstagramApprovalQueue"> | string | null
  status?: Prisma.StringWithAggregatesFilter<"InstagramApprovalQueue"> | string
  sentiment?: Prisma.StringNullableWithAggregatesFilter<"InstagramApprovalQueue"> | string | null
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"InstagramApprovalQueue"> | Date | string | null
  approvedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"InstagramApprovalQueue"> | Date | string | null
  rejectedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"InstagramApprovalQueue"> | Date | string | null
  postedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"InstagramApprovalQueue"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"InstagramApprovalQueue"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"InstagramApprovalQueue"> | Date | string
}

export type InstagramApprovalQueueCreateInput = {
  id?: string
  unitId: string
  postId?: string | null
  commentId?: string | null
  commenterUsername?: string | null
  commentText?: string | null
  suggestedReply?: string | null
  status?: string
  sentiment?: string | null
  expiresAt?: Date | string | null
  approvedAt?: Date | string | null
  rejectedAt?: Date | string | null
  postedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  account: Prisma.InstagramAccountCreateNestedOneWithoutApprovalsInput
}

export type InstagramApprovalQueueUncheckedCreateInput = {
  id?: string
  unitId: string
  accountId: string
  postId?: string | null
  commentId?: string | null
  commenterUsername?: string | null
  commentText?: string | null
  suggestedReply?: string | null
  status?: string
  sentiment?: string | null
  expiresAt?: Date | string | null
  approvedAt?: Date | string | null
  rejectedAt?: Date | string | null
  postedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramApprovalQueueUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commenterUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestedReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  postedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  account?: Prisma.InstagramAccountUpdateOneRequiredWithoutApprovalsNestedInput
}

export type InstagramApprovalQueueUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commenterUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestedReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  postedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramApprovalQueueCreateManyInput = {
  id?: string
  unitId: string
  accountId: string
  postId?: string | null
  commentId?: string | null
  commenterUsername?: string | null
  commentText?: string | null
  suggestedReply?: string | null
  status?: string
  sentiment?: string | null
  expiresAt?: Date | string | null
  approvedAt?: Date | string | null
  rejectedAt?: Date | string | null
  postedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramApprovalQueueUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commenterUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestedReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  postedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramApprovalQueueUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  accountId?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commenterUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestedReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  postedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramApprovalQueueListRelationFilter = {
  every?: Prisma.InstagramApprovalQueueWhereInput
  some?: Prisma.InstagramApprovalQueueWhereInput
  none?: Prisma.InstagramApprovalQueueWhereInput
}

export type InstagramApprovalQueueOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InstagramApprovalQueueOrderByRelevanceInput = {
  fields: Prisma.InstagramApprovalQueueOrderByRelevanceFieldEnum | Prisma.InstagramApprovalQueueOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type InstagramApprovalQueueCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  commentId?: Prisma.SortOrder
  commenterUsername?: Prisma.SortOrder
  commentText?: Prisma.SortOrder
  suggestedReply?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
  rejectedAt?: Prisma.SortOrder
  postedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InstagramApprovalQueueMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  commentId?: Prisma.SortOrder
  commenterUsername?: Prisma.SortOrder
  commentText?: Prisma.SortOrder
  suggestedReply?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
  rejectedAt?: Prisma.SortOrder
  postedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InstagramApprovalQueueMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  commentId?: Prisma.SortOrder
  commenterUsername?: Prisma.SortOrder
  commentText?: Prisma.SortOrder
  suggestedReply?: Prisma.SortOrder
  status?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
  rejectedAt?: Prisma.SortOrder
  postedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InstagramApprovalQueueCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.InstagramApprovalQueueCreateWithoutAccountInput, Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput> | Prisma.InstagramApprovalQueueCreateWithoutAccountInput[] | Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.InstagramApprovalQueueCreateOrConnectWithoutAccountInput | Prisma.InstagramApprovalQueueCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.InstagramApprovalQueueCreateManyAccountInputEnvelope
  connect?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
}

export type InstagramApprovalQueueUncheckedCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.InstagramApprovalQueueCreateWithoutAccountInput, Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput> | Prisma.InstagramApprovalQueueCreateWithoutAccountInput[] | Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.InstagramApprovalQueueCreateOrConnectWithoutAccountInput | Prisma.InstagramApprovalQueueCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.InstagramApprovalQueueCreateManyAccountInputEnvelope
  connect?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
}

export type InstagramApprovalQueueUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.InstagramApprovalQueueCreateWithoutAccountInput, Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput> | Prisma.InstagramApprovalQueueCreateWithoutAccountInput[] | Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.InstagramApprovalQueueCreateOrConnectWithoutAccountInput | Prisma.InstagramApprovalQueueCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.InstagramApprovalQueueUpsertWithWhereUniqueWithoutAccountInput | Prisma.InstagramApprovalQueueUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.InstagramApprovalQueueCreateManyAccountInputEnvelope
  set?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
  disconnect?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
  delete?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
  connect?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
  update?: Prisma.InstagramApprovalQueueUpdateWithWhereUniqueWithoutAccountInput | Prisma.InstagramApprovalQueueUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.InstagramApprovalQueueUpdateManyWithWhereWithoutAccountInput | Prisma.InstagramApprovalQueueUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.InstagramApprovalQueueScalarWhereInput | Prisma.InstagramApprovalQueueScalarWhereInput[]
}

export type InstagramApprovalQueueUncheckedUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.InstagramApprovalQueueCreateWithoutAccountInput, Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput> | Prisma.InstagramApprovalQueueCreateWithoutAccountInput[] | Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.InstagramApprovalQueueCreateOrConnectWithoutAccountInput | Prisma.InstagramApprovalQueueCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.InstagramApprovalQueueUpsertWithWhereUniqueWithoutAccountInput | Prisma.InstagramApprovalQueueUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.InstagramApprovalQueueCreateManyAccountInputEnvelope
  set?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
  disconnect?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
  delete?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
  connect?: Prisma.InstagramApprovalQueueWhereUniqueInput | Prisma.InstagramApprovalQueueWhereUniqueInput[]
  update?: Prisma.InstagramApprovalQueueUpdateWithWhereUniqueWithoutAccountInput | Prisma.InstagramApprovalQueueUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.InstagramApprovalQueueUpdateManyWithWhereWithoutAccountInput | Prisma.InstagramApprovalQueueUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.InstagramApprovalQueueScalarWhereInput | Prisma.InstagramApprovalQueueScalarWhereInput[]
}

export type InstagramApprovalQueueCreateWithoutAccountInput = {
  id?: string
  unitId: string
  postId?: string | null
  commentId?: string | null
  commenterUsername?: string | null
  commentText?: string | null
  suggestedReply?: string | null
  status?: string
  sentiment?: string | null
  expiresAt?: Date | string | null
  approvedAt?: Date | string | null
  rejectedAt?: Date | string | null
  postedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramApprovalQueueUncheckedCreateWithoutAccountInput = {
  id?: string
  unitId: string
  postId?: string | null
  commentId?: string | null
  commenterUsername?: string | null
  commentText?: string | null
  suggestedReply?: string | null
  status?: string
  sentiment?: string | null
  expiresAt?: Date | string | null
  approvedAt?: Date | string | null
  rejectedAt?: Date | string | null
  postedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramApprovalQueueCreateOrConnectWithoutAccountInput = {
  where: Prisma.InstagramApprovalQueueWhereUniqueInput
  create: Prisma.XOR<Prisma.InstagramApprovalQueueCreateWithoutAccountInput, Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput>
}

export type InstagramApprovalQueueCreateManyAccountInputEnvelope = {
  data: Prisma.InstagramApprovalQueueCreateManyAccountInput | Prisma.InstagramApprovalQueueCreateManyAccountInput[]
  skipDuplicates?: boolean
}

export type InstagramApprovalQueueUpsertWithWhereUniqueWithoutAccountInput = {
  where: Prisma.InstagramApprovalQueueWhereUniqueInput
  update: Prisma.XOR<Prisma.InstagramApprovalQueueUpdateWithoutAccountInput, Prisma.InstagramApprovalQueueUncheckedUpdateWithoutAccountInput>
  create: Prisma.XOR<Prisma.InstagramApprovalQueueCreateWithoutAccountInput, Prisma.InstagramApprovalQueueUncheckedCreateWithoutAccountInput>
}

export type InstagramApprovalQueueUpdateWithWhereUniqueWithoutAccountInput = {
  where: Prisma.InstagramApprovalQueueWhereUniqueInput
  data: Prisma.XOR<Prisma.InstagramApprovalQueueUpdateWithoutAccountInput, Prisma.InstagramApprovalQueueUncheckedUpdateWithoutAccountInput>
}

export type InstagramApprovalQueueUpdateManyWithWhereWithoutAccountInput = {
  where: Prisma.InstagramApprovalQueueScalarWhereInput
  data: Prisma.XOR<Prisma.InstagramApprovalQueueUpdateManyMutationInput, Prisma.InstagramApprovalQueueUncheckedUpdateManyWithoutAccountInput>
}

export type InstagramApprovalQueueScalarWhereInput = {
  AND?: Prisma.InstagramApprovalQueueScalarWhereInput | Prisma.InstagramApprovalQueueScalarWhereInput[]
  OR?: Prisma.InstagramApprovalQueueScalarWhereInput[]
  NOT?: Prisma.InstagramApprovalQueueScalarWhereInput | Prisma.InstagramApprovalQueueScalarWhereInput[]
  id?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  unitId?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  accountId?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  postId?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  commentId?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  commenterUsername?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  commentText?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  suggestedReply?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  status?: Prisma.StringFilter<"InstagramApprovalQueue"> | string
  sentiment?: Prisma.StringNullableFilter<"InstagramApprovalQueue"> | string | null
  expiresAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  approvedAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  rejectedAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  postedAt?: Prisma.DateTimeNullableFilter<"InstagramApprovalQueue"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"InstagramApprovalQueue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InstagramApprovalQueue"> | Date | string
}

export type InstagramApprovalQueueCreateManyAccountInput = {
  id?: string
  unitId: string
  postId?: string | null
  commentId?: string | null
  commenterUsername?: string | null
  commentText?: string | null
  suggestedReply?: string | null
  status?: string
  sentiment?: string | null
  expiresAt?: Date | string | null
  approvedAt?: Date | string | null
  rejectedAt?: Date | string | null
  postedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramApprovalQueueUpdateWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commenterUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestedReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  postedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramApprovalQueueUncheckedUpdateWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commenterUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestedReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  postedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramApprovalQueueUncheckedUpdateManyWithoutAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commenterUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestedReply?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  postedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type InstagramApprovalQueueSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  unitId?: boolean
  accountId?: boolean
  postId?: boolean
  commentId?: boolean
  commenterUsername?: boolean
  commentText?: boolean
  suggestedReply?: boolean
  status?: boolean
  sentiment?: boolean
  expiresAt?: boolean
  approvedAt?: boolean
  rejectedAt?: boolean
  postedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.InstagramAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["instagramApprovalQueue"]>



export type InstagramApprovalQueueSelectScalar = {
  id?: boolean
  unitId?: boolean
  accountId?: boolean
  postId?: boolean
  commentId?: boolean
  commenterUsername?: boolean
  commentText?: boolean
  suggestedReply?: boolean
  status?: boolean
  sentiment?: boolean
  expiresAt?: boolean
  approvedAt?: boolean
  rejectedAt?: boolean
  postedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type InstagramApprovalQueueOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "unitId" | "accountId" | "postId" | "commentId" | "commenterUsername" | "commentText" | "suggestedReply" | "status" | "sentiment" | "expiresAt" | "approvedAt" | "rejectedAt" | "postedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["instagramApprovalQueue"]>
export type InstagramApprovalQueueInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.InstagramAccountDefaultArgs<ExtArgs>
}

export type $InstagramApprovalQueuePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InstagramApprovalQueue"
  objects: {
    account: Prisma.$InstagramAccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    unitId: string
    accountId: string
    postId: string | null
    commentId: string | null
    commenterUsername: string | null
    commentText: string | null
    suggestedReply: string | null
    status: string
    sentiment: string | null
    expiresAt: Date | null
    approvedAt: Date | null
    rejectedAt: Date | null
    postedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["instagramApprovalQueue"]>
  composites: {}
}

export type InstagramApprovalQueueGetPayload<S extends boolean | null | undefined | InstagramApprovalQueueDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload, S>

export type InstagramApprovalQueueCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InstagramApprovalQueueFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InstagramApprovalQueueCountAggregateInputType | true
  }

export interface InstagramApprovalQueueDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InstagramApprovalQueue'], meta: { name: 'InstagramApprovalQueue' } }
  /**
   * Find zero or one InstagramApprovalQueue that matches the filter.
   * @param {InstagramApprovalQueueFindUniqueArgs} args - Arguments to find a InstagramApprovalQueue
   * @example
   * // Get one InstagramApprovalQueue
   * const instagramApprovalQueue = await prisma.instagramApprovalQueue.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InstagramApprovalQueueFindUniqueArgs>(args: Prisma.SelectSubset<T, InstagramApprovalQueueFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InstagramApprovalQueueClient<runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InstagramApprovalQueue that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InstagramApprovalQueueFindUniqueOrThrowArgs} args - Arguments to find a InstagramApprovalQueue
   * @example
   * // Get one InstagramApprovalQueue
   * const instagramApprovalQueue = await prisma.instagramApprovalQueue.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InstagramApprovalQueueFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InstagramApprovalQueueFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InstagramApprovalQueueClient<runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InstagramApprovalQueue that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramApprovalQueueFindFirstArgs} args - Arguments to find a InstagramApprovalQueue
   * @example
   * // Get one InstagramApprovalQueue
   * const instagramApprovalQueue = await prisma.instagramApprovalQueue.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InstagramApprovalQueueFindFirstArgs>(args?: Prisma.SelectSubset<T, InstagramApprovalQueueFindFirstArgs<ExtArgs>>): Prisma.Prisma__InstagramApprovalQueueClient<runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InstagramApprovalQueue that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramApprovalQueueFindFirstOrThrowArgs} args - Arguments to find a InstagramApprovalQueue
   * @example
   * // Get one InstagramApprovalQueue
   * const instagramApprovalQueue = await prisma.instagramApprovalQueue.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InstagramApprovalQueueFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InstagramApprovalQueueFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InstagramApprovalQueueClient<runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InstagramApprovalQueues that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramApprovalQueueFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InstagramApprovalQueues
   * const instagramApprovalQueues = await prisma.instagramApprovalQueue.findMany()
   * 
   * // Get first 10 InstagramApprovalQueues
   * const instagramApprovalQueues = await prisma.instagramApprovalQueue.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const instagramApprovalQueueWithIdOnly = await prisma.instagramApprovalQueue.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InstagramApprovalQueueFindManyArgs>(args?: Prisma.SelectSubset<T, InstagramApprovalQueueFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InstagramApprovalQueue.
   * @param {InstagramApprovalQueueCreateArgs} args - Arguments to create a InstagramApprovalQueue.
   * @example
   * // Create one InstagramApprovalQueue
   * const InstagramApprovalQueue = await prisma.instagramApprovalQueue.create({
   *   data: {
   *     // ... data to create a InstagramApprovalQueue
   *   }
   * })
   * 
   */
  create<T extends InstagramApprovalQueueCreateArgs>(args: Prisma.SelectSubset<T, InstagramApprovalQueueCreateArgs<ExtArgs>>): Prisma.Prisma__InstagramApprovalQueueClient<runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InstagramApprovalQueues.
   * @param {InstagramApprovalQueueCreateManyArgs} args - Arguments to create many InstagramApprovalQueues.
   * @example
   * // Create many InstagramApprovalQueues
   * const instagramApprovalQueue = await prisma.instagramApprovalQueue.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InstagramApprovalQueueCreateManyArgs>(args?: Prisma.SelectSubset<T, InstagramApprovalQueueCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a InstagramApprovalQueue.
   * @param {InstagramApprovalQueueDeleteArgs} args - Arguments to delete one InstagramApprovalQueue.
   * @example
   * // Delete one InstagramApprovalQueue
   * const InstagramApprovalQueue = await prisma.instagramApprovalQueue.delete({
   *   where: {
   *     // ... filter to delete one InstagramApprovalQueue
   *   }
   * })
   * 
   */
  delete<T extends InstagramApprovalQueueDeleteArgs>(args: Prisma.SelectSubset<T, InstagramApprovalQueueDeleteArgs<ExtArgs>>): Prisma.Prisma__InstagramApprovalQueueClient<runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InstagramApprovalQueue.
   * @param {InstagramApprovalQueueUpdateArgs} args - Arguments to update one InstagramApprovalQueue.
   * @example
   * // Update one InstagramApprovalQueue
   * const instagramApprovalQueue = await prisma.instagramApprovalQueue.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InstagramApprovalQueueUpdateArgs>(args: Prisma.SelectSubset<T, InstagramApprovalQueueUpdateArgs<ExtArgs>>): Prisma.Prisma__InstagramApprovalQueueClient<runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InstagramApprovalQueues.
   * @param {InstagramApprovalQueueDeleteManyArgs} args - Arguments to filter InstagramApprovalQueues to delete.
   * @example
   * // Delete a few InstagramApprovalQueues
   * const { count } = await prisma.instagramApprovalQueue.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InstagramApprovalQueueDeleteManyArgs>(args?: Prisma.SelectSubset<T, InstagramApprovalQueueDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InstagramApprovalQueues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramApprovalQueueUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InstagramApprovalQueues
   * const instagramApprovalQueue = await prisma.instagramApprovalQueue.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InstagramApprovalQueueUpdateManyArgs>(args: Prisma.SelectSubset<T, InstagramApprovalQueueUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one InstagramApprovalQueue.
   * @param {InstagramApprovalQueueUpsertArgs} args - Arguments to update or create a InstagramApprovalQueue.
   * @example
   * // Update or create a InstagramApprovalQueue
   * const instagramApprovalQueue = await prisma.instagramApprovalQueue.upsert({
   *   create: {
   *     // ... data to create a InstagramApprovalQueue
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InstagramApprovalQueue we want to update
   *   }
   * })
   */
  upsert<T extends InstagramApprovalQueueUpsertArgs>(args: Prisma.SelectSubset<T, InstagramApprovalQueueUpsertArgs<ExtArgs>>): Prisma.Prisma__InstagramApprovalQueueClient<runtime.Types.Result.GetResult<Prisma.$InstagramApprovalQueuePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InstagramApprovalQueues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramApprovalQueueCountArgs} args - Arguments to filter InstagramApprovalQueues to count.
   * @example
   * // Count the number of InstagramApprovalQueues
   * const count = await prisma.instagramApprovalQueue.count({
   *   where: {
   *     // ... the filter for the InstagramApprovalQueues we want to count
   *   }
   * })
  **/
  count<T extends InstagramApprovalQueueCountArgs>(
    args?: Prisma.Subset<T, InstagramApprovalQueueCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InstagramApprovalQueueCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InstagramApprovalQueue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramApprovalQueueAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InstagramApprovalQueueAggregateArgs>(args: Prisma.Subset<T, InstagramApprovalQueueAggregateArgs>): Prisma.PrismaPromise<GetInstagramApprovalQueueAggregateType<T>>

  /**
   * Group by InstagramApprovalQueue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramApprovalQueueGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InstagramApprovalQueueGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InstagramApprovalQueueGroupByArgs['orderBy'] }
      : { orderBy?: InstagramApprovalQueueGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InstagramApprovalQueueGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInstagramApprovalQueueGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InstagramApprovalQueue model
 */
readonly fields: InstagramApprovalQueueFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InstagramApprovalQueue.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InstagramApprovalQueueClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  account<T extends Prisma.InstagramAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.InstagramAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__InstagramAccountClient<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InstagramApprovalQueue model
 */
export interface InstagramApprovalQueueFieldRefs {
  readonly id: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly unitId: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly accountId: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly postId: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly commentId: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly commenterUsername: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly commentText: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly suggestedReply: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly status: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly sentiment: Prisma.FieldRef<"InstagramApprovalQueue", 'String'>
  readonly expiresAt: Prisma.FieldRef<"InstagramApprovalQueue", 'DateTime'>
  readonly approvedAt: Prisma.FieldRef<"InstagramApprovalQueue", 'DateTime'>
  readonly rejectedAt: Prisma.FieldRef<"InstagramApprovalQueue", 'DateTime'>
  readonly postedAt: Prisma.FieldRef<"InstagramApprovalQueue", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"InstagramApprovalQueue", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"InstagramApprovalQueue", 'DateTime'>
}
    

// Custom InputTypes
/**
 * InstagramApprovalQueue findUnique
 */
export type InstagramApprovalQueueFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
  /**
   * Filter, which InstagramApprovalQueue to fetch.
   */
  where: Prisma.InstagramApprovalQueueWhereUniqueInput
}

/**
 * InstagramApprovalQueue findUniqueOrThrow
 */
export type InstagramApprovalQueueFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
  /**
   * Filter, which InstagramApprovalQueue to fetch.
   */
  where: Prisma.InstagramApprovalQueueWhereUniqueInput
}

/**
 * InstagramApprovalQueue findFirst
 */
export type InstagramApprovalQueueFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
  /**
   * Filter, which InstagramApprovalQueue to fetch.
   */
  where?: Prisma.InstagramApprovalQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstagramApprovalQueues to fetch.
   */
  orderBy?: Prisma.InstagramApprovalQueueOrderByWithRelationInput | Prisma.InstagramApprovalQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InstagramApprovalQueues.
   */
  cursor?: Prisma.InstagramApprovalQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstagramApprovalQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstagramApprovalQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InstagramApprovalQueues.
   */
  distinct?: Prisma.InstagramApprovalQueueScalarFieldEnum | Prisma.InstagramApprovalQueueScalarFieldEnum[]
}

/**
 * InstagramApprovalQueue findFirstOrThrow
 */
export type InstagramApprovalQueueFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
  /**
   * Filter, which InstagramApprovalQueue to fetch.
   */
  where?: Prisma.InstagramApprovalQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstagramApprovalQueues to fetch.
   */
  orderBy?: Prisma.InstagramApprovalQueueOrderByWithRelationInput | Prisma.InstagramApprovalQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InstagramApprovalQueues.
   */
  cursor?: Prisma.InstagramApprovalQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstagramApprovalQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstagramApprovalQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InstagramApprovalQueues.
   */
  distinct?: Prisma.InstagramApprovalQueueScalarFieldEnum | Prisma.InstagramApprovalQueueScalarFieldEnum[]
}

/**
 * InstagramApprovalQueue findMany
 */
export type InstagramApprovalQueueFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
  /**
   * Filter, which InstagramApprovalQueues to fetch.
   */
  where?: Prisma.InstagramApprovalQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstagramApprovalQueues to fetch.
   */
  orderBy?: Prisma.InstagramApprovalQueueOrderByWithRelationInput | Prisma.InstagramApprovalQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InstagramApprovalQueues.
   */
  cursor?: Prisma.InstagramApprovalQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstagramApprovalQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstagramApprovalQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InstagramApprovalQueues.
   */
  distinct?: Prisma.InstagramApprovalQueueScalarFieldEnum | Prisma.InstagramApprovalQueueScalarFieldEnum[]
}

/**
 * InstagramApprovalQueue create
 */
export type InstagramApprovalQueueCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
  /**
   * The data needed to create a InstagramApprovalQueue.
   */
  data: Prisma.XOR<Prisma.InstagramApprovalQueueCreateInput, Prisma.InstagramApprovalQueueUncheckedCreateInput>
}

/**
 * InstagramApprovalQueue createMany
 */
export type InstagramApprovalQueueCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InstagramApprovalQueues.
   */
  data: Prisma.InstagramApprovalQueueCreateManyInput | Prisma.InstagramApprovalQueueCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InstagramApprovalQueue update
 */
export type InstagramApprovalQueueUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
  /**
   * The data needed to update a InstagramApprovalQueue.
   */
  data: Prisma.XOR<Prisma.InstagramApprovalQueueUpdateInput, Prisma.InstagramApprovalQueueUncheckedUpdateInput>
  /**
   * Choose, which InstagramApprovalQueue to update.
   */
  where: Prisma.InstagramApprovalQueueWhereUniqueInput
}

/**
 * InstagramApprovalQueue updateMany
 */
export type InstagramApprovalQueueUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InstagramApprovalQueues.
   */
  data: Prisma.XOR<Prisma.InstagramApprovalQueueUpdateManyMutationInput, Prisma.InstagramApprovalQueueUncheckedUpdateManyInput>
  /**
   * Filter which InstagramApprovalQueues to update
   */
  where?: Prisma.InstagramApprovalQueueWhereInput
  /**
   * Limit how many InstagramApprovalQueues to update.
   */
  limit?: number
}

/**
 * InstagramApprovalQueue upsert
 */
export type InstagramApprovalQueueUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
  /**
   * The filter to search for the InstagramApprovalQueue to update in case it exists.
   */
  where: Prisma.InstagramApprovalQueueWhereUniqueInput
  /**
   * In case the InstagramApprovalQueue found by the `where` argument doesn't exist, create a new InstagramApprovalQueue with this data.
   */
  create: Prisma.XOR<Prisma.InstagramApprovalQueueCreateInput, Prisma.InstagramApprovalQueueUncheckedCreateInput>
  /**
   * In case the InstagramApprovalQueue was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InstagramApprovalQueueUpdateInput, Prisma.InstagramApprovalQueueUncheckedUpdateInput>
}

/**
 * InstagramApprovalQueue delete
 */
export type InstagramApprovalQueueDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
  /**
   * Filter which InstagramApprovalQueue to delete.
   */
  where: Prisma.InstagramApprovalQueueWhereUniqueInput
}

/**
 * InstagramApprovalQueue deleteMany
 */
export type InstagramApprovalQueueDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InstagramApprovalQueues to delete
   */
  where?: Prisma.InstagramApprovalQueueWhereInput
  /**
   * Limit how many InstagramApprovalQueues to delete.
   */
  limit?: number
}

/**
 * InstagramApprovalQueue without action
 */
export type InstagramApprovalQueueDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramApprovalQueue
   */
  select?: Prisma.InstagramApprovalQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramApprovalQueue
   */
  omit?: Prisma.InstagramApprovalQueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramApprovalQueueInclude<ExtArgs> | null
}
