
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LinkfoodReview` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LinkfoodReview
 * 
 */
export type LinkfoodReviewModel = runtime.Types.Result.DefaultSelection<Prisma.$LinkfoodReviewPayload>

export type AggregateLinkfoodReview = {
  _count: LinkfoodReviewCountAggregateOutputType | null
  _avg: LinkfoodReviewAvgAggregateOutputType | null
  _sum: LinkfoodReviewSumAggregateOutputType | null
  _min: LinkfoodReviewMinAggregateOutputType | null
  _max: LinkfoodReviewMaxAggregateOutputType | null
}

export type LinkfoodReviewAvgAggregateOutputType = {
  rating: number | null
}

export type LinkfoodReviewSumAggregateOutputType = {
  rating: number | null
}

export type LinkfoodReviewMinAggregateOutputType = {
  id: string | null
  unitId: string | null
  businessId: string | null
  platformConnectionId: string | null
  externalId: string | null
  platform: string | null
  rating: number | null
  title: string | null
  content: string | null
  authorName: string | null
  authorImage: string | null
  reviewDate: Date | null
  responseText: string | null
  responseDate: Date | null
  language: string | null
  sentiment: string | null
  isVerified: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LinkfoodReviewMaxAggregateOutputType = {
  id: string | null
  unitId: string | null
  businessId: string | null
  platformConnectionId: string | null
  externalId: string | null
  platform: string | null
  rating: number | null
  title: string | null
  content: string | null
  authorName: string | null
  authorImage: string | null
  reviewDate: Date | null
  responseText: string | null
  responseDate: Date | null
  language: string | null
  sentiment: string | null
  isVerified: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LinkfoodReviewCountAggregateOutputType = {
  id: number
  unitId: number
  businessId: number
  platformConnectionId: number
  externalId: number
  platform: number
  rating: number
  title: number
  content: number
  authorName: number
  authorImage: number
  reviewDate: number
  responseText: number
  responseDate: number
  language: number
  sentiment: number
  isVerified: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LinkfoodReviewAvgAggregateInputType = {
  rating?: true
}

export type LinkfoodReviewSumAggregateInputType = {
  rating?: true
}

export type LinkfoodReviewMinAggregateInputType = {
  id?: true
  unitId?: true
  businessId?: true
  platformConnectionId?: true
  externalId?: true
  platform?: true
  rating?: true
  title?: true
  content?: true
  authorName?: true
  authorImage?: true
  reviewDate?: true
  responseText?: true
  responseDate?: true
  language?: true
  sentiment?: true
  isVerified?: true
  createdAt?: true
  updatedAt?: true
}

export type LinkfoodReviewMaxAggregateInputType = {
  id?: true
  unitId?: true
  businessId?: true
  platformConnectionId?: true
  externalId?: true
  platform?: true
  rating?: true
  title?: true
  content?: true
  authorName?: true
  authorImage?: true
  reviewDate?: true
  responseText?: true
  responseDate?: true
  language?: true
  sentiment?: true
  isVerified?: true
  createdAt?: true
  updatedAt?: true
}

export type LinkfoodReviewCountAggregateInputType = {
  id?: true
  unitId?: true
  businessId?: true
  platformConnectionId?: true
  externalId?: true
  platform?: true
  rating?: true
  title?: true
  content?: true
  authorName?: true
  authorImage?: true
  reviewDate?: true
  responseText?: true
  responseDate?: true
  language?: true
  sentiment?: true
  isVerified?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LinkfoodReviewAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LinkfoodReview to aggregate.
   */
  where?: Prisma.LinkfoodReviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkfoodReviews to fetch.
   */
  orderBy?: Prisma.LinkfoodReviewOrderByWithRelationInput | Prisma.LinkfoodReviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LinkfoodReviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkfoodReviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkfoodReviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LinkfoodReviews
  **/
  _count?: true | LinkfoodReviewCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LinkfoodReviewAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LinkfoodReviewSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LinkfoodReviewMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LinkfoodReviewMaxAggregateInputType
}

export type GetLinkfoodReviewAggregateType<T extends LinkfoodReviewAggregateArgs> = {
      [P in keyof T & keyof AggregateLinkfoodReview]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLinkfoodReview[P]>
    : Prisma.GetScalarType<T[P], AggregateLinkfoodReview[P]>
}




export type LinkfoodReviewGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LinkfoodReviewWhereInput
  orderBy?: Prisma.LinkfoodReviewOrderByWithAggregationInput | Prisma.LinkfoodReviewOrderByWithAggregationInput[]
  by: Prisma.LinkfoodReviewScalarFieldEnum[] | Prisma.LinkfoodReviewScalarFieldEnum
  having?: Prisma.LinkfoodReviewScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LinkfoodReviewCountAggregateInputType | true
  _avg?: LinkfoodReviewAvgAggregateInputType
  _sum?: LinkfoodReviewSumAggregateInputType
  _min?: LinkfoodReviewMinAggregateInputType
  _max?: LinkfoodReviewMaxAggregateInputType
}

export type LinkfoodReviewGroupByOutputType = {
  id: string
  unitId: string
  businessId: string
  platformConnectionId: string | null
  externalId: string | null
  platform: string
  rating: number
  title: string | null
  content: string | null
  authorName: string | null
  authorImage: string | null
  reviewDate: Date | null
  responseText: string | null
  responseDate: Date | null
  language: string | null
  sentiment: string | null
  isVerified: boolean
  createdAt: Date
  updatedAt: Date
  _count: LinkfoodReviewCountAggregateOutputType | null
  _avg: LinkfoodReviewAvgAggregateOutputType | null
  _sum: LinkfoodReviewSumAggregateOutputType | null
  _min: LinkfoodReviewMinAggregateOutputType | null
  _max: LinkfoodReviewMaxAggregateOutputType | null
}

export type GetLinkfoodReviewGroupByPayload<T extends LinkfoodReviewGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LinkfoodReviewGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LinkfoodReviewGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LinkfoodReviewGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LinkfoodReviewGroupByOutputType[P]>
      }
    >
  >



export type LinkfoodReviewWhereInput = {
  AND?: Prisma.LinkfoodReviewWhereInput | Prisma.LinkfoodReviewWhereInput[]
  OR?: Prisma.LinkfoodReviewWhereInput[]
  NOT?: Prisma.LinkfoodReviewWhereInput | Prisma.LinkfoodReviewWhereInput[]
  id?: Prisma.StringFilter<"LinkfoodReview"> | string
  unitId?: Prisma.StringFilter<"LinkfoodReview"> | string
  businessId?: Prisma.StringFilter<"LinkfoodReview"> | string
  platformConnectionId?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  externalId?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  platform?: Prisma.StringFilter<"LinkfoodReview"> | string
  rating?: Prisma.FloatFilter<"LinkfoodReview"> | number
  title?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  content?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  authorName?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  authorImage?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  reviewDate?: Prisma.DateTimeNullableFilter<"LinkfoodReview"> | Date | string | null
  responseText?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  responseDate?: Prisma.DateTimeNullableFilter<"LinkfoodReview"> | Date | string | null
  language?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  sentiment?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  isVerified?: Prisma.BoolFilter<"LinkfoodReview"> | boolean
  createdAt?: Prisma.DateTimeFilter<"LinkfoodReview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LinkfoodReview"> | Date | string
  connection?: Prisma.XOR<Prisma.LinkfoodPlatformConnectionNullableScalarRelationFilter, Prisma.LinkfoodPlatformConnectionWhereInput> | null
}

export type LinkfoodReviewOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  businessId?: Prisma.SortOrder
  platformConnectionId?: Prisma.SortOrderInput | Prisma.SortOrder
  externalId?: Prisma.SortOrderInput | Prisma.SortOrder
  platform?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  authorName?: Prisma.SortOrderInput | Prisma.SortOrder
  authorImage?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewDate?: Prisma.SortOrderInput | Prisma.SortOrder
  responseText?: Prisma.SortOrderInput | Prisma.SortOrder
  responseDate?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrderInput | Prisma.SortOrder
  sentiment?: Prisma.SortOrderInput | Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  connection?: Prisma.LinkfoodPlatformConnectionOrderByWithRelationInput
  _relevance?: Prisma.LinkfoodReviewOrderByRelevanceInput
}

export type LinkfoodReviewWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  unitId_externalId_platform?: Prisma.LinkfoodReviewUnitIdExternalIdPlatformCompoundUniqueInput
  AND?: Prisma.LinkfoodReviewWhereInput | Prisma.LinkfoodReviewWhereInput[]
  OR?: Prisma.LinkfoodReviewWhereInput[]
  NOT?: Prisma.LinkfoodReviewWhereInput | Prisma.LinkfoodReviewWhereInput[]
  unitId?: Prisma.StringFilter<"LinkfoodReview"> | string
  businessId?: Prisma.StringFilter<"LinkfoodReview"> | string
  platformConnectionId?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  externalId?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  platform?: Prisma.StringFilter<"LinkfoodReview"> | string
  rating?: Prisma.FloatFilter<"LinkfoodReview"> | number
  title?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  content?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  authorName?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  authorImage?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  reviewDate?: Prisma.DateTimeNullableFilter<"LinkfoodReview"> | Date | string | null
  responseText?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  responseDate?: Prisma.DateTimeNullableFilter<"LinkfoodReview"> | Date | string | null
  language?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  sentiment?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  isVerified?: Prisma.BoolFilter<"LinkfoodReview"> | boolean
  createdAt?: Prisma.DateTimeFilter<"LinkfoodReview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LinkfoodReview"> | Date | string
  connection?: Prisma.XOR<Prisma.LinkfoodPlatformConnectionNullableScalarRelationFilter, Prisma.LinkfoodPlatformConnectionWhereInput> | null
}, "id" | "unitId_externalId_platform">

export type LinkfoodReviewOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  businessId?: Prisma.SortOrder
  platformConnectionId?: Prisma.SortOrderInput | Prisma.SortOrder
  externalId?: Prisma.SortOrderInput | Prisma.SortOrder
  platform?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  authorName?: Prisma.SortOrderInput | Prisma.SortOrder
  authorImage?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewDate?: Prisma.SortOrderInput | Prisma.SortOrder
  responseText?: Prisma.SortOrderInput | Prisma.SortOrder
  responseDate?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrderInput | Prisma.SortOrder
  sentiment?: Prisma.SortOrderInput | Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LinkfoodReviewCountOrderByAggregateInput
  _avg?: Prisma.LinkfoodReviewAvgOrderByAggregateInput
  _max?: Prisma.LinkfoodReviewMaxOrderByAggregateInput
  _min?: Prisma.LinkfoodReviewMinOrderByAggregateInput
  _sum?: Prisma.LinkfoodReviewSumOrderByAggregateInput
}

export type LinkfoodReviewScalarWhereWithAggregatesInput = {
  AND?: Prisma.LinkfoodReviewScalarWhereWithAggregatesInput | Prisma.LinkfoodReviewScalarWhereWithAggregatesInput[]
  OR?: Prisma.LinkfoodReviewScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LinkfoodReviewScalarWhereWithAggregatesInput | Prisma.LinkfoodReviewScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LinkfoodReview"> | string
  unitId?: Prisma.StringWithAggregatesFilter<"LinkfoodReview"> | string
  businessId?: Prisma.StringWithAggregatesFilter<"LinkfoodReview"> | string
  platformConnectionId?: Prisma.StringNullableWithAggregatesFilter<"LinkfoodReview"> | string | null
  externalId?: Prisma.StringNullableWithAggregatesFilter<"LinkfoodReview"> | string | null
  platform?: Prisma.StringWithAggregatesFilter<"LinkfoodReview"> | string
  rating?: Prisma.FloatWithAggregatesFilter<"LinkfoodReview"> | number
  title?: Prisma.StringNullableWithAggregatesFilter<"LinkfoodReview"> | string | null
  content?: Prisma.StringNullableWithAggregatesFilter<"LinkfoodReview"> | string | null
  authorName?: Prisma.StringNullableWithAggregatesFilter<"LinkfoodReview"> | string | null
  authorImage?: Prisma.StringNullableWithAggregatesFilter<"LinkfoodReview"> | string | null
  reviewDate?: Prisma.DateTimeNullableWithAggregatesFilter<"LinkfoodReview"> | Date | string | null
  responseText?: Prisma.StringNullableWithAggregatesFilter<"LinkfoodReview"> | string | null
  responseDate?: Prisma.DateTimeNullableWithAggregatesFilter<"LinkfoodReview"> | Date | string | null
  language?: Prisma.StringNullableWithAggregatesFilter<"LinkfoodReview"> | string | null
  sentiment?: Prisma.StringNullableWithAggregatesFilter<"LinkfoodReview"> | string | null
  isVerified?: Prisma.BoolWithAggregatesFilter<"LinkfoodReview"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LinkfoodReview"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LinkfoodReview"> | Date | string
}

export type LinkfoodReviewCreateInput = {
  id?: string
  unitId: string
  businessId: string
  externalId?: string | null
  platform: string
  rating: number
  title?: string | null
  content?: string | null
  authorName?: string | null
  authorImage?: string | null
  reviewDate?: Date | string | null
  responseText?: string | null
  responseDate?: Date | string | null
  language?: string | null
  sentiment?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  connection?: Prisma.LinkfoodPlatformConnectionCreateNestedOneWithoutReviewsInput
}

export type LinkfoodReviewUncheckedCreateInput = {
  id?: string
  unitId: string
  businessId: string
  platformConnectionId?: string | null
  externalId?: string | null
  platform: string
  rating: number
  title?: string | null
  content?: string | null
  authorName?: string | null
  authorImage?: string | null
  reviewDate?: Date | string | null
  responseText?: string | null
  responseDate?: Date | string | null
  language?: string | null
  sentiment?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LinkfoodReviewUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  businessId?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  responseText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  connection?: Prisma.LinkfoodPlatformConnectionUpdateOneWithoutReviewsNestedInput
}

export type LinkfoodReviewUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  businessId?: Prisma.StringFieldUpdateOperationsInput | string
  platformConnectionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  responseText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkfoodReviewCreateManyInput = {
  id?: string
  unitId: string
  businessId: string
  platformConnectionId?: string | null
  externalId?: string | null
  platform: string
  rating: number
  title?: string | null
  content?: string | null
  authorName?: string | null
  authorImage?: string | null
  reviewDate?: Date | string | null
  responseText?: string | null
  responseDate?: Date | string | null
  language?: string | null
  sentiment?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LinkfoodReviewUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  businessId?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  responseText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkfoodReviewUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  businessId?: Prisma.StringFieldUpdateOperationsInput | string
  platformConnectionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  responseText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkfoodReviewListRelationFilter = {
  every?: Prisma.LinkfoodReviewWhereInput
  some?: Prisma.LinkfoodReviewWhereInput
  none?: Prisma.LinkfoodReviewWhereInput
}

export type LinkfoodReviewOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LinkfoodReviewOrderByRelevanceInput = {
  fields: Prisma.LinkfoodReviewOrderByRelevanceFieldEnum | Prisma.LinkfoodReviewOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type LinkfoodReviewUnitIdExternalIdPlatformCompoundUniqueInput = {
  unitId: string
  externalId: string
  platform: string
}

export type LinkfoodReviewCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  businessId?: Prisma.SortOrder
  platformConnectionId?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorImage?: Prisma.SortOrder
  reviewDate?: Prisma.SortOrder
  responseText?: Prisma.SortOrder
  responseDate?: Prisma.SortOrder
  language?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LinkfoodReviewAvgOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}

export type LinkfoodReviewMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  businessId?: Prisma.SortOrder
  platformConnectionId?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorImage?: Prisma.SortOrder
  reviewDate?: Prisma.SortOrder
  responseText?: Prisma.SortOrder
  responseDate?: Prisma.SortOrder
  language?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LinkfoodReviewMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  businessId?: Prisma.SortOrder
  platformConnectionId?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  authorName?: Prisma.SortOrder
  authorImage?: Prisma.SortOrder
  reviewDate?: Prisma.SortOrder
  responseText?: Prisma.SortOrder
  responseDate?: Prisma.SortOrder
  language?: Prisma.SortOrder
  sentiment?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LinkfoodReviewSumOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}

export type LinkfoodReviewCreateNestedManyWithoutConnectionInput = {
  create?: Prisma.XOR<Prisma.LinkfoodReviewCreateWithoutConnectionInput, Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput> | Prisma.LinkfoodReviewCreateWithoutConnectionInput[] | Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput[]
  connectOrCreate?: Prisma.LinkfoodReviewCreateOrConnectWithoutConnectionInput | Prisma.LinkfoodReviewCreateOrConnectWithoutConnectionInput[]
  createMany?: Prisma.LinkfoodReviewCreateManyConnectionInputEnvelope
  connect?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
}

export type LinkfoodReviewUncheckedCreateNestedManyWithoutConnectionInput = {
  create?: Prisma.XOR<Prisma.LinkfoodReviewCreateWithoutConnectionInput, Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput> | Prisma.LinkfoodReviewCreateWithoutConnectionInput[] | Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput[]
  connectOrCreate?: Prisma.LinkfoodReviewCreateOrConnectWithoutConnectionInput | Prisma.LinkfoodReviewCreateOrConnectWithoutConnectionInput[]
  createMany?: Prisma.LinkfoodReviewCreateManyConnectionInputEnvelope
  connect?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
}

export type LinkfoodReviewUpdateManyWithoutConnectionNestedInput = {
  create?: Prisma.XOR<Prisma.LinkfoodReviewCreateWithoutConnectionInput, Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput> | Prisma.LinkfoodReviewCreateWithoutConnectionInput[] | Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput[]
  connectOrCreate?: Prisma.LinkfoodReviewCreateOrConnectWithoutConnectionInput | Prisma.LinkfoodReviewCreateOrConnectWithoutConnectionInput[]
  upsert?: Prisma.LinkfoodReviewUpsertWithWhereUniqueWithoutConnectionInput | Prisma.LinkfoodReviewUpsertWithWhereUniqueWithoutConnectionInput[]
  createMany?: Prisma.LinkfoodReviewCreateManyConnectionInputEnvelope
  set?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
  disconnect?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
  delete?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
  connect?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
  update?: Prisma.LinkfoodReviewUpdateWithWhereUniqueWithoutConnectionInput | Prisma.LinkfoodReviewUpdateWithWhereUniqueWithoutConnectionInput[]
  updateMany?: Prisma.LinkfoodReviewUpdateManyWithWhereWithoutConnectionInput | Prisma.LinkfoodReviewUpdateManyWithWhereWithoutConnectionInput[]
  deleteMany?: Prisma.LinkfoodReviewScalarWhereInput | Prisma.LinkfoodReviewScalarWhereInput[]
}

export type LinkfoodReviewUncheckedUpdateManyWithoutConnectionNestedInput = {
  create?: Prisma.XOR<Prisma.LinkfoodReviewCreateWithoutConnectionInput, Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput> | Prisma.LinkfoodReviewCreateWithoutConnectionInput[] | Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput[]
  connectOrCreate?: Prisma.LinkfoodReviewCreateOrConnectWithoutConnectionInput | Prisma.LinkfoodReviewCreateOrConnectWithoutConnectionInput[]
  upsert?: Prisma.LinkfoodReviewUpsertWithWhereUniqueWithoutConnectionInput | Prisma.LinkfoodReviewUpsertWithWhereUniqueWithoutConnectionInput[]
  createMany?: Prisma.LinkfoodReviewCreateManyConnectionInputEnvelope
  set?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
  disconnect?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
  delete?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
  connect?: Prisma.LinkfoodReviewWhereUniqueInput | Prisma.LinkfoodReviewWhereUniqueInput[]
  update?: Prisma.LinkfoodReviewUpdateWithWhereUniqueWithoutConnectionInput | Prisma.LinkfoodReviewUpdateWithWhereUniqueWithoutConnectionInput[]
  updateMany?: Prisma.LinkfoodReviewUpdateManyWithWhereWithoutConnectionInput | Prisma.LinkfoodReviewUpdateManyWithWhereWithoutConnectionInput[]
  deleteMany?: Prisma.LinkfoodReviewScalarWhereInput | Prisma.LinkfoodReviewScalarWhereInput[]
}

export type LinkfoodReviewCreateWithoutConnectionInput = {
  id?: string
  unitId: string
  businessId: string
  externalId?: string | null
  platform: string
  rating: number
  title?: string | null
  content?: string | null
  authorName?: string | null
  authorImage?: string | null
  reviewDate?: Date | string | null
  responseText?: string | null
  responseDate?: Date | string | null
  language?: string | null
  sentiment?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LinkfoodReviewUncheckedCreateWithoutConnectionInput = {
  id?: string
  unitId: string
  businessId: string
  externalId?: string | null
  platform: string
  rating: number
  title?: string | null
  content?: string | null
  authorName?: string | null
  authorImage?: string | null
  reviewDate?: Date | string | null
  responseText?: string | null
  responseDate?: Date | string | null
  language?: string | null
  sentiment?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LinkfoodReviewCreateOrConnectWithoutConnectionInput = {
  where: Prisma.LinkfoodReviewWhereUniqueInput
  create: Prisma.XOR<Prisma.LinkfoodReviewCreateWithoutConnectionInput, Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput>
}

export type LinkfoodReviewCreateManyConnectionInputEnvelope = {
  data: Prisma.LinkfoodReviewCreateManyConnectionInput | Prisma.LinkfoodReviewCreateManyConnectionInput[]
  skipDuplicates?: boolean
}

export type LinkfoodReviewUpsertWithWhereUniqueWithoutConnectionInput = {
  where: Prisma.LinkfoodReviewWhereUniqueInput
  update: Prisma.XOR<Prisma.LinkfoodReviewUpdateWithoutConnectionInput, Prisma.LinkfoodReviewUncheckedUpdateWithoutConnectionInput>
  create: Prisma.XOR<Prisma.LinkfoodReviewCreateWithoutConnectionInput, Prisma.LinkfoodReviewUncheckedCreateWithoutConnectionInput>
}

export type LinkfoodReviewUpdateWithWhereUniqueWithoutConnectionInput = {
  where: Prisma.LinkfoodReviewWhereUniqueInput
  data: Prisma.XOR<Prisma.LinkfoodReviewUpdateWithoutConnectionInput, Prisma.LinkfoodReviewUncheckedUpdateWithoutConnectionInput>
}

export type LinkfoodReviewUpdateManyWithWhereWithoutConnectionInput = {
  where: Prisma.LinkfoodReviewScalarWhereInput
  data: Prisma.XOR<Prisma.LinkfoodReviewUpdateManyMutationInput, Prisma.LinkfoodReviewUncheckedUpdateManyWithoutConnectionInput>
}

export type LinkfoodReviewScalarWhereInput = {
  AND?: Prisma.LinkfoodReviewScalarWhereInput | Prisma.LinkfoodReviewScalarWhereInput[]
  OR?: Prisma.LinkfoodReviewScalarWhereInput[]
  NOT?: Prisma.LinkfoodReviewScalarWhereInput | Prisma.LinkfoodReviewScalarWhereInput[]
  id?: Prisma.StringFilter<"LinkfoodReview"> | string
  unitId?: Prisma.StringFilter<"LinkfoodReview"> | string
  businessId?: Prisma.StringFilter<"LinkfoodReview"> | string
  platformConnectionId?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  externalId?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  platform?: Prisma.StringFilter<"LinkfoodReview"> | string
  rating?: Prisma.FloatFilter<"LinkfoodReview"> | number
  title?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  content?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  authorName?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  authorImage?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  reviewDate?: Prisma.DateTimeNullableFilter<"LinkfoodReview"> | Date | string | null
  responseText?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  responseDate?: Prisma.DateTimeNullableFilter<"LinkfoodReview"> | Date | string | null
  language?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  sentiment?: Prisma.StringNullableFilter<"LinkfoodReview"> | string | null
  isVerified?: Prisma.BoolFilter<"LinkfoodReview"> | boolean
  createdAt?: Prisma.DateTimeFilter<"LinkfoodReview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LinkfoodReview"> | Date | string
}

export type LinkfoodReviewCreateManyConnectionInput = {
  id?: string
  unitId: string
  businessId: string
  externalId?: string | null
  platform: string
  rating: number
  title?: string | null
  content?: string | null
  authorName?: string | null
  authorImage?: string | null
  reviewDate?: Date | string | null
  responseText?: string | null
  responseDate?: Date | string | null
  language?: string | null
  sentiment?: string | null
  isVerified?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LinkfoodReviewUpdateWithoutConnectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  businessId?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  responseText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkfoodReviewUncheckedUpdateWithoutConnectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  businessId?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  responseText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkfoodReviewUncheckedUpdateManyWithoutConnectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  businessId?: Prisma.StringFieldUpdateOperationsInput | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  platform?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  responseText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  language?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sentiment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LinkfoodReviewSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  unitId?: boolean
  businessId?: boolean
  platformConnectionId?: boolean
  externalId?: boolean
  platform?: boolean
  rating?: boolean
  title?: boolean
  content?: boolean
  authorName?: boolean
  authorImage?: boolean
  reviewDate?: boolean
  responseText?: boolean
  responseDate?: boolean
  language?: boolean
  sentiment?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  connection?: boolean | Prisma.LinkfoodReview$connectionArgs<ExtArgs>
}, ExtArgs["result"]["linkfoodReview"]>



export type LinkfoodReviewSelectScalar = {
  id?: boolean
  unitId?: boolean
  businessId?: boolean
  platformConnectionId?: boolean
  externalId?: boolean
  platform?: boolean
  rating?: boolean
  title?: boolean
  content?: boolean
  authorName?: boolean
  authorImage?: boolean
  reviewDate?: boolean
  responseText?: boolean
  responseDate?: boolean
  language?: boolean
  sentiment?: boolean
  isVerified?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LinkfoodReviewOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "unitId" | "businessId" | "platformConnectionId" | "externalId" | "platform" | "rating" | "title" | "content" | "authorName" | "authorImage" | "reviewDate" | "responseText" | "responseDate" | "language" | "sentiment" | "isVerified" | "createdAt" | "updatedAt", ExtArgs["result"]["linkfoodReview"]>
export type LinkfoodReviewInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  connection?: boolean | Prisma.LinkfoodReview$connectionArgs<ExtArgs>
}

export type $LinkfoodReviewPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LinkfoodReview"
  objects: {
    connection: Prisma.$LinkfoodPlatformConnectionPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    unitId: string
    businessId: string
    platformConnectionId: string | null
    externalId: string | null
    platform: string
    rating: number
    title: string | null
    content: string | null
    authorName: string | null
    authorImage: string | null
    reviewDate: Date | null
    responseText: string | null
    responseDate: Date | null
    language: string | null
    sentiment: string | null
    isVerified: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["linkfoodReview"]>
  composites: {}
}

export type LinkfoodReviewGetPayload<S extends boolean | null | undefined | LinkfoodReviewDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload, S>

export type LinkfoodReviewCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LinkfoodReviewFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LinkfoodReviewCountAggregateInputType | true
  }

export interface LinkfoodReviewDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LinkfoodReview'], meta: { name: 'LinkfoodReview' } }
  /**
   * Find zero or one LinkfoodReview that matches the filter.
   * @param {LinkfoodReviewFindUniqueArgs} args - Arguments to find a LinkfoodReview
   * @example
   * // Get one LinkfoodReview
   * const linkfoodReview = await prisma.linkfoodReview.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LinkfoodReviewFindUniqueArgs>(args: Prisma.SelectSubset<T, LinkfoodReviewFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LinkfoodReviewClient<runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LinkfoodReview that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LinkfoodReviewFindUniqueOrThrowArgs} args - Arguments to find a LinkfoodReview
   * @example
   * // Get one LinkfoodReview
   * const linkfoodReview = await prisma.linkfoodReview.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LinkfoodReviewFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LinkfoodReviewFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LinkfoodReviewClient<runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LinkfoodReview that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkfoodReviewFindFirstArgs} args - Arguments to find a LinkfoodReview
   * @example
   * // Get one LinkfoodReview
   * const linkfoodReview = await prisma.linkfoodReview.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LinkfoodReviewFindFirstArgs>(args?: Prisma.SelectSubset<T, LinkfoodReviewFindFirstArgs<ExtArgs>>): Prisma.Prisma__LinkfoodReviewClient<runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LinkfoodReview that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkfoodReviewFindFirstOrThrowArgs} args - Arguments to find a LinkfoodReview
   * @example
   * // Get one LinkfoodReview
   * const linkfoodReview = await prisma.linkfoodReview.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LinkfoodReviewFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LinkfoodReviewFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LinkfoodReviewClient<runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LinkfoodReviews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkfoodReviewFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LinkfoodReviews
   * const linkfoodReviews = await prisma.linkfoodReview.findMany()
   * 
   * // Get first 10 LinkfoodReviews
   * const linkfoodReviews = await prisma.linkfoodReview.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const linkfoodReviewWithIdOnly = await prisma.linkfoodReview.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LinkfoodReviewFindManyArgs>(args?: Prisma.SelectSubset<T, LinkfoodReviewFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LinkfoodReview.
   * @param {LinkfoodReviewCreateArgs} args - Arguments to create a LinkfoodReview.
   * @example
   * // Create one LinkfoodReview
   * const LinkfoodReview = await prisma.linkfoodReview.create({
   *   data: {
   *     // ... data to create a LinkfoodReview
   *   }
   * })
   * 
   */
  create<T extends LinkfoodReviewCreateArgs>(args: Prisma.SelectSubset<T, LinkfoodReviewCreateArgs<ExtArgs>>): Prisma.Prisma__LinkfoodReviewClient<runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LinkfoodReviews.
   * @param {LinkfoodReviewCreateManyArgs} args - Arguments to create many LinkfoodReviews.
   * @example
   * // Create many LinkfoodReviews
   * const linkfoodReview = await prisma.linkfoodReview.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LinkfoodReviewCreateManyArgs>(args?: Prisma.SelectSubset<T, LinkfoodReviewCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a LinkfoodReview.
   * @param {LinkfoodReviewDeleteArgs} args - Arguments to delete one LinkfoodReview.
   * @example
   * // Delete one LinkfoodReview
   * const LinkfoodReview = await prisma.linkfoodReview.delete({
   *   where: {
   *     // ... filter to delete one LinkfoodReview
   *   }
   * })
   * 
   */
  delete<T extends LinkfoodReviewDeleteArgs>(args: Prisma.SelectSubset<T, LinkfoodReviewDeleteArgs<ExtArgs>>): Prisma.Prisma__LinkfoodReviewClient<runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LinkfoodReview.
   * @param {LinkfoodReviewUpdateArgs} args - Arguments to update one LinkfoodReview.
   * @example
   * // Update one LinkfoodReview
   * const linkfoodReview = await prisma.linkfoodReview.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LinkfoodReviewUpdateArgs>(args: Prisma.SelectSubset<T, LinkfoodReviewUpdateArgs<ExtArgs>>): Prisma.Prisma__LinkfoodReviewClient<runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LinkfoodReviews.
   * @param {LinkfoodReviewDeleteManyArgs} args - Arguments to filter LinkfoodReviews to delete.
   * @example
   * // Delete a few LinkfoodReviews
   * const { count } = await prisma.linkfoodReview.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LinkfoodReviewDeleteManyArgs>(args?: Prisma.SelectSubset<T, LinkfoodReviewDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LinkfoodReviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkfoodReviewUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LinkfoodReviews
   * const linkfoodReview = await prisma.linkfoodReview.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LinkfoodReviewUpdateManyArgs>(args: Prisma.SelectSubset<T, LinkfoodReviewUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one LinkfoodReview.
   * @param {LinkfoodReviewUpsertArgs} args - Arguments to update or create a LinkfoodReview.
   * @example
   * // Update or create a LinkfoodReview
   * const linkfoodReview = await prisma.linkfoodReview.upsert({
   *   create: {
   *     // ... data to create a LinkfoodReview
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LinkfoodReview we want to update
   *   }
   * })
   */
  upsert<T extends LinkfoodReviewUpsertArgs>(args: Prisma.SelectSubset<T, LinkfoodReviewUpsertArgs<ExtArgs>>): Prisma.Prisma__LinkfoodReviewClient<runtime.Types.Result.GetResult<Prisma.$LinkfoodReviewPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LinkfoodReviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkfoodReviewCountArgs} args - Arguments to filter LinkfoodReviews to count.
   * @example
   * // Count the number of LinkfoodReviews
   * const count = await prisma.linkfoodReview.count({
   *   where: {
   *     // ... the filter for the LinkfoodReviews we want to count
   *   }
   * })
  **/
  count<T extends LinkfoodReviewCountArgs>(
    args?: Prisma.Subset<T, LinkfoodReviewCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LinkfoodReviewCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LinkfoodReview.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkfoodReviewAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LinkfoodReviewAggregateArgs>(args: Prisma.Subset<T, LinkfoodReviewAggregateArgs>): Prisma.PrismaPromise<GetLinkfoodReviewAggregateType<T>>

  /**
   * Group by LinkfoodReview.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkfoodReviewGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LinkfoodReviewGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LinkfoodReviewGroupByArgs['orderBy'] }
      : { orderBy?: LinkfoodReviewGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LinkfoodReviewGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLinkfoodReviewGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LinkfoodReview model
 */
readonly fields: LinkfoodReviewFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LinkfoodReview.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LinkfoodReviewClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  connection<T extends Prisma.LinkfoodReview$connectionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LinkfoodReview$connectionArgs<ExtArgs>>): Prisma.Prisma__LinkfoodPlatformConnectionClient<runtime.Types.Result.GetResult<Prisma.$LinkfoodPlatformConnectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LinkfoodReview model
 */
export interface LinkfoodReviewFieldRefs {
  readonly id: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly unitId: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly businessId: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly platformConnectionId: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly externalId: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly platform: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly rating: Prisma.FieldRef<"LinkfoodReview", 'Float'>
  readonly title: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly content: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly authorName: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly authorImage: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly reviewDate: Prisma.FieldRef<"LinkfoodReview", 'DateTime'>
  readonly responseText: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly responseDate: Prisma.FieldRef<"LinkfoodReview", 'DateTime'>
  readonly language: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly sentiment: Prisma.FieldRef<"LinkfoodReview", 'String'>
  readonly isVerified: Prisma.FieldRef<"LinkfoodReview", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"LinkfoodReview", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LinkfoodReview", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LinkfoodReview findUnique
 */
export type LinkfoodReviewFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
  /**
   * Filter, which LinkfoodReview to fetch.
   */
  where: Prisma.LinkfoodReviewWhereUniqueInput
}

/**
 * LinkfoodReview findUniqueOrThrow
 */
export type LinkfoodReviewFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
  /**
   * Filter, which LinkfoodReview to fetch.
   */
  where: Prisma.LinkfoodReviewWhereUniqueInput
}

/**
 * LinkfoodReview findFirst
 */
export type LinkfoodReviewFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
  /**
   * Filter, which LinkfoodReview to fetch.
   */
  where?: Prisma.LinkfoodReviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkfoodReviews to fetch.
   */
  orderBy?: Prisma.LinkfoodReviewOrderByWithRelationInput | Prisma.LinkfoodReviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LinkfoodReviews.
   */
  cursor?: Prisma.LinkfoodReviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkfoodReviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkfoodReviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LinkfoodReviews.
   */
  distinct?: Prisma.LinkfoodReviewScalarFieldEnum | Prisma.LinkfoodReviewScalarFieldEnum[]
}

/**
 * LinkfoodReview findFirstOrThrow
 */
export type LinkfoodReviewFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
  /**
   * Filter, which LinkfoodReview to fetch.
   */
  where?: Prisma.LinkfoodReviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkfoodReviews to fetch.
   */
  orderBy?: Prisma.LinkfoodReviewOrderByWithRelationInput | Prisma.LinkfoodReviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LinkfoodReviews.
   */
  cursor?: Prisma.LinkfoodReviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkfoodReviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkfoodReviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LinkfoodReviews.
   */
  distinct?: Prisma.LinkfoodReviewScalarFieldEnum | Prisma.LinkfoodReviewScalarFieldEnum[]
}

/**
 * LinkfoodReview findMany
 */
export type LinkfoodReviewFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
  /**
   * Filter, which LinkfoodReviews to fetch.
   */
  where?: Prisma.LinkfoodReviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkfoodReviews to fetch.
   */
  orderBy?: Prisma.LinkfoodReviewOrderByWithRelationInput | Prisma.LinkfoodReviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LinkfoodReviews.
   */
  cursor?: Prisma.LinkfoodReviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkfoodReviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkfoodReviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LinkfoodReviews.
   */
  distinct?: Prisma.LinkfoodReviewScalarFieldEnum | Prisma.LinkfoodReviewScalarFieldEnum[]
}

/**
 * LinkfoodReview create
 */
export type LinkfoodReviewCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
  /**
   * The data needed to create a LinkfoodReview.
   */
  data: Prisma.XOR<Prisma.LinkfoodReviewCreateInput, Prisma.LinkfoodReviewUncheckedCreateInput>
}

/**
 * LinkfoodReview createMany
 */
export type LinkfoodReviewCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LinkfoodReviews.
   */
  data: Prisma.LinkfoodReviewCreateManyInput | Prisma.LinkfoodReviewCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LinkfoodReview update
 */
export type LinkfoodReviewUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
  /**
   * The data needed to update a LinkfoodReview.
   */
  data: Prisma.XOR<Prisma.LinkfoodReviewUpdateInput, Prisma.LinkfoodReviewUncheckedUpdateInput>
  /**
   * Choose, which LinkfoodReview to update.
   */
  where: Prisma.LinkfoodReviewWhereUniqueInput
}

/**
 * LinkfoodReview updateMany
 */
export type LinkfoodReviewUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LinkfoodReviews.
   */
  data: Prisma.XOR<Prisma.LinkfoodReviewUpdateManyMutationInput, Prisma.LinkfoodReviewUncheckedUpdateManyInput>
  /**
   * Filter which LinkfoodReviews to update
   */
  where?: Prisma.LinkfoodReviewWhereInput
  /**
   * Limit how many LinkfoodReviews to update.
   */
  limit?: number
}

/**
 * LinkfoodReview upsert
 */
export type LinkfoodReviewUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
  /**
   * The filter to search for the LinkfoodReview to update in case it exists.
   */
  where: Prisma.LinkfoodReviewWhereUniqueInput
  /**
   * In case the LinkfoodReview found by the `where` argument doesn't exist, create a new LinkfoodReview with this data.
   */
  create: Prisma.XOR<Prisma.LinkfoodReviewCreateInput, Prisma.LinkfoodReviewUncheckedCreateInput>
  /**
   * In case the LinkfoodReview was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LinkfoodReviewUpdateInput, Prisma.LinkfoodReviewUncheckedUpdateInput>
}

/**
 * LinkfoodReview delete
 */
export type LinkfoodReviewDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
  /**
   * Filter which LinkfoodReview to delete.
   */
  where: Prisma.LinkfoodReviewWhereUniqueInput
}

/**
 * LinkfoodReview deleteMany
 */
export type LinkfoodReviewDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LinkfoodReviews to delete
   */
  where?: Prisma.LinkfoodReviewWhereInput
  /**
   * Limit how many LinkfoodReviews to delete.
   */
  limit?: number
}

/**
 * LinkfoodReview.connection
 */
export type LinkfoodReview$connectionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodPlatformConnection
   */
  select?: Prisma.LinkfoodPlatformConnectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodPlatformConnection
   */
  omit?: Prisma.LinkfoodPlatformConnectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodPlatformConnectionInclude<ExtArgs> | null
  where?: Prisma.LinkfoodPlatformConnectionWhereInput
}

/**
 * LinkfoodReview without action
 */
export type LinkfoodReviewDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkfoodReview
   */
  select?: Prisma.LinkfoodReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkfoodReview
   */
  omit?: Prisma.LinkfoodReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkfoodReviewInclude<ExtArgs> | null
}
