
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TotaliaAuditLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TotaliaAuditLog
 * 
 */
export type TotaliaAuditLogModel = runtime.Types.Result.DefaultSelection<Prisma.$TotaliaAuditLogPayload>

export type AggregateTotaliaAuditLog = {
  _count: TotaliaAuditLogCountAggregateOutputType | null
  _min: TotaliaAuditLogMinAggregateOutputType | null
  _max: TotaliaAuditLogMaxAggregateOutputType | null
}

export type TotaliaAuditLogMinAggregateOutputType = {
  id: string | null
  userId: string | null
  unitId: string | null
  tableName: string | null
  action: string | null
  ipAddress: string | null
  userAgent: string | null
  createdAt: Date | null
}

export type TotaliaAuditLogMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  unitId: string | null
  tableName: string | null
  action: string | null
  ipAddress: string | null
  userAgent: string | null
  createdAt: Date | null
}

export type TotaliaAuditLogCountAggregateOutputType = {
  id: number
  userId: number
  unitId: number
  tableName: number
  action: number
  details: number
  ipAddress: number
  userAgent: number
  createdAt: number
  _all: number
}


export type TotaliaAuditLogMinAggregateInputType = {
  id?: true
  userId?: true
  unitId?: true
  tableName?: true
  action?: true
  ipAddress?: true
  userAgent?: true
  createdAt?: true
}

export type TotaliaAuditLogMaxAggregateInputType = {
  id?: true
  userId?: true
  unitId?: true
  tableName?: true
  action?: true
  ipAddress?: true
  userAgent?: true
  createdAt?: true
}

export type TotaliaAuditLogCountAggregateInputType = {
  id?: true
  userId?: true
  unitId?: true
  tableName?: true
  action?: true
  details?: true
  ipAddress?: true
  userAgent?: true
  createdAt?: true
  _all?: true
}

export type TotaliaAuditLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TotaliaAuditLog to aggregate.
   */
  where?: Prisma.TotaliaAuditLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaAuditLogs to fetch.
   */
  orderBy?: Prisma.TotaliaAuditLogOrderByWithRelationInput | Prisma.TotaliaAuditLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TotaliaAuditLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaAuditLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaAuditLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TotaliaAuditLogs
  **/
  _count?: true | TotaliaAuditLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TotaliaAuditLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TotaliaAuditLogMaxAggregateInputType
}

export type GetTotaliaAuditLogAggregateType<T extends TotaliaAuditLogAggregateArgs> = {
      [P in keyof T & keyof AggregateTotaliaAuditLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTotaliaAuditLog[P]>
    : Prisma.GetScalarType<T[P], AggregateTotaliaAuditLog[P]>
}




export type TotaliaAuditLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TotaliaAuditLogWhereInput
  orderBy?: Prisma.TotaliaAuditLogOrderByWithAggregationInput | Prisma.TotaliaAuditLogOrderByWithAggregationInput[]
  by: Prisma.TotaliaAuditLogScalarFieldEnum[] | Prisma.TotaliaAuditLogScalarFieldEnum
  having?: Prisma.TotaliaAuditLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TotaliaAuditLogCountAggregateInputType | true
  _min?: TotaliaAuditLogMinAggregateInputType
  _max?: TotaliaAuditLogMaxAggregateInputType
}

export type TotaliaAuditLogGroupByOutputType = {
  id: string
  userId: string | null
  unitId: string
  tableName: string | null
  action: string
  details: runtime.JsonValue | null
  ipAddress: string | null
  userAgent: string | null
  createdAt: Date
  _count: TotaliaAuditLogCountAggregateOutputType | null
  _min: TotaliaAuditLogMinAggregateOutputType | null
  _max: TotaliaAuditLogMaxAggregateOutputType | null
}

export type GetTotaliaAuditLogGroupByPayload<T extends TotaliaAuditLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TotaliaAuditLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TotaliaAuditLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TotaliaAuditLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TotaliaAuditLogGroupByOutputType[P]>
      }
    >
  >



export type TotaliaAuditLogWhereInput = {
  AND?: Prisma.TotaliaAuditLogWhereInput | Prisma.TotaliaAuditLogWhereInput[]
  OR?: Prisma.TotaliaAuditLogWhereInput[]
  NOT?: Prisma.TotaliaAuditLogWhereInput | Prisma.TotaliaAuditLogWhereInput[]
  id?: Prisma.StringFilter<"TotaliaAuditLog"> | string
  userId?: Prisma.StringNullableFilter<"TotaliaAuditLog"> | string | null
  unitId?: Prisma.StringFilter<"TotaliaAuditLog"> | string
  tableName?: Prisma.StringNullableFilter<"TotaliaAuditLog"> | string | null
  action?: Prisma.StringFilter<"TotaliaAuditLog"> | string
  details?: Prisma.JsonNullableFilter<"TotaliaAuditLog">
  ipAddress?: Prisma.StringNullableFilter<"TotaliaAuditLog"> | string | null
  userAgent?: Prisma.StringNullableFilter<"TotaliaAuditLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TotaliaAuditLog"> | Date | string
}

export type TotaliaAuditLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  unitId?: Prisma.SortOrder
  tableName?: Prisma.SortOrderInput | Prisma.SortOrder
  action?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _relevance?: Prisma.TotaliaAuditLogOrderByRelevanceInput
}

export type TotaliaAuditLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TotaliaAuditLogWhereInput | Prisma.TotaliaAuditLogWhereInput[]
  OR?: Prisma.TotaliaAuditLogWhereInput[]
  NOT?: Prisma.TotaliaAuditLogWhereInput | Prisma.TotaliaAuditLogWhereInput[]
  userId?: Prisma.StringNullableFilter<"TotaliaAuditLog"> | string | null
  unitId?: Prisma.StringFilter<"TotaliaAuditLog"> | string
  tableName?: Prisma.StringNullableFilter<"TotaliaAuditLog"> | string | null
  action?: Prisma.StringFilter<"TotaliaAuditLog"> | string
  details?: Prisma.JsonNullableFilter<"TotaliaAuditLog">
  ipAddress?: Prisma.StringNullableFilter<"TotaliaAuditLog"> | string | null
  userAgent?: Prisma.StringNullableFilter<"TotaliaAuditLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TotaliaAuditLog"> | Date | string
}, "id">

export type TotaliaAuditLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  unitId?: Prisma.SortOrder
  tableName?: Prisma.SortOrderInput | Prisma.SortOrder
  action?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TotaliaAuditLogCountOrderByAggregateInput
  _max?: Prisma.TotaliaAuditLogMaxOrderByAggregateInput
  _min?: Prisma.TotaliaAuditLogMinOrderByAggregateInput
}

export type TotaliaAuditLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.TotaliaAuditLogScalarWhereWithAggregatesInput | Prisma.TotaliaAuditLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.TotaliaAuditLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TotaliaAuditLogScalarWhereWithAggregatesInput | Prisma.TotaliaAuditLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TotaliaAuditLog"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"TotaliaAuditLog"> | string | null
  unitId?: Prisma.StringWithAggregatesFilter<"TotaliaAuditLog"> | string
  tableName?: Prisma.StringNullableWithAggregatesFilter<"TotaliaAuditLog"> | string | null
  action?: Prisma.StringWithAggregatesFilter<"TotaliaAuditLog"> | string
  details?: Prisma.JsonNullableWithAggregatesFilter<"TotaliaAuditLog">
  ipAddress?: Prisma.StringNullableWithAggregatesFilter<"TotaliaAuditLog"> | string | null
  userAgent?: Prisma.StringNullableWithAggregatesFilter<"TotaliaAuditLog"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TotaliaAuditLog"> | Date | string
}

export type TotaliaAuditLogCreateInput = {
  id?: string
  userId?: string | null
  unitId: string
  tableName?: string | null
  action: string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  ipAddress?: string | null
  userAgent?: string | null
  createdAt?: Date | string
}

export type TotaliaAuditLogUncheckedCreateInput = {
  id?: string
  userId?: string | null
  unitId: string
  tableName?: string | null
  action: string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  ipAddress?: string | null
  userAgent?: string | null
  createdAt?: Date | string
}

export type TotaliaAuditLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  tableName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaAuditLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  tableName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaAuditLogCreateManyInput = {
  id?: string
  userId?: string | null
  unitId: string
  tableName?: string | null
  action: string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  ipAddress?: string | null
  userAgent?: string | null
  createdAt?: Date | string
}

export type TotaliaAuditLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  tableName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaAuditLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  tableName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  action?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaAuditLogOrderByRelevanceInput = {
  fields: Prisma.TotaliaAuditLogOrderByRelevanceFieldEnum | Prisma.TotaliaAuditLogOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type TotaliaAuditLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  tableName?: Prisma.SortOrder
  action?: Prisma.SortOrder
  details?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TotaliaAuditLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  tableName?: Prisma.SortOrder
  action?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TotaliaAuditLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  tableName?: Prisma.SortOrder
  action?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}



export type TotaliaAuditLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  unitId?: boolean
  tableName?: boolean
  action?: boolean
  details?: boolean
  ipAddress?: boolean
  userAgent?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["totaliaAuditLog"]>



export type TotaliaAuditLogSelectScalar = {
  id?: boolean
  userId?: boolean
  unitId?: boolean
  tableName?: boolean
  action?: boolean
  details?: boolean
  ipAddress?: boolean
  userAgent?: boolean
  createdAt?: boolean
}

export type TotaliaAuditLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "unitId" | "tableName" | "action" | "details" | "ipAddress" | "userAgent" | "createdAt", ExtArgs["result"]["totaliaAuditLog"]>

export type $TotaliaAuditLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TotaliaAuditLog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string | null
    unitId: string
    tableName: string | null
    action: string
    details: runtime.JsonValue | null
    ipAddress: string | null
    userAgent: string | null
    createdAt: Date
  }, ExtArgs["result"]["totaliaAuditLog"]>
  composites: {}
}

export type TotaliaAuditLogGetPayload<S extends boolean | null | undefined | TotaliaAuditLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload, S>

export type TotaliaAuditLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TotaliaAuditLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TotaliaAuditLogCountAggregateInputType | true
  }

export interface TotaliaAuditLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TotaliaAuditLog'], meta: { name: 'TotaliaAuditLog' } }
  /**
   * Find zero or one TotaliaAuditLog that matches the filter.
   * @param {TotaliaAuditLogFindUniqueArgs} args - Arguments to find a TotaliaAuditLog
   * @example
   * // Get one TotaliaAuditLog
   * const totaliaAuditLog = await prisma.totaliaAuditLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TotaliaAuditLogFindUniqueArgs>(args: Prisma.SelectSubset<T, TotaliaAuditLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TotaliaAuditLogClient<runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TotaliaAuditLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TotaliaAuditLogFindUniqueOrThrowArgs} args - Arguments to find a TotaliaAuditLog
   * @example
   * // Get one TotaliaAuditLog
   * const totaliaAuditLog = await prisma.totaliaAuditLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TotaliaAuditLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TotaliaAuditLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TotaliaAuditLogClient<runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TotaliaAuditLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaAuditLogFindFirstArgs} args - Arguments to find a TotaliaAuditLog
   * @example
   * // Get one TotaliaAuditLog
   * const totaliaAuditLog = await prisma.totaliaAuditLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TotaliaAuditLogFindFirstArgs>(args?: Prisma.SelectSubset<T, TotaliaAuditLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__TotaliaAuditLogClient<runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TotaliaAuditLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaAuditLogFindFirstOrThrowArgs} args - Arguments to find a TotaliaAuditLog
   * @example
   * // Get one TotaliaAuditLog
   * const totaliaAuditLog = await prisma.totaliaAuditLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TotaliaAuditLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TotaliaAuditLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TotaliaAuditLogClient<runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TotaliaAuditLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaAuditLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TotaliaAuditLogs
   * const totaliaAuditLogs = await prisma.totaliaAuditLog.findMany()
   * 
   * // Get first 10 TotaliaAuditLogs
   * const totaliaAuditLogs = await prisma.totaliaAuditLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const totaliaAuditLogWithIdOnly = await prisma.totaliaAuditLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TotaliaAuditLogFindManyArgs>(args?: Prisma.SelectSubset<T, TotaliaAuditLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TotaliaAuditLog.
   * @param {TotaliaAuditLogCreateArgs} args - Arguments to create a TotaliaAuditLog.
   * @example
   * // Create one TotaliaAuditLog
   * const TotaliaAuditLog = await prisma.totaliaAuditLog.create({
   *   data: {
   *     // ... data to create a TotaliaAuditLog
   *   }
   * })
   * 
   */
  create<T extends TotaliaAuditLogCreateArgs>(args: Prisma.SelectSubset<T, TotaliaAuditLogCreateArgs<ExtArgs>>): Prisma.Prisma__TotaliaAuditLogClient<runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TotaliaAuditLogs.
   * @param {TotaliaAuditLogCreateManyArgs} args - Arguments to create many TotaliaAuditLogs.
   * @example
   * // Create many TotaliaAuditLogs
   * const totaliaAuditLog = await prisma.totaliaAuditLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TotaliaAuditLogCreateManyArgs>(args?: Prisma.SelectSubset<T, TotaliaAuditLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a TotaliaAuditLog.
   * @param {TotaliaAuditLogDeleteArgs} args - Arguments to delete one TotaliaAuditLog.
   * @example
   * // Delete one TotaliaAuditLog
   * const TotaliaAuditLog = await prisma.totaliaAuditLog.delete({
   *   where: {
   *     // ... filter to delete one TotaliaAuditLog
   *   }
   * })
   * 
   */
  delete<T extends TotaliaAuditLogDeleteArgs>(args: Prisma.SelectSubset<T, TotaliaAuditLogDeleteArgs<ExtArgs>>): Prisma.Prisma__TotaliaAuditLogClient<runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TotaliaAuditLog.
   * @param {TotaliaAuditLogUpdateArgs} args - Arguments to update one TotaliaAuditLog.
   * @example
   * // Update one TotaliaAuditLog
   * const totaliaAuditLog = await prisma.totaliaAuditLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TotaliaAuditLogUpdateArgs>(args: Prisma.SelectSubset<T, TotaliaAuditLogUpdateArgs<ExtArgs>>): Prisma.Prisma__TotaliaAuditLogClient<runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TotaliaAuditLogs.
   * @param {TotaliaAuditLogDeleteManyArgs} args - Arguments to filter TotaliaAuditLogs to delete.
   * @example
   * // Delete a few TotaliaAuditLogs
   * const { count } = await prisma.totaliaAuditLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TotaliaAuditLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, TotaliaAuditLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TotaliaAuditLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaAuditLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TotaliaAuditLogs
   * const totaliaAuditLog = await prisma.totaliaAuditLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TotaliaAuditLogUpdateManyArgs>(args: Prisma.SelectSubset<T, TotaliaAuditLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one TotaliaAuditLog.
   * @param {TotaliaAuditLogUpsertArgs} args - Arguments to update or create a TotaliaAuditLog.
   * @example
   * // Update or create a TotaliaAuditLog
   * const totaliaAuditLog = await prisma.totaliaAuditLog.upsert({
   *   create: {
   *     // ... data to create a TotaliaAuditLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TotaliaAuditLog we want to update
   *   }
   * })
   */
  upsert<T extends TotaliaAuditLogUpsertArgs>(args: Prisma.SelectSubset<T, TotaliaAuditLogUpsertArgs<ExtArgs>>): Prisma.Prisma__TotaliaAuditLogClient<runtime.Types.Result.GetResult<Prisma.$TotaliaAuditLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TotaliaAuditLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaAuditLogCountArgs} args - Arguments to filter TotaliaAuditLogs to count.
   * @example
   * // Count the number of TotaliaAuditLogs
   * const count = await prisma.totaliaAuditLog.count({
   *   where: {
   *     // ... the filter for the TotaliaAuditLogs we want to count
   *   }
   * })
  **/
  count<T extends TotaliaAuditLogCountArgs>(
    args?: Prisma.Subset<T, TotaliaAuditLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TotaliaAuditLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TotaliaAuditLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaAuditLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TotaliaAuditLogAggregateArgs>(args: Prisma.Subset<T, TotaliaAuditLogAggregateArgs>): Prisma.PrismaPromise<GetTotaliaAuditLogAggregateType<T>>

  /**
   * Group by TotaliaAuditLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaAuditLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TotaliaAuditLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TotaliaAuditLogGroupByArgs['orderBy'] }
      : { orderBy?: TotaliaAuditLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TotaliaAuditLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTotaliaAuditLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TotaliaAuditLog model
 */
readonly fields: TotaliaAuditLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TotaliaAuditLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TotaliaAuditLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TotaliaAuditLog model
 */
export interface TotaliaAuditLogFieldRefs {
  readonly id: Prisma.FieldRef<"TotaliaAuditLog", 'String'>
  readonly userId: Prisma.FieldRef<"TotaliaAuditLog", 'String'>
  readonly unitId: Prisma.FieldRef<"TotaliaAuditLog", 'String'>
  readonly tableName: Prisma.FieldRef<"TotaliaAuditLog", 'String'>
  readonly action: Prisma.FieldRef<"TotaliaAuditLog", 'String'>
  readonly details: Prisma.FieldRef<"TotaliaAuditLog", 'Json'>
  readonly ipAddress: Prisma.FieldRef<"TotaliaAuditLog", 'String'>
  readonly userAgent: Prisma.FieldRef<"TotaliaAuditLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"TotaliaAuditLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TotaliaAuditLog findUnique
 */
export type TotaliaAuditLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaAuditLog to fetch.
   */
  where: Prisma.TotaliaAuditLogWhereUniqueInput
}

/**
 * TotaliaAuditLog findUniqueOrThrow
 */
export type TotaliaAuditLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaAuditLog to fetch.
   */
  where: Prisma.TotaliaAuditLogWhereUniqueInput
}

/**
 * TotaliaAuditLog findFirst
 */
export type TotaliaAuditLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaAuditLog to fetch.
   */
  where?: Prisma.TotaliaAuditLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaAuditLogs to fetch.
   */
  orderBy?: Prisma.TotaliaAuditLogOrderByWithRelationInput | Prisma.TotaliaAuditLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TotaliaAuditLogs.
   */
  cursor?: Prisma.TotaliaAuditLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaAuditLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaAuditLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TotaliaAuditLogs.
   */
  distinct?: Prisma.TotaliaAuditLogScalarFieldEnum | Prisma.TotaliaAuditLogScalarFieldEnum[]
}

/**
 * TotaliaAuditLog findFirstOrThrow
 */
export type TotaliaAuditLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaAuditLog to fetch.
   */
  where?: Prisma.TotaliaAuditLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaAuditLogs to fetch.
   */
  orderBy?: Prisma.TotaliaAuditLogOrderByWithRelationInput | Prisma.TotaliaAuditLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TotaliaAuditLogs.
   */
  cursor?: Prisma.TotaliaAuditLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaAuditLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaAuditLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TotaliaAuditLogs.
   */
  distinct?: Prisma.TotaliaAuditLogScalarFieldEnum | Prisma.TotaliaAuditLogScalarFieldEnum[]
}

/**
 * TotaliaAuditLog findMany
 */
export type TotaliaAuditLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaAuditLogs to fetch.
   */
  where?: Prisma.TotaliaAuditLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaAuditLogs to fetch.
   */
  orderBy?: Prisma.TotaliaAuditLogOrderByWithRelationInput | Prisma.TotaliaAuditLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TotaliaAuditLogs.
   */
  cursor?: Prisma.TotaliaAuditLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaAuditLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaAuditLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TotaliaAuditLogs.
   */
  distinct?: Prisma.TotaliaAuditLogScalarFieldEnum | Prisma.TotaliaAuditLogScalarFieldEnum[]
}

/**
 * TotaliaAuditLog create
 */
export type TotaliaAuditLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
  /**
   * The data needed to create a TotaliaAuditLog.
   */
  data: Prisma.XOR<Prisma.TotaliaAuditLogCreateInput, Prisma.TotaliaAuditLogUncheckedCreateInput>
}

/**
 * TotaliaAuditLog createMany
 */
export type TotaliaAuditLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TotaliaAuditLogs.
   */
  data: Prisma.TotaliaAuditLogCreateManyInput | Prisma.TotaliaAuditLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TotaliaAuditLog update
 */
export type TotaliaAuditLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
  /**
   * The data needed to update a TotaliaAuditLog.
   */
  data: Prisma.XOR<Prisma.TotaliaAuditLogUpdateInput, Prisma.TotaliaAuditLogUncheckedUpdateInput>
  /**
   * Choose, which TotaliaAuditLog to update.
   */
  where: Prisma.TotaliaAuditLogWhereUniqueInput
}

/**
 * TotaliaAuditLog updateMany
 */
export type TotaliaAuditLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TotaliaAuditLogs.
   */
  data: Prisma.XOR<Prisma.TotaliaAuditLogUpdateManyMutationInput, Prisma.TotaliaAuditLogUncheckedUpdateManyInput>
  /**
   * Filter which TotaliaAuditLogs to update
   */
  where?: Prisma.TotaliaAuditLogWhereInput
  /**
   * Limit how many TotaliaAuditLogs to update.
   */
  limit?: number
}

/**
 * TotaliaAuditLog upsert
 */
export type TotaliaAuditLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
  /**
   * The filter to search for the TotaliaAuditLog to update in case it exists.
   */
  where: Prisma.TotaliaAuditLogWhereUniqueInput
  /**
   * In case the TotaliaAuditLog found by the `where` argument doesn't exist, create a new TotaliaAuditLog with this data.
   */
  create: Prisma.XOR<Prisma.TotaliaAuditLogCreateInput, Prisma.TotaliaAuditLogUncheckedCreateInput>
  /**
   * In case the TotaliaAuditLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TotaliaAuditLogUpdateInput, Prisma.TotaliaAuditLogUncheckedUpdateInput>
}

/**
 * TotaliaAuditLog delete
 */
export type TotaliaAuditLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
  /**
   * Filter which TotaliaAuditLog to delete.
   */
  where: Prisma.TotaliaAuditLogWhereUniqueInput
}

/**
 * TotaliaAuditLog deleteMany
 */
export type TotaliaAuditLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TotaliaAuditLogs to delete
   */
  where?: Prisma.TotaliaAuditLogWhereInput
  /**
   * Limit how many TotaliaAuditLogs to delete.
   */
  limit?: number
}

/**
 * TotaliaAuditLog without action
 */
export type TotaliaAuditLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaAuditLog
   */
  select?: Prisma.TotaliaAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaAuditLog
   */
  omit?: Prisma.TotaliaAuditLogOmit<ExtArgs> | null
}
