
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TotaliaOpportunity` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TotaliaOpportunity
 * 
 */
export type TotaliaOpportunityModel = runtime.Types.Result.DefaultSelection<Prisma.$TotaliaOpportunityPayload>

export type AggregateTotaliaOpportunity = {
  _count: TotaliaOpportunityCountAggregateOutputType | null
  _min: TotaliaOpportunityMinAggregateOutputType | null
  _max: TotaliaOpportunityMaxAggregateOutputType | null
}

export type TotaliaOpportunityMinAggregateOutputType = {
  id: string | null
  unitId: string | null
  title: string | null
  description: string | null
  origin: string | null
  probability: string | null
  impact: string | null
  detectionDate: Date | null
  reviewDate: Date | null
  status: string | null
  assignedTo: string | null
  assignedAt: Date | null
  resolvedAt: Date | null
  resolutionNotes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TotaliaOpportunityMaxAggregateOutputType = {
  id: string | null
  unitId: string | null
  title: string | null
  description: string | null
  origin: string | null
  probability: string | null
  impact: string | null
  detectionDate: Date | null
  reviewDate: Date | null
  status: string | null
  assignedTo: string | null
  assignedAt: Date | null
  resolvedAt: Date | null
  resolutionNotes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TotaliaOpportunityCountAggregateOutputType = {
  id: number
  unitId: number
  title: number
  description: number
  origin: number
  probability: number
  impact: number
  detectionDate: number
  reviewDate: number
  status: number
  assignedTo: number
  assignedAt: number
  resolvedAt: number
  resolutionNotes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TotaliaOpportunityMinAggregateInputType = {
  id?: true
  unitId?: true
  title?: true
  description?: true
  origin?: true
  probability?: true
  impact?: true
  detectionDate?: true
  reviewDate?: true
  status?: true
  assignedTo?: true
  assignedAt?: true
  resolvedAt?: true
  resolutionNotes?: true
  createdAt?: true
  updatedAt?: true
}

export type TotaliaOpportunityMaxAggregateInputType = {
  id?: true
  unitId?: true
  title?: true
  description?: true
  origin?: true
  probability?: true
  impact?: true
  detectionDate?: true
  reviewDate?: true
  status?: true
  assignedTo?: true
  assignedAt?: true
  resolvedAt?: true
  resolutionNotes?: true
  createdAt?: true
  updatedAt?: true
}

export type TotaliaOpportunityCountAggregateInputType = {
  id?: true
  unitId?: true
  title?: true
  description?: true
  origin?: true
  probability?: true
  impact?: true
  detectionDate?: true
  reviewDate?: true
  status?: true
  assignedTo?: true
  assignedAt?: true
  resolvedAt?: true
  resolutionNotes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TotaliaOpportunityAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TotaliaOpportunity to aggregate.
   */
  where?: Prisma.TotaliaOpportunityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaOpportunities to fetch.
   */
  orderBy?: Prisma.TotaliaOpportunityOrderByWithRelationInput | Prisma.TotaliaOpportunityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TotaliaOpportunityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaOpportunities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaOpportunities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TotaliaOpportunities
  **/
  _count?: true | TotaliaOpportunityCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TotaliaOpportunityMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TotaliaOpportunityMaxAggregateInputType
}

export type GetTotaliaOpportunityAggregateType<T extends TotaliaOpportunityAggregateArgs> = {
      [P in keyof T & keyof AggregateTotaliaOpportunity]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTotaliaOpportunity[P]>
    : Prisma.GetScalarType<T[P], AggregateTotaliaOpportunity[P]>
}




export type TotaliaOpportunityGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TotaliaOpportunityWhereInput
  orderBy?: Prisma.TotaliaOpportunityOrderByWithAggregationInput | Prisma.TotaliaOpportunityOrderByWithAggregationInput[]
  by: Prisma.TotaliaOpportunityScalarFieldEnum[] | Prisma.TotaliaOpportunityScalarFieldEnum
  having?: Prisma.TotaliaOpportunityScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TotaliaOpportunityCountAggregateInputType | true
  _min?: TotaliaOpportunityMinAggregateInputType
  _max?: TotaliaOpportunityMaxAggregateInputType
}

export type TotaliaOpportunityGroupByOutputType = {
  id: string
  unitId: string
  title: string
  description: string | null
  origin: string | null
  probability: string | null
  impact: string | null
  detectionDate: Date | null
  reviewDate: Date | null
  status: string
  assignedTo: string | null
  assignedAt: Date | null
  resolvedAt: Date | null
  resolutionNotes: string | null
  createdAt: Date
  updatedAt: Date
  _count: TotaliaOpportunityCountAggregateOutputType | null
  _min: TotaliaOpportunityMinAggregateOutputType | null
  _max: TotaliaOpportunityMaxAggregateOutputType | null
}

export type GetTotaliaOpportunityGroupByPayload<T extends TotaliaOpportunityGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TotaliaOpportunityGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TotaliaOpportunityGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TotaliaOpportunityGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TotaliaOpportunityGroupByOutputType[P]>
      }
    >
  >



export type TotaliaOpportunityWhereInput = {
  AND?: Prisma.TotaliaOpportunityWhereInput | Prisma.TotaliaOpportunityWhereInput[]
  OR?: Prisma.TotaliaOpportunityWhereInput[]
  NOT?: Prisma.TotaliaOpportunityWhereInput | Prisma.TotaliaOpportunityWhereInput[]
  id?: Prisma.StringFilter<"TotaliaOpportunity"> | string
  unitId?: Prisma.StringFilter<"TotaliaOpportunity"> | string
  title?: Prisma.StringFilter<"TotaliaOpportunity"> | string
  description?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  origin?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  probability?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  impact?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  detectionDate?: Prisma.DateTimeNullableFilter<"TotaliaOpportunity"> | Date | string | null
  reviewDate?: Prisma.DateTimeNullableFilter<"TotaliaOpportunity"> | Date | string | null
  status?: Prisma.StringFilter<"TotaliaOpportunity"> | string
  assignedTo?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  assignedAt?: Prisma.DateTimeNullableFilter<"TotaliaOpportunity"> | Date | string | null
  resolvedAt?: Prisma.DateTimeNullableFilter<"TotaliaOpportunity"> | Date | string | null
  resolutionNotes?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TotaliaOpportunity"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TotaliaOpportunity"> | Date | string
}

export type TotaliaOpportunityOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  origin?: Prisma.SortOrderInput | Prisma.SortOrder
  probability?: Prisma.SortOrderInput | Prisma.SortOrder
  impact?: Prisma.SortOrderInput | Prisma.SortOrder
  detectionDate?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewDate?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrderInput | Prisma.SortOrder
  assignedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  resolvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  resolutionNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.TotaliaOpportunityOrderByRelevanceInput
}

export type TotaliaOpportunityWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TotaliaOpportunityWhereInput | Prisma.TotaliaOpportunityWhereInput[]
  OR?: Prisma.TotaliaOpportunityWhereInput[]
  NOT?: Prisma.TotaliaOpportunityWhereInput | Prisma.TotaliaOpportunityWhereInput[]
  unitId?: Prisma.StringFilter<"TotaliaOpportunity"> | string
  title?: Prisma.StringFilter<"TotaliaOpportunity"> | string
  description?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  origin?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  probability?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  impact?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  detectionDate?: Prisma.DateTimeNullableFilter<"TotaliaOpportunity"> | Date | string | null
  reviewDate?: Prisma.DateTimeNullableFilter<"TotaliaOpportunity"> | Date | string | null
  status?: Prisma.StringFilter<"TotaliaOpportunity"> | string
  assignedTo?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  assignedAt?: Prisma.DateTimeNullableFilter<"TotaliaOpportunity"> | Date | string | null
  resolvedAt?: Prisma.DateTimeNullableFilter<"TotaliaOpportunity"> | Date | string | null
  resolutionNotes?: Prisma.StringNullableFilter<"TotaliaOpportunity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TotaliaOpportunity"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TotaliaOpportunity"> | Date | string
}, "id">

export type TotaliaOpportunityOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  origin?: Prisma.SortOrderInput | Prisma.SortOrder
  probability?: Prisma.SortOrderInput | Prisma.SortOrder
  impact?: Prisma.SortOrderInput | Prisma.SortOrder
  detectionDate?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewDate?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrderInput | Prisma.SortOrder
  assignedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  resolvedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  resolutionNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TotaliaOpportunityCountOrderByAggregateInput
  _max?: Prisma.TotaliaOpportunityMaxOrderByAggregateInput
  _min?: Prisma.TotaliaOpportunityMinOrderByAggregateInput
}

export type TotaliaOpportunityScalarWhereWithAggregatesInput = {
  AND?: Prisma.TotaliaOpportunityScalarWhereWithAggregatesInput | Prisma.TotaliaOpportunityScalarWhereWithAggregatesInput[]
  OR?: Prisma.TotaliaOpportunityScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TotaliaOpportunityScalarWhereWithAggregatesInput | Prisma.TotaliaOpportunityScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TotaliaOpportunity"> | string
  unitId?: Prisma.StringWithAggregatesFilter<"TotaliaOpportunity"> | string
  title?: Prisma.StringWithAggregatesFilter<"TotaliaOpportunity"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"TotaliaOpportunity"> | string | null
  origin?: Prisma.StringNullableWithAggregatesFilter<"TotaliaOpportunity"> | string | null
  probability?: Prisma.StringNullableWithAggregatesFilter<"TotaliaOpportunity"> | string | null
  impact?: Prisma.StringNullableWithAggregatesFilter<"TotaliaOpportunity"> | string | null
  detectionDate?: Prisma.DateTimeNullableWithAggregatesFilter<"TotaliaOpportunity"> | Date | string | null
  reviewDate?: Prisma.DateTimeNullableWithAggregatesFilter<"TotaliaOpportunity"> | Date | string | null
  status?: Prisma.StringWithAggregatesFilter<"TotaliaOpportunity"> | string
  assignedTo?: Prisma.StringNullableWithAggregatesFilter<"TotaliaOpportunity"> | string | null
  assignedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TotaliaOpportunity"> | Date | string | null
  resolvedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TotaliaOpportunity"> | Date | string | null
  resolutionNotes?: Prisma.StringNullableWithAggregatesFilter<"TotaliaOpportunity"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TotaliaOpportunity"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TotaliaOpportunity"> | Date | string
}

export type TotaliaOpportunityCreateInput = {
  id?: string
  unitId: string
  title: string
  description?: string | null
  origin?: string | null
  probability?: string | null
  impact?: string | null
  detectionDate?: Date | string | null
  reviewDate?: Date | string | null
  status?: string
  assignedTo?: string | null
  assignedAt?: Date | string | null
  resolvedAt?: Date | string | null
  resolutionNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TotaliaOpportunityUncheckedCreateInput = {
  id?: string
  unitId: string
  title: string
  description?: string | null
  origin?: string | null
  probability?: string | null
  impact?: string | null
  detectionDate?: Date | string | null
  reviewDate?: Date | string | null
  status?: string
  assignedTo?: string | null
  assignedAt?: Date | string | null
  resolvedAt?: Date | string | null
  resolutionNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TotaliaOpportunityUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  probability?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  impact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detectionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaOpportunityUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  probability?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  impact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detectionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaOpportunityCreateManyInput = {
  id?: string
  unitId: string
  title: string
  description?: string | null
  origin?: string | null
  probability?: string | null
  impact?: string | null
  detectionDate?: Date | string | null
  reviewDate?: Date | string | null
  status?: string
  assignedTo?: string | null
  assignedAt?: Date | string | null
  resolvedAt?: Date | string | null
  resolutionNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TotaliaOpportunityUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  probability?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  impact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detectionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaOpportunityUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  probability?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  impact?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detectionDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviewDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolvedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  resolutionNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaOpportunityOrderByRelevanceInput = {
  fields: Prisma.TotaliaOpportunityOrderByRelevanceFieldEnum | Prisma.TotaliaOpportunityOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type TotaliaOpportunityCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  origin?: Prisma.SortOrder
  probability?: Prisma.SortOrder
  impact?: Prisma.SortOrder
  detectionDate?: Prisma.SortOrder
  reviewDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  resolutionNotes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TotaliaOpportunityMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  origin?: Prisma.SortOrder
  probability?: Prisma.SortOrder
  impact?: Prisma.SortOrder
  detectionDate?: Prisma.SortOrder
  reviewDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  resolutionNotes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TotaliaOpportunityMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  origin?: Prisma.SortOrder
  probability?: Prisma.SortOrder
  impact?: Prisma.SortOrder
  detectionDate?: Prisma.SortOrder
  reviewDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  resolutionNotes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type TotaliaOpportunitySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  unitId?: boolean
  title?: boolean
  description?: boolean
  origin?: boolean
  probability?: boolean
  impact?: boolean
  detectionDate?: boolean
  reviewDate?: boolean
  status?: boolean
  assignedTo?: boolean
  assignedAt?: boolean
  resolvedAt?: boolean
  resolutionNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["totaliaOpportunity"]>



export type TotaliaOpportunitySelectScalar = {
  id?: boolean
  unitId?: boolean
  title?: boolean
  description?: boolean
  origin?: boolean
  probability?: boolean
  impact?: boolean
  detectionDate?: boolean
  reviewDate?: boolean
  status?: boolean
  assignedTo?: boolean
  assignedAt?: boolean
  resolvedAt?: boolean
  resolutionNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TotaliaOpportunityOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "unitId" | "title" | "description" | "origin" | "probability" | "impact" | "detectionDate" | "reviewDate" | "status" | "assignedTo" | "assignedAt" | "resolvedAt" | "resolutionNotes" | "createdAt" | "updatedAt", ExtArgs["result"]["totaliaOpportunity"]>

export type $TotaliaOpportunityPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TotaliaOpportunity"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    unitId: string
    title: string
    description: string | null
    origin: string | null
    probability: string | null
    impact: string | null
    detectionDate: Date | null
    reviewDate: Date | null
    status: string
    assignedTo: string | null
    assignedAt: Date | null
    resolvedAt: Date | null
    resolutionNotes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["totaliaOpportunity"]>
  composites: {}
}

export type TotaliaOpportunityGetPayload<S extends boolean | null | undefined | TotaliaOpportunityDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload, S>

export type TotaliaOpportunityCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TotaliaOpportunityFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TotaliaOpportunityCountAggregateInputType | true
  }

export interface TotaliaOpportunityDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TotaliaOpportunity'], meta: { name: 'TotaliaOpportunity' } }
  /**
   * Find zero or one TotaliaOpportunity that matches the filter.
   * @param {TotaliaOpportunityFindUniqueArgs} args - Arguments to find a TotaliaOpportunity
   * @example
   * // Get one TotaliaOpportunity
   * const totaliaOpportunity = await prisma.totaliaOpportunity.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TotaliaOpportunityFindUniqueArgs>(args: Prisma.SelectSubset<T, TotaliaOpportunityFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TotaliaOpportunityClient<runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TotaliaOpportunity that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TotaliaOpportunityFindUniqueOrThrowArgs} args - Arguments to find a TotaliaOpportunity
   * @example
   * // Get one TotaliaOpportunity
   * const totaliaOpportunity = await prisma.totaliaOpportunity.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TotaliaOpportunityFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TotaliaOpportunityFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TotaliaOpportunityClient<runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TotaliaOpportunity that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaOpportunityFindFirstArgs} args - Arguments to find a TotaliaOpportunity
   * @example
   * // Get one TotaliaOpportunity
   * const totaliaOpportunity = await prisma.totaliaOpportunity.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TotaliaOpportunityFindFirstArgs>(args?: Prisma.SelectSubset<T, TotaliaOpportunityFindFirstArgs<ExtArgs>>): Prisma.Prisma__TotaliaOpportunityClient<runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TotaliaOpportunity that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaOpportunityFindFirstOrThrowArgs} args - Arguments to find a TotaliaOpportunity
   * @example
   * // Get one TotaliaOpportunity
   * const totaliaOpportunity = await prisma.totaliaOpportunity.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TotaliaOpportunityFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TotaliaOpportunityFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TotaliaOpportunityClient<runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TotaliaOpportunities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaOpportunityFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TotaliaOpportunities
   * const totaliaOpportunities = await prisma.totaliaOpportunity.findMany()
   * 
   * // Get first 10 TotaliaOpportunities
   * const totaliaOpportunities = await prisma.totaliaOpportunity.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const totaliaOpportunityWithIdOnly = await prisma.totaliaOpportunity.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TotaliaOpportunityFindManyArgs>(args?: Prisma.SelectSubset<T, TotaliaOpportunityFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TotaliaOpportunity.
   * @param {TotaliaOpportunityCreateArgs} args - Arguments to create a TotaliaOpportunity.
   * @example
   * // Create one TotaliaOpportunity
   * const TotaliaOpportunity = await prisma.totaliaOpportunity.create({
   *   data: {
   *     // ... data to create a TotaliaOpportunity
   *   }
   * })
   * 
   */
  create<T extends TotaliaOpportunityCreateArgs>(args: Prisma.SelectSubset<T, TotaliaOpportunityCreateArgs<ExtArgs>>): Prisma.Prisma__TotaliaOpportunityClient<runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TotaliaOpportunities.
   * @param {TotaliaOpportunityCreateManyArgs} args - Arguments to create many TotaliaOpportunities.
   * @example
   * // Create many TotaliaOpportunities
   * const totaliaOpportunity = await prisma.totaliaOpportunity.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TotaliaOpportunityCreateManyArgs>(args?: Prisma.SelectSubset<T, TotaliaOpportunityCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a TotaliaOpportunity.
   * @param {TotaliaOpportunityDeleteArgs} args - Arguments to delete one TotaliaOpportunity.
   * @example
   * // Delete one TotaliaOpportunity
   * const TotaliaOpportunity = await prisma.totaliaOpportunity.delete({
   *   where: {
   *     // ... filter to delete one TotaliaOpportunity
   *   }
   * })
   * 
   */
  delete<T extends TotaliaOpportunityDeleteArgs>(args: Prisma.SelectSubset<T, TotaliaOpportunityDeleteArgs<ExtArgs>>): Prisma.Prisma__TotaliaOpportunityClient<runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TotaliaOpportunity.
   * @param {TotaliaOpportunityUpdateArgs} args - Arguments to update one TotaliaOpportunity.
   * @example
   * // Update one TotaliaOpportunity
   * const totaliaOpportunity = await prisma.totaliaOpportunity.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TotaliaOpportunityUpdateArgs>(args: Prisma.SelectSubset<T, TotaliaOpportunityUpdateArgs<ExtArgs>>): Prisma.Prisma__TotaliaOpportunityClient<runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TotaliaOpportunities.
   * @param {TotaliaOpportunityDeleteManyArgs} args - Arguments to filter TotaliaOpportunities to delete.
   * @example
   * // Delete a few TotaliaOpportunities
   * const { count } = await prisma.totaliaOpportunity.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TotaliaOpportunityDeleteManyArgs>(args?: Prisma.SelectSubset<T, TotaliaOpportunityDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TotaliaOpportunities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaOpportunityUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TotaliaOpportunities
   * const totaliaOpportunity = await prisma.totaliaOpportunity.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TotaliaOpportunityUpdateManyArgs>(args: Prisma.SelectSubset<T, TotaliaOpportunityUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one TotaliaOpportunity.
   * @param {TotaliaOpportunityUpsertArgs} args - Arguments to update or create a TotaliaOpportunity.
   * @example
   * // Update or create a TotaliaOpportunity
   * const totaliaOpportunity = await prisma.totaliaOpportunity.upsert({
   *   create: {
   *     // ... data to create a TotaliaOpportunity
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TotaliaOpportunity we want to update
   *   }
   * })
   */
  upsert<T extends TotaliaOpportunityUpsertArgs>(args: Prisma.SelectSubset<T, TotaliaOpportunityUpsertArgs<ExtArgs>>): Prisma.Prisma__TotaliaOpportunityClient<runtime.Types.Result.GetResult<Prisma.$TotaliaOpportunityPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TotaliaOpportunities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaOpportunityCountArgs} args - Arguments to filter TotaliaOpportunities to count.
   * @example
   * // Count the number of TotaliaOpportunities
   * const count = await prisma.totaliaOpportunity.count({
   *   where: {
   *     // ... the filter for the TotaliaOpportunities we want to count
   *   }
   * })
  **/
  count<T extends TotaliaOpportunityCountArgs>(
    args?: Prisma.Subset<T, TotaliaOpportunityCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TotaliaOpportunityCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TotaliaOpportunity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaOpportunityAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TotaliaOpportunityAggregateArgs>(args: Prisma.Subset<T, TotaliaOpportunityAggregateArgs>): Prisma.PrismaPromise<GetTotaliaOpportunityAggregateType<T>>

  /**
   * Group by TotaliaOpportunity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaOpportunityGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TotaliaOpportunityGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TotaliaOpportunityGroupByArgs['orderBy'] }
      : { orderBy?: TotaliaOpportunityGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TotaliaOpportunityGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTotaliaOpportunityGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TotaliaOpportunity model
 */
readonly fields: TotaliaOpportunityFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TotaliaOpportunity.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TotaliaOpportunityClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TotaliaOpportunity model
 */
export interface TotaliaOpportunityFieldRefs {
  readonly id: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly unitId: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly title: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly description: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly origin: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly probability: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly impact: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly detectionDate: Prisma.FieldRef<"TotaliaOpportunity", 'DateTime'>
  readonly reviewDate: Prisma.FieldRef<"TotaliaOpportunity", 'DateTime'>
  readonly status: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly assignedTo: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly assignedAt: Prisma.FieldRef<"TotaliaOpportunity", 'DateTime'>
  readonly resolvedAt: Prisma.FieldRef<"TotaliaOpportunity", 'DateTime'>
  readonly resolutionNotes: Prisma.FieldRef<"TotaliaOpportunity", 'String'>
  readonly createdAt: Prisma.FieldRef<"TotaliaOpportunity", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TotaliaOpportunity", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TotaliaOpportunity findUnique
 */
export type TotaliaOpportunityFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaOpportunity to fetch.
   */
  where: Prisma.TotaliaOpportunityWhereUniqueInput
}

/**
 * TotaliaOpportunity findUniqueOrThrow
 */
export type TotaliaOpportunityFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaOpportunity to fetch.
   */
  where: Prisma.TotaliaOpportunityWhereUniqueInput
}

/**
 * TotaliaOpportunity findFirst
 */
export type TotaliaOpportunityFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaOpportunity to fetch.
   */
  where?: Prisma.TotaliaOpportunityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaOpportunities to fetch.
   */
  orderBy?: Prisma.TotaliaOpportunityOrderByWithRelationInput | Prisma.TotaliaOpportunityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TotaliaOpportunities.
   */
  cursor?: Prisma.TotaliaOpportunityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaOpportunities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaOpportunities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TotaliaOpportunities.
   */
  distinct?: Prisma.TotaliaOpportunityScalarFieldEnum | Prisma.TotaliaOpportunityScalarFieldEnum[]
}

/**
 * TotaliaOpportunity findFirstOrThrow
 */
export type TotaliaOpportunityFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaOpportunity to fetch.
   */
  where?: Prisma.TotaliaOpportunityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaOpportunities to fetch.
   */
  orderBy?: Prisma.TotaliaOpportunityOrderByWithRelationInput | Prisma.TotaliaOpportunityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TotaliaOpportunities.
   */
  cursor?: Prisma.TotaliaOpportunityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaOpportunities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaOpportunities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TotaliaOpportunities.
   */
  distinct?: Prisma.TotaliaOpportunityScalarFieldEnum | Prisma.TotaliaOpportunityScalarFieldEnum[]
}

/**
 * TotaliaOpportunity findMany
 */
export type TotaliaOpportunityFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
  /**
   * Filter, which TotaliaOpportunities to fetch.
   */
  where?: Prisma.TotaliaOpportunityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaOpportunities to fetch.
   */
  orderBy?: Prisma.TotaliaOpportunityOrderByWithRelationInput | Prisma.TotaliaOpportunityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TotaliaOpportunities.
   */
  cursor?: Prisma.TotaliaOpportunityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaOpportunities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaOpportunities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TotaliaOpportunities.
   */
  distinct?: Prisma.TotaliaOpportunityScalarFieldEnum | Prisma.TotaliaOpportunityScalarFieldEnum[]
}

/**
 * TotaliaOpportunity create
 */
export type TotaliaOpportunityCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
  /**
   * The data needed to create a TotaliaOpportunity.
   */
  data: Prisma.XOR<Prisma.TotaliaOpportunityCreateInput, Prisma.TotaliaOpportunityUncheckedCreateInput>
}

/**
 * TotaliaOpportunity createMany
 */
export type TotaliaOpportunityCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TotaliaOpportunities.
   */
  data: Prisma.TotaliaOpportunityCreateManyInput | Prisma.TotaliaOpportunityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TotaliaOpportunity update
 */
export type TotaliaOpportunityUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
  /**
   * The data needed to update a TotaliaOpportunity.
   */
  data: Prisma.XOR<Prisma.TotaliaOpportunityUpdateInput, Prisma.TotaliaOpportunityUncheckedUpdateInput>
  /**
   * Choose, which TotaliaOpportunity to update.
   */
  where: Prisma.TotaliaOpportunityWhereUniqueInput
}

/**
 * TotaliaOpportunity updateMany
 */
export type TotaliaOpportunityUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TotaliaOpportunities.
   */
  data: Prisma.XOR<Prisma.TotaliaOpportunityUpdateManyMutationInput, Prisma.TotaliaOpportunityUncheckedUpdateManyInput>
  /**
   * Filter which TotaliaOpportunities to update
   */
  where?: Prisma.TotaliaOpportunityWhereInput
  /**
   * Limit how many TotaliaOpportunities to update.
   */
  limit?: number
}

/**
 * TotaliaOpportunity upsert
 */
export type TotaliaOpportunityUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
  /**
   * The filter to search for the TotaliaOpportunity to update in case it exists.
   */
  where: Prisma.TotaliaOpportunityWhereUniqueInput
  /**
   * In case the TotaliaOpportunity found by the `where` argument doesn't exist, create a new TotaliaOpportunity with this data.
   */
  create: Prisma.XOR<Prisma.TotaliaOpportunityCreateInput, Prisma.TotaliaOpportunityUncheckedCreateInput>
  /**
   * In case the TotaliaOpportunity was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TotaliaOpportunityUpdateInput, Prisma.TotaliaOpportunityUncheckedUpdateInput>
}

/**
 * TotaliaOpportunity delete
 */
export type TotaliaOpportunityDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
  /**
   * Filter which TotaliaOpportunity to delete.
   */
  where: Prisma.TotaliaOpportunityWhereUniqueInput
}

/**
 * TotaliaOpportunity deleteMany
 */
export type TotaliaOpportunityDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TotaliaOpportunities to delete
   */
  where?: Prisma.TotaliaOpportunityWhereInput
  /**
   * Limit how many TotaliaOpportunities to delete.
   */
  limit?: number
}

/**
 * TotaliaOpportunity without action
 */
export type TotaliaOpportunityDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaOpportunity
   */
  select?: Prisma.TotaliaOpportunitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaOpportunity
   */
  omit?: Prisma.TotaliaOpportunityOmit<ExtArgs> | null
}
