
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BarbershopConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BarbershopConfig
 * 
 */
export type BarbershopConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$BarbershopConfigPayload>

export type AggregateBarbershopConfig = {
  _count: BarbershopConfigCountAggregateOutputType | null
  _min: BarbershopConfigMinAggregateOutputType | null
  _max: BarbershopConfigMaxAggregateOutputType | null
}

export type BarbershopConfigMinAggregateOutputType = {
  id: string | null
  unitId: string | null
  chave: string | null
}

export type BarbershopConfigMaxAggregateOutputType = {
  id: string | null
  unitId: string | null
  chave: string | null
}

export type BarbershopConfigCountAggregateOutputType = {
  id: number
  unitId: number
  chave: number
  valor: number
  _all: number
}


export type BarbershopConfigMinAggregateInputType = {
  id?: true
  unitId?: true
  chave?: true
}

export type BarbershopConfigMaxAggregateInputType = {
  id?: true
  unitId?: true
  chave?: true
}

export type BarbershopConfigCountAggregateInputType = {
  id?: true
  unitId?: true
  chave?: true
  valor?: true
  _all?: true
}

export type BarbershopConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BarbershopConfig to aggregate.
   */
  where?: Prisma.BarbershopConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarbershopConfigs to fetch.
   */
  orderBy?: Prisma.BarbershopConfigOrderByWithRelationInput | Prisma.BarbershopConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BarbershopConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarbershopConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarbershopConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BarbershopConfigs
  **/
  _count?: true | BarbershopConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BarbershopConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BarbershopConfigMaxAggregateInputType
}

export type GetBarbershopConfigAggregateType<T extends BarbershopConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateBarbershopConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBarbershopConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateBarbershopConfig[P]>
}




export type BarbershopConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BarbershopConfigWhereInput
  orderBy?: Prisma.BarbershopConfigOrderByWithAggregationInput | Prisma.BarbershopConfigOrderByWithAggregationInput[]
  by: Prisma.BarbershopConfigScalarFieldEnum[] | Prisma.BarbershopConfigScalarFieldEnum
  having?: Prisma.BarbershopConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BarbershopConfigCountAggregateInputType | true
  _min?: BarbershopConfigMinAggregateInputType
  _max?: BarbershopConfigMaxAggregateInputType
}

export type BarbershopConfigGroupByOutputType = {
  id: string
  unitId: string
  chave: string
  valor: runtime.JsonValue
  _count: BarbershopConfigCountAggregateOutputType | null
  _min: BarbershopConfigMinAggregateOutputType | null
  _max: BarbershopConfigMaxAggregateOutputType | null
}

export type GetBarbershopConfigGroupByPayload<T extends BarbershopConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BarbershopConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BarbershopConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BarbershopConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BarbershopConfigGroupByOutputType[P]>
      }
    >
  >



export type BarbershopConfigWhereInput = {
  AND?: Prisma.BarbershopConfigWhereInput | Prisma.BarbershopConfigWhereInput[]
  OR?: Prisma.BarbershopConfigWhereInput[]
  NOT?: Prisma.BarbershopConfigWhereInput | Prisma.BarbershopConfigWhereInput[]
  id?: Prisma.StringFilter<"BarbershopConfig"> | string
  unitId?: Prisma.StringFilter<"BarbershopConfig"> | string
  chave?: Prisma.StringFilter<"BarbershopConfig"> | string
  valor?: Prisma.JsonFilter<"BarbershopConfig">
}

export type BarbershopConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  chave?: Prisma.SortOrder
  valor?: Prisma.SortOrder
  _relevance?: Prisma.BarbershopConfigOrderByRelevanceInput
}

export type BarbershopConfigWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  unitId_chave?: Prisma.BarbershopConfigUnitIdChaveCompoundUniqueInput
  AND?: Prisma.BarbershopConfigWhereInput | Prisma.BarbershopConfigWhereInput[]
  OR?: Prisma.BarbershopConfigWhereInput[]
  NOT?: Prisma.BarbershopConfigWhereInput | Prisma.BarbershopConfigWhereInput[]
  unitId?: Prisma.StringFilter<"BarbershopConfig"> | string
  chave?: Prisma.StringFilter<"BarbershopConfig"> | string
  valor?: Prisma.JsonFilter<"BarbershopConfig">
}, "id" | "unitId_chave">

export type BarbershopConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  chave?: Prisma.SortOrder
  valor?: Prisma.SortOrder
  _count?: Prisma.BarbershopConfigCountOrderByAggregateInput
  _max?: Prisma.BarbershopConfigMaxOrderByAggregateInput
  _min?: Prisma.BarbershopConfigMinOrderByAggregateInput
}

export type BarbershopConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.BarbershopConfigScalarWhereWithAggregatesInput | Prisma.BarbershopConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.BarbershopConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BarbershopConfigScalarWhereWithAggregatesInput | Prisma.BarbershopConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BarbershopConfig"> | string
  unitId?: Prisma.StringWithAggregatesFilter<"BarbershopConfig"> | string
  chave?: Prisma.StringWithAggregatesFilter<"BarbershopConfig"> | string
  valor?: Prisma.JsonWithAggregatesFilter<"BarbershopConfig">
}

export type BarbershopConfigCreateInput = {
  id?: string
  unitId: string
  chave: string
  valor: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type BarbershopConfigUncheckedCreateInput = {
  id?: string
  unitId: string
  chave: string
  valor: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type BarbershopConfigUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  chave?: Prisma.StringFieldUpdateOperationsInput | string
  valor?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type BarbershopConfigUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  chave?: Prisma.StringFieldUpdateOperationsInput | string
  valor?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type BarbershopConfigCreateManyInput = {
  id?: string
  unitId: string
  chave: string
  valor: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type BarbershopConfigUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  chave?: Prisma.StringFieldUpdateOperationsInput | string
  valor?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type BarbershopConfigUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  chave?: Prisma.StringFieldUpdateOperationsInput | string
  valor?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type BarbershopConfigOrderByRelevanceInput = {
  fields: Prisma.BarbershopConfigOrderByRelevanceFieldEnum | Prisma.BarbershopConfigOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type BarbershopConfigUnitIdChaveCompoundUniqueInput = {
  unitId: string
  chave: string
}

export type BarbershopConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  chave?: Prisma.SortOrder
  valor?: Prisma.SortOrder
}

export type BarbershopConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  chave?: Prisma.SortOrder
}

export type BarbershopConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  chave?: Prisma.SortOrder
}



export type BarbershopConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  unitId?: boolean
  chave?: boolean
  valor?: boolean
}, ExtArgs["result"]["barbershopConfig"]>



export type BarbershopConfigSelectScalar = {
  id?: boolean
  unitId?: boolean
  chave?: boolean
  valor?: boolean
}

export type BarbershopConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "unitId" | "chave" | "valor", ExtArgs["result"]["barbershopConfig"]>

export type $BarbershopConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BarbershopConfig"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    unitId: string
    chave: string
    valor: runtime.JsonValue
  }, ExtArgs["result"]["barbershopConfig"]>
  composites: {}
}

export type BarbershopConfigGetPayload<S extends boolean | null | undefined | BarbershopConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload, S>

export type BarbershopConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BarbershopConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BarbershopConfigCountAggregateInputType | true
  }

export interface BarbershopConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BarbershopConfig'], meta: { name: 'BarbershopConfig' } }
  /**
   * Find zero or one BarbershopConfig that matches the filter.
   * @param {BarbershopConfigFindUniqueArgs} args - Arguments to find a BarbershopConfig
   * @example
   * // Get one BarbershopConfig
   * const barbershopConfig = await prisma.barbershopConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BarbershopConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, BarbershopConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BarbershopConfigClient<runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BarbershopConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BarbershopConfigFindUniqueOrThrowArgs} args - Arguments to find a BarbershopConfig
   * @example
   * // Get one BarbershopConfig
   * const barbershopConfig = await prisma.barbershopConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BarbershopConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BarbershopConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BarbershopConfigClient<runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BarbershopConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarbershopConfigFindFirstArgs} args - Arguments to find a BarbershopConfig
   * @example
   * // Get one BarbershopConfig
   * const barbershopConfig = await prisma.barbershopConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BarbershopConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, BarbershopConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__BarbershopConfigClient<runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BarbershopConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarbershopConfigFindFirstOrThrowArgs} args - Arguments to find a BarbershopConfig
   * @example
   * // Get one BarbershopConfig
   * const barbershopConfig = await prisma.barbershopConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BarbershopConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BarbershopConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BarbershopConfigClient<runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BarbershopConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarbershopConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BarbershopConfigs
   * const barbershopConfigs = await prisma.barbershopConfig.findMany()
   * 
   * // Get first 10 BarbershopConfigs
   * const barbershopConfigs = await prisma.barbershopConfig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const barbershopConfigWithIdOnly = await prisma.barbershopConfig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BarbershopConfigFindManyArgs>(args?: Prisma.SelectSubset<T, BarbershopConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BarbershopConfig.
   * @param {BarbershopConfigCreateArgs} args - Arguments to create a BarbershopConfig.
   * @example
   * // Create one BarbershopConfig
   * const BarbershopConfig = await prisma.barbershopConfig.create({
   *   data: {
   *     // ... data to create a BarbershopConfig
   *   }
   * })
   * 
   */
  create<T extends BarbershopConfigCreateArgs>(args: Prisma.SelectSubset<T, BarbershopConfigCreateArgs<ExtArgs>>): Prisma.Prisma__BarbershopConfigClient<runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BarbershopConfigs.
   * @param {BarbershopConfigCreateManyArgs} args - Arguments to create many BarbershopConfigs.
   * @example
   * // Create many BarbershopConfigs
   * const barbershopConfig = await prisma.barbershopConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BarbershopConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, BarbershopConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a BarbershopConfig.
   * @param {BarbershopConfigDeleteArgs} args - Arguments to delete one BarbershopConfig.
   * @example
   * // Delete one BarbershopConfig
   * const BarbershopConfig = await prisma.barbershopConfig.delete({
   *   where: {
   *     // ... filter to delete one BarbershopConfig
   *   }
   * })
   * 
   */
  delete<T extends BarbershopConfigDeleteArgs>(args: Prisma.SelectSubset<T, BarbershopConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__BarbershopConfigClient<runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BarbershopConfig.
   * @param {BarbershopConfigUpdateArgs} args - Arguments to update one BarbershopConfig.
   * @example
   * // Update one BarbershopConfig
   * const barbershopConfig = await prisma.barbershopConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BarbershopConfigUpdateArgs>(args: Prisma.SelectSubset<T, BarbershopConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__BarbershopConfigClient<runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BarbershopConfigs.
   * @param {BarbershopConfigDeleteManyArgs} args - Arguments to filter BarbershopConfigs to delete.
   * @example
   * // Delete a few BarbershopConfigs
   * const { count } = await prisma.barbershopConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BarbershopConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, BarbershopConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BarbershopConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarbershopConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BarbershopConfigs
   * const barbershopConfig = await prisma.barbershopConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BarbershopConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, BarbershopConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one BarbershopConfig.
   * @param {BarbershopConfigUpsertArgs} args - Arguments to update or create a BarbershopConfig.
   * @example
   * // Update or create a BarbershopConfig
   * const barbershopConfig = await prisma.barbershopConfig.upsert({
   *   create: {
   *     // ... data to create a BarbershopConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BarbershopConfig we want to update
   *   }
   * })
   */
  upsert<T extends BarbershopConfigUpsertArgs>(args: Prisma.SelectSubset<T, BarbershopConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__BarbershopConfigClient<runtime.Types.Result.GetResult<Prisma.$BarbershopConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BarbershopConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarbershopConfigCountArgs} args - Arguments to filter BarbershopConfigs to count.
   * @example
   * // Count the number of BarbershopConfigs
   * const count = await prisma.barbershopConfig.count({
   *   where: {
   *     // ... the filter for the BarbershopConfigs we want to count
   *   }
   * })
  **/
  count<T extends BarbershopConfigCountArgs>(
    args?: Prisma.Subset<T, BarbershopConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BarbershopConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BarbershopConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarbershopConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BarbershopConfigAggregateArgs>(args: Prisma.Subset<T, BarbershopConfigAggregateArgs>): Prisma.PrismaPromise<GetBarbershopConfigAggregateType<T>>

  /**
   * Group by BarbershopConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BarbershopConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BarbershopConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BarbershopConfigGroupByArgs['orderBy'] }
      : { orderBy?: BarbershopConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BarbershopConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBarbershopConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BarbershopConfig model
 */
readonly fields: BarbershopConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BarbershopConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BarbershopConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BarbershopConfig model
 */
export interface BarbershopConfigFieldRefs {
  readonly id: Prisma.FieldRef<"BarbershopConfig", 'String'>
  readonly unitId: Prisma.FieldRef<"BarbershopConfig", 'String'>
  readonly chave: Prisma.FieldRef<"BarbershopConfig", 'String'>
  readonly valor: Prisma.FieldRef<"BarbershopConfig", 'Json'>
}
    

// Custom InputTypes
/**
 * BarbershopConfig findUnique
 */
export type BarbershopConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
  /**
   * Filter, which BarbershopConfig to fetch.
   */
  where: Prisma.BarbershopConfigWhereUniqueInput
}

/**
 * BarbershopConfig findUniqueOrThrow
 */
export type BarbershopConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
  /**
   * Filter, which BarbershopConfig to fetch.
   */
  where: Prisma.BarbershopConfigWhereUniqueInput
}

/**
 * BarbershopConfig findFirst
 */
export type BarbershopConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
  /**
   * Filter, which BarbershopConfig to fetch.
   */
  where?: Prisma.BarbershopConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarbershopConfigs to fetch.
   */
  orderBy?: Prisma.BarbershopConfigOrderByWithRelationInput | Prisma.BarbershopConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BarbershopConfigs.
   */
  cursor?: Prisma.BarbershopConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarbershopConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarbershopConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BarbershopConfigs.
   */
  distinct?: Prisma.BarbershopConfigScalarFieldEnum | Prisma.BarbershopConfigScalarFieldEnum[]
}

/**
 * BarbershopConfig findFirstOrThrow
 */
export type BarbershopConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
  /**
   * Filter, which BarbershopConfig to fetch.
   */
  where?: Prisma.BarbershopConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarbershopConfigs to fetch.
   */
  orderBy?: Prisma.BarbershopConfigOrderByWithRelationInput | Prisma.BarbershopConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BarbershopConfigs.
   */
  cursor?: Prisma.BarbershopConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarbershopConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarbershopConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BarbershopConfigs.
   */
  distinct?: Prisma.BarbershopConfigScalarFieldEnum | Prisma.BarbershopConfigScalarFieldEnum[]
}

/**
 * BarbershopConfig findMany
 */
export type BarbershopConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
  /**
   * Filter, which BarbershopConfigs to fetch.
   */
  where?: Prisma.BarbershopConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BarbershopConfigs to fetch.
   */
  orderBy?: Prisma.BarbershopConfigOrderByWithRelationInput | Prisma.BarbershopConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BarbershopConfigs.
   */
  cursor?: Prisma.BarbershopConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BarbershopConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BarbershopConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BarbershopConfigs.
   */
  distinct?: Prisma.BarbershopConfigScalarFieldEnum | Prisma.BarbershopConfigScalarFieldEnum[]
}

/**
 * BarbershopConfig create
 */
export type BarbershopConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
  /**
   * The data needed to create a BarbershopConfig.
   */
  data: Prisma.XOR<Prisma.BarbershopConfigCreateInput, Prisma.BarbershopConfigUncheckedCreateInput>
}

/**
 * BarbershopConfig createMany
 */
export type BarbershopConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BarbershopConfigs.
   */
  data: Prisma.BarbershopConfigCreateManyInput | Prisma.BarbershopConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BarbershopConfig update
 */
export type BarbershopConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
  /**
   * The data needed to update a BarbershopConfig.
   */
  data: Prisma.XOR<Prisma.BarbershopConfigUpdateInput, Prisma.BarbershopConfigUncheckedUpdateInput>
  /**
   * Choose, which BarbershopConfig to update.
   */
  where: Prisma.BarbershopConfigWhereUniqueInput
}

/**
 * BarbershopConfig updateMany
 */
export type BarbershopConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BarbershopConfigs.
   */
  data: Prisma.XOR<Prisma.BarbershopConfigUpdateManyMutationInput, Prisma.BarbershopConfigUncheckedUpdateManyInput>
  /**
   * Filter which BarbershopConfigs to update
   */
  where?: Prisma.BarbershopConfigWhereInput
  /**
   * Limit how many BarbershopConfigs to update.
   */
  limit?: number
}

/**
 * BarbershopConfig upsert
 */
export type BarbershopConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
  /**
   * The filter to search for the BarbershopConfig to update in case it exists.
   */
  where: Prisma.BarbershopConfigWhereUniqueInput
  /**
   * In case the BarbershopConfig found by the `where` argument doesn't exist, create a new BarbershopConfig with this data.
   */
  create: Prisma.XOR<Prisma.BarbershopConfigCreateInput, Prisma.BarbershopConfigUncheckedCreateInput>
  /**
   * In case the BarbershopConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BarbershopConfigUpdateInput, Prisma.BarbershopConfigUncheckedUpdateInput>
}

/**
 * BarbershopConfig delete
 */
export type BarbershopConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
  /**
   * Filter which BarbershopConfig to delete.
   */
  where: Prisma.BarbershopConfigWhereUniqueInput
}

/**
 * BarbershopConfig deleteMany
 */
export type BarbershopConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BarbershopConfigs to delete
   */
  where?: Prisma.BarbershopConfigWhereInput
  /**
   * Limit how many BarbershopConfigs to delete.
   */
  limit?: number
}

/**
 * BarbershopConfig without action
 */
export type BarbershopConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BarbershopConfig
   */
  select?: Prisma.BarbershopConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BarbershopConfig
   */
  omit?: Prisma.BarbershopConfigOmit<ExtArgs> | null
}
