
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TotaliaProduct` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TotaliaProduct
 * 
 */
export type TotaliaProductModel = runtime.Types.Result.DefaultSelection<Prisma.$TotaliaProductPayload>

export type AggregateTotaliaProduct = {
  _count: TotaliaProductCountAggregateOutputType | null
  _avg: TotaliaProductAvgAggregateOutputType | null
  _sum: TotaliaProductSumAggregateOutputType | null
  _min: TotaliaProductMinAggregateOutputType | null
  _max: TotaliaProductMaxAggregateOutputType | null
}

export type TotaliaProductAvgAggregateOutputType = {
  unitPrice: number | null
  currentStock: number | null
  minStock: number | null
}

export type TotaliaProductSumAggregateOutputType = {
  unitPrice: number | null
  currentStock: number | null
  minStock: number | null
}

export type TotaliaProductMinAggregateOutputType = {
  id: string | null
  unitId: string | null
  name: string | null
  sku: string | null
  description: string | null
  category: string | null
  unitOfMeasure: string | null
  unitPrice: number | null
  currentStock: number | null
  minStock: number | null
  status: string | null
  supplierId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TotaliaProductMaxAggregateOutputType = {
  id: string | null
  unitId: string | null
  name: string | null
  sku: string | null
  description: string | null
  category: string | null
  unitOfMeasure: string | null
  unitPrice: number | null
  currentStock: number | null
  minStock: number | null
  status: string | null
  supplierId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TotaliaProductCountAggregateOutputType = {
  id: number
  unitId: number
  name: number
  sku: number
  description: number
  category: number
  unitOfMeasure: number
  unitPrice: number
  currentStock: number
  minStock: number
  status: number
  supplierId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TotaliaProductAvgAggregateInputType = {
  unitPrice?: true
  currentStock?: true
  minStock?: true
}

export type TotaliaProductSumAggregateInputType = {
  unitPrice?: true
  currentStock?: true
  minStock?: true
}

export type TotaliaProductMinAggregateInputType = {
  id?: true
  unitId?: true
  name?: true
  sku?: true
  description?: true
  category?: true
  unitOfMeasure?: true
  unitPrice?: true
  currentStock?: true
  minStock?: true
  status?: true
  supplierId?: true
  createdAt?: true
  updatedAt?: true
}

export type TotaliaProductMaxAggregateInputType = {
  id?: true
  unitId?: true
  name?: true
  sku?: true
  description?: true
  category?: true
  unitOfMeasure?: true
  unitPrice?: true
  currentStock?: true
  minStock?: true
  status?: true
  supplierId?: true
  createdAt?: true
  updatedAt?: true
}

export type TotaliaProductCountAggregateInputType = {
  id?: true
  unitId?: true
  name?: true
  sku?: true
  description?: true
  category?: true
  unitOfMeasure?: true
  unitPrice?: true
  currentStock?: true
  minStock?: true
  status?: true
  supplierId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TotaliaProductAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TotaliaProduct to aggregate.
   */
  where?: Prisma.TotaliaProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaProducts to fetch.
   */
  orderBy?: Prisma.TotaliaProductOrderByWithRelationInput | Prisma.TotaliaProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TotaliaProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TotaliaProducts
  **/
  _count?: true | TotaliaProductCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TotaliaProductAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TotaliaProductSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TotaliaProductMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TotaliaProductMaxAggregateInputType
}

export type GetTotaliaProductAggregateType<T extends TotaliaProductAggregateArgs> = {
      [P in keyof T & keyof AggregateTotaliaProduct]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTotaliaProduct[P]>
    : Prisma.GetScalarType<T[P], AggregateTotaliaProduct[P]>
}




export type TotaliaProductGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TotaliaProductWhereInput
  orderBy?: Prisma.TotaliaProductOrderByWithAggregationInput | Prisma.TotaliaProductOrderByWithAggregationInput[]
  by: Prisma.TotaliaProductScalarFieldEnum[] | Prisma.TotaliaProductScalarFieldEnum
  having?: Prisma.TotaliaProductScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TotaliaProductCountAggregateInputType | true
  _avg?: TotaliaProductAvgAggregateInputType
  _sum?: TotaliaProductSumAggregateInputType
  _min?: TotaliaProductMinAggregateInputType
  _max?: TotaliaProductMaxAggregateInputType
}

export type TotaliaProductGroupByOutputType = {
  id: string
  unitId: string
  name: string
  sku: string | null
  description: string | null
  category: string | null
  unitOfMeasure: string | null
  unitPrice: number
  currentStock: number
  minStock: number
  status: string
  supplierId: string | null
  createdAt: Date
  updatedAt: Date
  _count: TotaliaProductCountAggregateOutputType | null
  _avg: TotaliaProductAvgAggregateOutputType | null
  _sum: TotaliaProductSumAggregateOutputType | null
  _min: TotaliaProductMinAggregateOutputType | null
  _max: TotaliaProductMaxAggregateOutputType | null
}

export type GetTotaliaProductGroupByPayload<T extends TotaliaProductGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TotaliaProductGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TotaliaProductGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TotaliaProductGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TotaliaProductGroupByOutputType[P]>
      }
    >
  >



export type TotaliaProductWhereInput = {
  AND?: Prisma.TotaliaProductWhereInput | Prisma.TotaliaProductWhereInput[]
  OR?: Prisma.TotaliaProductWhereInput[]
  NOT?: Prisma.TotaliaProductWhereInput | Prisma.TotaliaProductWhereInput[]
  id?: Prisma.StringFilter<"TotaliaProduct"> | string
  unitId?: Prisma.StringFilter<"TotaliaProduct"> | string
  name?: Prisma.StringFilter<"TotaliaProduct"> | string
  sku?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  description?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  category?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  unitOfMeasure?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  unitPrice?: Prisma.FloatFilter<"TotaliaProduct"> | number
  currentStock?: Prisma.FloatFilter<"TotaliaProduct"> | number
  minStock?: Prisma.FloatFilter<"TotaliaProduct"> | number
  status?: Prisma.StringFilter<"TotaliaProduct"> | string
  supplierId?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TotaliaProduct"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TotaliaProduct"> | Date | string
  supplier?: Prisma.XOR<Prisma.TotaliaSupplierNullableScalarRelationFilter, Prisma.TotaliaSupplierWhereInput> | null
  orderItems?: Prisma.TotaliaPurchaseOrderItemListRelationFilter
}

export type TotaliaProductOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sku?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  unitOfMeasure?: Prisma.SortOrderInput | Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currentStock?: Prisma.SortOrder
  minStock?: Prisma.SortOrder
  status?: Prisma.SortOrder
  supplierId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  supplier?: Prisma.TotaliaSupplierOrderByWithRelationInput
  orderItems?: Prisma.TotaliaPurchaseOrderItemOrderByRelationAggregateInput
  _relevance?: Prisma.TotaliaProductOrderByRelevanceInput
}

export type TotaliaProductWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TotaliaProductWhereInput | Prisma.TotaliaProductWhereInput[]
  OR?: Prisma.TotaliaProductWhereInput[]
  NOT?: Prisma.TotaliaProductWhereInput | Prisma.TotaliaProductWhereInput[]
  unitId?: Prisma.StringFilter<"TotaliaProduct"> | string
  name?: Prisma.StringFilter<"TotaliaProduct"> | string
  sku?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  description?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  category?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  unitOfMeasure?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  unitPrice?: Prisma.FloatFilter<"TotaliaProduct"> | number
  currentStock?: Prisma.FloatFilter<"TotaliaProduct"> | number
  minStock?: Prisma.FloatFilter<"TotaliaProduct"> | number
  status?: Prisma.StringFilter<"TotaliaProduct"> | string
  supplierId?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TotaliaProduct"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TotaliaProduct"> | Date | string
  supplier?: Prisma.XOR<Prisma.TotaliaSupplierNullableScalarRelationFilter, Prisma.TotaliaSupplierWhereInput> | null
  orderItems?: Prisma.TotaliaPurchaseOrderItemListRelationFilter
}, "id">

export type TotaliaProductOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sku?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  unitOfMeasure?: Prisma.SortOrderInput | Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currentStock?: Prisma.SortOrder
  minStock?: Prisma.SortOrder
  status?: Prisma.SortOrder
  supplierId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TotaliaProductCountOrderByAggregateInput
  _avg?: Prisma.TotaliaProductAvgOrderByAggregateInput
  _max?: Prisma.TotaliaProductMaxOrderByAggregateInput
  _min?: Prisma.TotaliaProductMinOrderByAggregateInput
  _sum?: Prisma.TotaliaProductSumOrderByAggregateInput
}

export type TotaliaProductScalarWhereWithAggregatesInput = {
  AND?: Prisma.TotaliaProductScalarWhereWithAggregatesInput | Prisma.TotaliaProductScalarWhereWithAggregatesInput[]
  OR?: Prisma.TotaliaProductScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TotaliaProductScalarWhereWithAggregatesInput | Prisma.TotaliaProductScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TotaliaProduct"> | string
  unitId?: Prisma.StringWithAggregatesFilter<"TotaliaProduct"> | string
  name?: Prisma.StringWithAggregatesFilter<"TotaliaProduct"> | string
  sku?: Prisma.StringNullableWithAggregatesFilter<"TotaliaProduct"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"TotaliaProduct"> | string | null
  category?: Prisma.StringNullableWithAggregatesFilter<"TotaliaProduct"> | string | null
  unitOfMeasure?: Prisma.StringNullableWithAggregatesFilter<"TotaliaProduct"> | string | null
  unitPrice?: Prisma.FloatWithAggregatesFilter<"TotaliaProduct"> | number
  currentStock?: Prisma.FloatWithAggregatesFilter<"TotaliaProduct"> | number
  minStock?: Prisma.FloatWithAggregatesFilter<"TotaliaProduct"> | number
  status?: Prisma.StringWithAggregatesFilter<"TotaliaProduct"> | string
  supplierId?: Prisma.StringNullableWithAggregatesFilter<"TotaliaProduct"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TotaliaProduct"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TotaliaProduct"> | Date | string
}

export type TotaliaProductCreateInput = {
  id?: string
  unitId: string
  name: string
  sku?: string | null
  description?: string | null
  category?: string | null
  unitOfMeasure?: string | null
  unitPrice?: number
  currentStock?: number
  minStock?: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  supplier?: Prisma.TotaliaSupplierCreateNestedOneWithoutProductsInput
  orderItems?: Prisma.TotaliaPurchaseOrderItemCreateNestedManyWithoutProductInput
}

export type TotaliaProductUncheckedCreateInput = {
  id?: string
  unitId: string
  name: string
  sku?: string | null
  description?: string | null
  category?: string | null
  unitOfMeasure?: string | null
  unitPrice?: number
  currentStock?: number
  minStock?: number
  status?: string
  supplierId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  orderItems?: Prisma.TotaliaPurchaseOrderItemUncheckedCreateNestedManyWithoutProductInput
}

export type TotaliaProductUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sku?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitOfMeasure?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  currentStock?: Prisma.FloatFieldUpdateOperationsInput | number
  minStock?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  supplier?: Prisma.TotaliaSupplierUpdateOneWithoutProductsNestedInput
  orderItems?: Prisma.TotaliaPurchaseOrderItemUpdateManyWithoutProductNestedInput
}

export type TotaliaProductUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sku?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitOfMeasure?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  currentStock?: Prisma.FloatFieldUpdateOperationsInput | number
  minStock?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orderItems?: Prisma.TotaliaPurchaseOrderItemUncheckedUpdateManyWithoutProductNestedInput
}

export type TotaliaProductCreateManyInput = {
  id?: string
  unitId: string
  name: string
  sku?: string | null
  description?: string | null
  category?: string | null
  unitOfMeasure?: string | null
  unitPrice?: number
  currentStock?: number
  minStock?: number
  status?: string
  supplierId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TotaliaProductUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sku?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitOfMeasure?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  currentStock?: Prisma.FloatFieldUpdateOperationsInput | number
  minStock?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaProductUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sku?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitOfMeasure?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  currentStock?: Prisma.FloatFieldUpdateOperationsInput | number
  minStock?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaProductListRelationFilter = {
  every?: Prisma.TotaliaProductWhereInput
  some?: Prisma.TotaliaProductWhereInput
  none?: Prisma.TotaliaProductWhereInput
}

export type TotaliaProductOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TotaliaProductOrderByRelevanceInput = {
  fields: Prisma.TotaliaProductOrderByRelevanceFieldEnum | Prisma.TotaliaProductOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type TotaliaProductCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sku?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  unitOfMeasure?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currentStock?: Prisma.SortOrder
  minStock?: Prisma.SortOrder
  status?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TotaliaProductAvgOrderByAggregateInput = {
  unitPrice?: Prisma.SortOrder
  currentStock?: Prisma.SortOrder
  minStock?: Prisma.SortOrder
}

export type TotaliaProductMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sku?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  unitOfMeasure?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currentStock?: Prisma.SortOrder
  minStock?: Prisma.SortOrder
  status?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TotaliaProductMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sku?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  unitOfMeasure?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currentStock?: Prisma.SortOrder
  minStock?: Prisma.SortOrder
  status?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TotaliaProductSumOrderByAggregateInput = {
  unitPrice?: Prisma.SortOrder
  currentStock?: Prisma.SortOrder
  minStock?: Prisma.SortOrder
}

export type TotaliaProductNullableScalarRelationFilter = {
  is?: Prisma.TotaliaProductWhereInput | null
  isNot?: Prisma.TotaliaProductWhereInput | null
}

export type TotaliaProductCreateNestedManyWithoutSupplierInput = {
  create?: Prisma.XOR<Prisma.TotaliaProductCreateWithoutSupplierInput, Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput> | Prisma.TotaliaProductCreateWithoutSupplierInput[] | Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.TotaliaProductCreateOrConnectWithoutSupplierInput | Prisma.TotaliaProductCreateOrConnectWithoutSupplierInput[]
  createMany?: Prisma.TotaliaProductCreateManySupplierInputEnvelope
  connect?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
}

export type TotaliaProductUncheckedCreateNestedManyWithoutSupplierInput = {
  create?: Prisma.XOR<Prisma.TotaliaProductCreateWithoutSupplierInput, Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput> | Prisma.TotaliaProductCreateWithoutSupplierInput[] | Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.TotaliaProductCreateOrConnectWithoutSupplierInput | Prisma.TotaliaProductCreateOrConnectWithoutSupplierInput[]
  createMany?: Prisma.TotaliaProductCreateManySupplierInputEnvelope
  connect?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
}

export type TotaliaProductUpdateManyWithoutSupplierNestedInput = {
  create?: Prisma.XOR<Prisma.TotaliaProductCreateWithoutSupplierInput, Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput> | Prisma.TotaliaProductCreateWithoutSupplierInput[] | Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.TotaliaProductCreateOrConnectWithoutSupplierInput | Prisma.TotaliaProductCreateOrConnectWithoutSupplierInput[]
  upsert?: Prisma.TotaliaProductUpsertWithWhereUniqueWithoutSupplierInput | Prisma.TotaliaProductUpsertWithWhereUniqueWithoutSupplierInput[]
  createMany?: Prisma.TotaliaProductCreateManySupplierInputEnvelope
  set?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
  disconnect?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
  delete?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
  connect?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
  update?: Prisma.TotaliaProductUpdateWithWhereUniqueWithoutSupplierInput | Prisma.TotaliaProductUpdateWithWhereUniqueWithoutSupplierInput[]
  updateMany?: Prisma.TotaliaProductUpdateManyWithWhereWithoutSupplierInput | Prisma.TotaliaProductUpdateManyWithWhereWithoutSupplierInput[]
  deleteMany?: Prisma.TotaliaProductScalarWhereInput | Prisma.TotaliaProductScalarWhereInput[]
}

export type TotaliaProductUncheckedUpdateManyWithoutSupplierNestedInput = {
  create?: Prisma.XOR<Prisma.TotaliaProductCreateWithoutSupplierInput, Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput> | Prisma.TotaliaProductCreateWithoutSupplierInput[] | Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.TotaliaProductCreateOrConnectWithoutSupplierInput | Prisma.TotaliaProductCreateOrConnectWithoutSupplierInput[]
  upsert?: Prisma.TotaliaProductUpsertWithWhereUniqueWithoutSupplierInput | Prisma.TotaliaProductUpsertWithWhereUniqueWithoutSupplierInput[]
  createMany?: Prisma.TotaliaProductCreateManySupplierInputEnvelope
  set?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
  disconnect?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
  delete?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
  connect?: Prisma.TotaliaProductWhereUniqueInput | Prisma.TotaliaProductWhereUniqueInput[]
  update?: Prisma.TotaliaProductUpdateWithWhereUniqueWithoutSupplierInput | Prisma.TotaliaProductUpdateWithWhereUniqueWithoutSupplierInput[]
  updateMany?: Prisma.TotaliaProductUpdateManyWithWhereWithoutSupplierInput | Prisma.TotaliaProductUpdateManyWithWhereWithoutSupplierInput[]
  deleteMany?: Prisma.TotaliaProductScalarWhereInput | Prisma.TotaliaProductScalarWhereInput[]
}

export type TotaliaProductCreateNestedOneWithoutOrderItemsInput = {
  create?: Prisma.XOR<Prisma.TotaliaProductCreateWithoutOrderItemsInput, Prisma.TotaliaProductUncheckedCreateWithoutOrderItemsInput>
  connectOrCreate?: Prisma.TotaliaProductCreateOrConnectWithoutOrderItemsInput
  connect?: Prisma.TotaliaProductWhereUniqueInput
}

export type TotaliaProductUpdateOneWithoutOrderItemsNestedInput = {
  create?: Prisma.XOR<Prisma.TotaliaProductCreateWithoutOrderItemsInput, Prisma.TotaliaProductUncheckedCreateWithoutOrderItemsInput>
  connectOrCreate?: Prisma.TotaliaProductCreateOrConnectWithoutOrderItemsInput
  upsert?: Prisma.TotaliaProductUpsertWithoutOrderItemsInput
  disconnect?: Prisma.TotaliaProductWhereInput | boolean
  delete?: Prisma.TotaliaProductWhereInput | boolean
  connect?: Prisma.TotaliaProductWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TotaliaProductUpdateToOneWithWhereWithoutOrderItemsInput, Prisma.TotaliaProductUpdateWithoutOrderItemsInput>, Prisma.TotaliaProductUncheckedUpdateWithoutOrderItemsInput>
}

export type TotaliaProductCreateWithoutSupplierInput = {
  id?: string
  unitId: string
  name: string
  sku?: string | null
  description?: string | null
  category?: string | null
  unitOfMeasure?: string | null
  unitPrice?: number
  currentStock?: number
  minStock?: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  orderItems?: Prisma.TotaliaPurchaseOrderItemCreateNestedManyWithoutProductInput
}

export type TotaliaProductUncheckedCreateWithoutSupplierInput = {
  id?: string
  unitId: string
  name: string
  sku?: string | null
  description?: string | null
  category?: string | null
  unitOfMeasure?: string | null
  unitPrice?: number
  currentStock?: number
  minStock?: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  orderItems?: Prisma.TotaliaPurchaseOrderItemUncheckedCreateNestedManyWithoutProductInput
}

export type TotaliaProductCreateOrConnectWithoutSupplierInput = {
  where: Prisma.TotaliaProductWhereUniqueInput
  create: Prisma.XOR<Prisma.TotaliaProductCreateWithoutSupplierInput, Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput>
}

export type TotaliaProductCreateManySupplierInputEnvelope = {
  data: Prisma.TotaliaProductCreateManySupplierInput | Prisma.TotaliaProductCreateManySupplierInput[]
  skipDuplicates?: boolean
}

export type TotaliaProductUpsertWithWhereUniqueWithoutSupplierInput = {
  where: Prisma.TotaliaProductWhereUniqueInput
  update: Prisma.XOR<Prisma.TotaliaProductUpdateWithoutSupplierInput, Prisma.TotaliaProductUncheckedUpdateWithoutSupplierInput>
  create: Prisma.XOR<Prisma.TotaliaProductCreateWithoutSupplierInput, Prisma.TotaliaProductUncheckedCreateWithoutSupplierInput>
}

export type TotaliaProductUpdateWithWhereUniqueWithoutSupplierInput = {
  where: Prisma.TotaliaProductWhereUniqueInput
  data: Prisma.XOR<Prisma.TotaliaProductUpdateWithoutSupplierInput, Prisma.TotaliaProductUncheckedUpdateWithoutSupplierInput>
}

export type TotaliaProductUpdateManyWithWhereWithoutSupplierInput = {
  where: Prisma.TotaliaProductScalarWhereInput
  data: Prisma.XOR<Prisma.TotaliaProductUpdateManyMutationInput, Prisma.TotaliaProductUncheckedUpdateManyWithoutSupplierInput>
}

export type TotaliaProductScalarWhereInput = {
  AND?: Prisma.TotaliaProductScalarWhereInput | Prisma.TotaliaProductScalarWhereInput[]
  OR?: Prisma.TotaliaProductScalarWhereInput[]
  NOT?: Prisma.TotaliaProductScalarWhereInput | Prisma.TotaliaProductScalarWhereInput[]
  id?: Prisma.StringFilter<"TotaliaProduct"> | string
  unitId?: Prisma.StringFilter<"TotaliaProduct"> | string
  name?: Prisma.StringFilter<"TotaliaProduct"> | string
  sku?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  description?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  category?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  unitOfMeasure?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  unitPrice?: Prisma.FloatFilter<"TotaliaProduct"> | number
  currentStock?: Prisma.FloatFilter<"TotaliaProduct"> | number
  minStock?: Prisma.FloatFilter<"TotaliaProduct"> | number
  status?: Prisma.StringFilter<"TotaliaProduct"> | string
  supplierId?: Prisma.StringNullableFilter<"TotaliaProduct"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TotaliaProduct"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TotaliaProduct"> | Date | string
}

export type TotaliaProductCreateWithoutOrderItemsInput = {
  id?: string
  unitId: string
  name: string
  sku?: string | null
  description?: string | null
  category?: string | null
  unitOfMeasure?: string | null
  unitPrice?: number
  currentStock?: number
  minStock?: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  supplier?: Prisma.TotaliaSupplierCreateNestedOneWithoutProductsInput
}

export type TotaliaProductUncheckedCreateWithoutOrderItemsInput = {
  id?: string
  unitId: string
  name: string
  sku?: string | null
  description?: string | null
  category?: string | null
  unitOfMeasure?: string | null
  unitPrice?: number
  currentStock?: number
  minStock?: number
  status?: string
  supplierId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TotaliaProductCreateOrConnectWithoutOrderItemsInput = {
  where: Prisma.TotaliaProductWhereUniqueInput
  create: Prisma.XOR<Prisma.TotaliaProductCreateWithoutOrderItemsInput, Prisma.TotaliaProductUncheckedCreateWithoutOrderItemsInput>
}

export type TotaliaProductUpsertWithoutOrderItemsInput = {
  update: Prisma.XOR<Prisma.TotaliaProductUpdateWithoutOrderItemsInput, Prisma.TotaliaProductUncheckedUpdateWithoutOrderItemsInput>
  create: Prisma.XOR<Prisma.TotaliaProductCreateWithoutOrderItemsInput, Prisma.TotaliaProductUncheckedCreateWithoutOrderItemsInput>
  where?: Prisma.TotaliaProductWhereInput
}

export type TotaliaProductUpdateToOneWithWhereWithoutOrderItemsInput = {
  where?: Prisma.TotaliaProductWhereInput
  data: Prisma.XOR<Prisma.TotaliaProductUpdateWithoutOrderItemsInput, Prisma.TotaliaProductUncheckedUpdateWithoutOrderItemsInput>
}

export type TotaliaProductUpdateWithoutOrderItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sku?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitOfMeasure?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  currentStock?: Prisma.FloatFieldUpdateOperationsInput | number
  minStock?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  supplier?: Prisma.TotaliaSupplierUpdateOneWithoutProductsNestedInput
}

export type TotaliaProductUncheckedUpdateWithoutOrderItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sku?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitOfMeasure?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  currentStock?: Prisma.FloatFieldUpdateOperationsInput | number
  minStock?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TotaliaProductCreateManySupplierInput = {
  id?: string
  unitId: string
  name: string
  sku?: string | null
  description?: string | null
  category?: string | null
  unitOfMeasure?: string | null
  unitPrice?: number
  currentStock?: number
  minStock?: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TotaliaProductUpdateWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sku?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitOfMeasure?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  currentStock?: Prisma.FloatFieldUpdateOperationsInput | number
  minStock?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orderItems?: Prisma.TotaliaPurchaseOrderItemUpdateManyWithoutProductNestedInput
}

export type TotaliaProductUncheckedUpdateWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sku?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitOfMeasure?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  currentStock?: Prisma.FloatFieldUpdateOperationsInput | number
  minStock?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orderItems?: Prisma.TotaliaPurchaseOrderItemUncheckedUpdateManyWithoutProductNestedInput
}

export type TotaliaProductUncheckedUpdateManyWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sku?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitOfMeasure?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  unitPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  currentStock?: Prisma.FloatFieldUpdateOperationsInput | number
  minStock?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TotaliaProductCountOutputType
 */

export type TotaliaProductCountOutputType = {
  orderItems: number
}

export type TotaliaProductCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  orderItems?: boolean | TotaliaProductCountOutputTypeCountOrderItemsArgs
}

/**
 * TotaliaProductCountOutputType without action
 */
export type TotaliaProductCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProductCountOutputType
   */
  select?: Prisma.TotaliaProductCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TotaliaProductCountOutputType without action
 */
export type TotaliaProductCountOutputTypeCountOrderItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TotaliaPurchaseOrderItemWhereInput
}


export type TotaliaProductSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  unitId?: boolean
  name?: boolean
  sku?: boolean
  description?: boolean
  category?: boolean
  unitOfMeasure?: boolean
  unitPrice?: boolean
  currentStock?: boolean
  minStock?: boolean
  status?: boolean
  supplierId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  supplier?: boolean | Prisma.TotaliaProduct$supplierArgs<ExtArgs>
  orderItems?: boolean | Prisma.TotaliaProduct$orderItemsArgs<ExtArgs>
  _count?: boolean | Prisma.TotaliaProductCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["totaliaProduct"]>



export type TotaliaProductSelectScalar = {
  id?: boolean
  unitId?: boolean
  name?: boolean
  sku?: boolean
  description?: boolean
  category?: boolean
  unitOfMeasure?: boolean
  unitPrice?: boolean
  currentStock?: boolean
  minStock?: boolean
  status?: boolean
  supplierId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TotaliaProductOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "unitId" | "name" | "sku" | "description" | "category" | "unitOfMeasure" | "unitPrice" | "currentStock" | "minStock" | "status" | "supplierId" | "createdAt" | "updatedAt", ExtArgs["result"]["totaliaProduct"]>
export type TotaliaProductInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  supplier?: boolean | Prisma.TotaliaProduct$supplierArgs<ExtArgs>
  orderItems?: boolean | Prisma.TotaliaProduct$orderItemsArgs<ExtArgs>
  _count?: boolean | Prisma.TotaliaProductCountOutputTypeDefaultArgs<ExtArgs>
}

export type $TotaliaProductPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TotaliaProduct"
  objects: {
    supplier: Prisma.$TotaliaSupplierPayload<ExtArgs> | null
    orderItems: Prisma.$TotaliaPurchaseOrderItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    unitId: string
    name: string
    sku: string | null
    description: string | null
    category: string | null
    unitOfMeasure: string | null
    unitPrice: number
    currentStock: number
    minStock: number
    status: string
    supplierId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["totaliaProduct"]>
  composites: {}
}

export type TotaliaProductGetPayload<S extends boolean | null | undefined | TotaliaProductDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload, S>

export type TotaliaProductCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TotaliaProductFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TotaliaProductCountAggregateInputType | true
  }

export interface TotaliaProductDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TotaliaProduct'], meta: { name: 'TotaliaProduct' } }
  /**
   * Find zero or one TotaliaProduct that matches the filter.
   * @param {TotaliaProductFindUniqueArgs} args - Arguments to find a TotaliaProduct
   * @example
   * // Get one TotaliaProduct
   * const totaliaProduct = await prisma.totaliaProduct.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TotaliaProductFindUniqueArgs>(args: Prisma.SelectSubset<T, TotaliaProductFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TotaliaProductClient<runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TotaliaProduct that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TotaliaProductFindUniqueOrThrowArgs} args - Arguments to find a TotaliaProduct
   * @example
   * // Get one TotaliaProduct
   * const totaliaProduct = await prisma.totaliaProduct.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TotaliaProductFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TotaliaProductFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TotaliaProductClient<runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TotaliaProduct that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaProductFindFirstArgs} args - Arguments to find a TotaliaProduct
   * @example
   * // Get one TotaliaProduct
   * const totaliaProduct = await prisma.totaliaProduct.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TotaliaProductFindFirstArgs>(args?: Prisma.SelectSubset<T, TotaliaProductFindFirstArgs<ExtArgs>>): Prisma.Prisma__TotaliaProductClient<runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TotaliaProduct that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaProductFindFirstOrThrowArgs} args - Arguments to find a TotaliaProduct
   * @example
   * // Get one TotaliaProduct
   * const totaliaProduct = await prisma.totaliaProduct.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TotaliaProductFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TotaliaProductFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TotaliaProductClient<runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TotaliaProducts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaProductFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TotaliaProducts
   * const totaliaProducts = await prisma.totaliaProduct.findMany()
   * 
   * // Get first 10 TotaliaProducts
   * const totaliaProducts = await prisma.totaliaProduct.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const totaliaProductWithIdOnly = await prisma.totaliaProduct.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TotaliaProductFindManyArgs>(args?: Prisma.SelectSubset<T, TotaliaProductFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TotaliaProduct.
   * @param {TotaliaProductCreateArgs} args - Arguments to create a TotaliaProduct.
   * @example
   * // Create one TotaliaProduct
   * const TotaliaProduct = await prisma.totaliaProduct.create({
   *   data: {
   *     // ... data to create a TotaliaProduct
   *   }
   * })
   * 
   */
  create<T extends TotaliaProductCreateArgs>(args: Prisma.SelectSubset<T, TotaliaProductCreateArgs<ExtArgs>>): Prisma.Prisma__TotaliaProductClient<runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TotaliaProducts.
   * @param {TotaliaProductCreateManyArgs} args - Arguments to create many TotaliaProducts.
   * @example
   * // Create many TotaliaProducts
   * const totaliaProduct = await prisma.totaliaProduct.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TotaliaProductCreateManyArgs>(args?: Prisma.SelectSubset<T, TotaliaProductCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a TotaliaProduct.
   * @param {TotaliaProductDeleteArgs} args - Arguments to delete one TotaliaProduct.
   * @example
   * // Delete one TotaliaProduct
   * const TotaliaProduct = await prisma.totaliaProduct.delete({
   *   where: {
   *     // ... filter to delete one TotaliaProduct
   *   }
   * })
   * 
   */
  delete<T extends TotaliaProductDeleteArgs>(args: Prisma.SelectSubset<T, TotaliaProductDeleteArgs<ExtArgs>>): Prisma.Prisma__TotaliaProductClient<runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TotaliaProduct.
   * @param {TotaliaProductUpdateArgs} args - Arguments to update one TotaliaProduct.
   * @example
   * // Update one TotaliaProduct
   * const totaliaProduct = await prisma.totaliaProduct.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TotaliaProductUpdateArgs>(args: Prisma.SelectSubset<T, TotaliaProductUpdateArgs<ExtArgs>>): Prisma.Prisma__TotaliaProductClient<runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TotaliaProducts.
   * @param {TotaliaProductDeleteManyArgs} args - Arguments to filter TotaliaProducts to delete.
   * @example
   * // Delete a few TotaliaProducts
   * const { count } = await prisma.totaliaProduct.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TotaliaProductDeleteManyArgs>(args?: Prisma.SelectSubset<T, TotaliaProductDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TotaliaProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaProductUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TotaliaProducts
   * const totaliaProduct = await prisma.totaliaProduct.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TotaliaProductUpdateManyArgs>(args: Prisma.SelectSubset<T, TotaliaProductUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one TotaliaProduct.
   * @param {TotaliaProductUpsertArgs} args - Arguments to update or create a TotaliaProduct.
   * @example
   * // Update or create a TotaliaProduct
   * const totaliaProduct = await prisma.totaliaProduct.upsert({
   *   create: {
   *     // ... data to create a TotaliaProduct
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TotaliaProduct we want to update
   *   }
   * })
   */
  upsert<T extends TotaliaProductUpsertArgs>(args: Prisma.SelectSubset<T, TotaliaProductUpsertArgs<ExtArgs>>): Prisma.Prisma__TotaliaProductClient<runtime.Types.Result.GetResult<Prisma.$TotaliaProductPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TotaliaProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaProductCountArgs} args - Arguments to filter TotaliaProducts to count.
   * @example
   * // Count the number of TotaliaProducts
   * const count = await prisma.totaliaProduct.count({
   *   where: {
   *     // ... the filter for the TotaliaProducts we want to count
   *   }
   * })
  **/
  count<T extends TotaliaProductCountArgs>(
    args?: Prisma.Subset<T, TotaliaProductCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TotaliaProductCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TotaliaProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaProductAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TotaliaProductAggregateArgs>(args: Prisma.Subset<T, TotaliaProductAggregateArgs>): Prisma.PrismaPromise<GetTotaliaProductAggregateType<T>>

  /**
   * Group by TotaliaProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TotaliaProductGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TotaliaProductGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TotaliaProductGroupByArgs['orderBy'] }
      : { orderBy?: TotaliaProductGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TotaliaProductGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTotaliaProductGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TotaliaProduct model
 */
readonly fields: TotaliaProductFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TotaliaProduct.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TotaliaProductClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  supplier<T extends Prisma.TotaliaProduct$supplierArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TotaliaProduct$supplierArgs<ExtArgs>>): Prisma.Prisma__TotaliaSupplierClient<runtime.Types.Result.GetResult<Prisma.$TotaliaSupplierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  orderItems<T extends Prisma.TotaliaProduct$orderItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TotaliaProduct$orderItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TotaliaPurchaseOrderItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TotaliaProduct model
 */
export interface TotaliaProductFieldRefs {
  readonly id: Prisma.FieldRef<"TotaliaProduct", 'String'>
  readonly unitId: Prisma.FieldRef<"TotaliaProduct", 'String'>
  readonly name: Prisma.FieldRef<"TotaliaProduct", 'String'>
  readonly sku: Prisma.FieldRef<"TotaliaProduct", 'String'>
  readonly description: Prisma.FieldRef<"TotaliaProduct", 'String'>
  readonly category: Prisma.FieldRef<"TotaliaProduct", 'String'>
  readonly unitOfMeasure: Prisma.FieldRef<"TotaliaProduct", 'String'>
  readonly unitPrice: Prisma.FieldRef<"TotaliaProduct", 'Float'>
  readonly currentStock: Prisma.FieldRef<"TotaliaProduct", 'Float'>
  readonly minStock: Prisma.FieldRef<"TotaliaProduct", 'Float'>
  readonly status: Prisma.FieldRef<"TotaliaProduct", 'String'>
  readonly supplierId: Prisma.FieldRef<"TotaliaProduct", 'String'>
  readonly createdAt: Prisma.FieldRef<"TotaliaProduct", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TotaliaProduct", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TotaliaProduct findUnique
 */
export type TotaliaProductFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
  /**
   * Filter, which TotaliaProduct to fetch.
   */
  where: Prisma.TotaliaProductWhereUniqueInput
}

/**
 * TotaliaProduct findUniqueOrThrow
 */
export type TotaliaProductFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
  /**
   * Filter, which TotaliaProduct to fetch.
   */
  where: Prisma.TotaliaProductWhereUniqueInput
}

/**
 * TotaliaProduct findFirst
 */
export type TotaliaProductFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
  /**
   * Filter, which TotaliaProduct to fetch.
   */
  where?: Prisma.TotaliaProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaProducts to fetch.
   */
  orderBy?: Prisma.TotaliaProductOrderByWithRelationInput | Prisma.TotaliaProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TotaliaProducts.
   */
  cursor?: Prisma.TotaliaProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TotaliaProducts.
   */
  distinct?: Prisma.TotaliaProductScalarFieldEnum | Prisma.TotaliaProductScalarFieldEnum[]
}

/**
 * TotaliaProduct findFirstOrThrow
 */
export type TotaliaProductFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
  /**
   * Filter, which TotaliaProduct to fetch.
   */
  where?: Prisma.TotaliaProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaProducts to fetch.
   */
  orderBy?: Prisma.TotaliaProductOrderByWithRelationInput | Prisma.TotaliaProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TotaliaProducts.
   */
  cursor?: Prisma.TotaliaProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TotaliaProducts.
   */
  distinct?: Prisma.TotaliaProductScalarFieldEnum | Prisma.TotaliaProductScalarFieldEnum[]
}

/**
 * TotaliaProduct findMany
 */
export type TotaliaProductFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
  /**
   * Filter, which TotaliaProducts to fetch.
   */
  where?: Prisma.TotaliaProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TotaliaProducts to fetch.
   */
  orderBy?: Prisma.TotaliaProductOrderByWithRelationInput | Prisma.TotaliaProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TotaliaProducts.
   */
  cursor?: Prisma.TotaliaProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TotaliaProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TotaliaProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TotaliaProducts.
   */
  distinct?: Prisma.TotaliaProductScalarFieldEnum | Prisma.TotaliaProductScalarFieldEnum[]
}

/**
 * TotaliaProduct create
 */
export type TotaliaProductCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
  /**
   * The data needed to create a TotaliaProduct.
   */
  data: Prisma.XOR<Prisma.TotaliaProductCreateInput, Prisma.TotaliaProductUncheckedCreateInput>
}

/**
 * TotaliaProduct createMany
 */
export type TotaliaProductCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TotaliaProducts.
   */
  data: Prisma.TotaliaProductCreateManyInput | Prisma.TotaliaProductCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TotaliaProduct update
 */
export type TotaliaProductUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
  /**
   * The data needed to update a TotaliaProduct.
   */
  data: Prisma.XOR<Prisma.TotaliaProductUpdateInput, Prisma.TotaliaProductUncheckedUpdateInput>
  /**
   * Choose, which TotaliaProduct to update.
   */
  where: Prisma.TotaliaProductWhereUniqueInput
}

/**
 * TotaliaProduct updateMany
 */
export type TotaliaProductUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TotaliaProducts.
   */
  data: Prisma.XOR<Prisma.TotaliaProductUpdateManyMutationInput, Prisma.TotaliaProductUncheckedUpdateManyInput>
  /**
   * Filter which TotaliaProducts to update
   */
  where?: Prisma.TotaliaProductWhereInput
  /**
   * Limit how many TotaliaProducts to update.
   */
  limit?: number
}

/**
 * TotaliaProduct upsert
 */
export type TotaliaProductUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
  /**
   * The filter to search for the TotaliaProduct to update in case it exists.
   */
  where: Prisma.TotaliaProductWhereUniqueInput
  /**
   * In case the TotaliaProduct found by the `where` argument doesn't exist, create a new TotaliaProduct with this data.
   */
  create: Prisma.XOR<Prisma.TotaliaProductCreateInput, Prisma.TotaliaProductUncheckedCreateInput>
  /**
   * In case the TotaliaProduct was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TotaliaProductUpdateInput, Prisma.TotaliaProductUncheckedUpdateInput>
}

/**
 * TotaliaProduct delete
 */
export type TotaliaProductDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
  /**
   * Filter which TotaliaProduct to delete.
   */
  where: Prisma.TotaliaProductWhereUniqueInput
}

/**
 * TotaliaProduct deleteMany
 */
export type TotaliaProductDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TotaliaProducts to delete
   */
  where?: Prisma.TotaliaProductWhereInput
  /**
   * Limit how many TotaliaProducts to delete.
   */
  limit?: number
}

/**
 * TotaliaProduct.supplier
 */
export type TotaliaProduct$supplierArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaSupplier
   */
  select?: Prisma.TotaliaSupplierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaSupplier
   */
  omit?: Prisma.TotaliaSupplierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaSupplierInclude<ExtArgs> | null
  where?: Prisma.TotaliaSupplierWhereInput
}

/**
 * TotaliaProduct.orderItems
 */
export type TotaliaProduct$orderItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaPurchaseOrderItem
   */
  select?: Prisma.TotaliaPurchaseOrderItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaPurchaseOrderItem
   */
  omit?: Prisma.TotaliaPurchaseOrderItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaPurchaseOrderItemInclude<ExtArgs> | null
  where?: Prisma.TotaliaPurchaseOrderItemWhereInput
  orderBy?: Prisma.TotaliaPurchaseOrderItemOrderByWithRelationInput | Prisma.TotaliaPurchaseOrderItemOrderByWithRelationInput[]
  cursor?: Prisma.TotaliaPurchaseOrderItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TotaliaPurchaseOrderItemScalarFieldEnum | Prisma.TotaliaPurchaseOrderItemScalarFieldEnum[]
}

/**
 * TotaliaProduct without action
 */
export type TotaliaProductDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TotaliaProduct
   */
  select?: Prisma.TotaliaProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TotaliaProduct
   */
  omit?: Prisma.TotaliaProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TotaliaProductInclude<ExtArgs> | null
}
