
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VipDataRelatorioSemanal` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VipDataRelatorioSemanal
 * 
 */
export type VipDataRelatorioSemanalModel = runtime.Types.Result.DefaultSelection<Prisma.$VipDataRelatorioSemanalPayload>

export type AggregateVipDataRelatorioSemanal = {
  _count: VipDataRelatorioSemanalCountAggregateOutputType | null
  _min: VipDataRelatorioSemanalMinAggregateOutputType | null
  _max: VipDataRelatorioSemanalMaxAggregateOutputType | null
}

export type VipDataRelatorioSemanalMinAggregateOutputType = {
  id: string | null
  unitId: string | null
  semanaInicio: Date | null
  semanaFim: Date | null
  titulo: string | null
  criadoPor: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VipDataRelatorioSemanalMaxAggregateOutputType = {
  id: string | null
  unitId: string | null
  semanaInicio: Date | null
  semanaFim: Date | null
  titulo: string | null
  criadoPor: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type VipDataRelatorioSemanalCountAggregateOutputType = {
  id: number
  unitId: number
  semanaInicio: number
  semanaFim: number
  titulo: number
  conteudo: number
  criadoPor: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type VipDataRelatorioSemanalMinAggregateInputType = {
  id?: true
  unitId?: true
  semanaInicio?: true
  semanaFim?: true
  titulo?: true
  criadoPor?: true
  createdAt?: true
  updatedAt?: true
}

export type VipDataRelatorioSemanalMaxAggregateInputType = {
  id?: true
  unitId?: true
  semanaInicio?: true
  semanaFim?: true
  titulo?: true
  criadoPor?: true
  createdAt?: true
  updatedAt?: true
}

export type VipDataRelatorioSemanalCountAggregateInputType = {
  id?: true
  unitId?: true
  semanaInicio?: true
  semanaFim?: true
  titulo?: true
  conteudo?: true
  criadoPor?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type VipDataRelatorioSemanalAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VipDataRelatorioSemanal to aggregate.
   */
  where?: Prisma.VipDataRelatorioSemanalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VipDataRelatorioSemanals to fetch.
   */
  orderBy?: Prisma.VipDataRelatorioSemanalOrderByWithRelationInput | Prisma.VipDataRelatorioSemanalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VipDataRelatorioSemanalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VipDataRelatorioSemanals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VipDataRelatorioSemanals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VipDataRelatorioSemanals
  **/
  _count?: true | VipDataRelatorioSemanalCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VipDataRelatorioSemanalMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VipDataRelatorioSemanalMaxAggregateInputType
}

export type GetVipDataRelatorioSemanalAggregateType<T extends VipDataRelatorioSemanalAggregateArgs> = {
      [P in keyof T & keyof AggregateVipDataRelatorioSemanal]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVipDataRelatorioSemanal[P]>
    : Prisma.GetScalarType<T[P], AggregateVipDataRelatorioSemanal[P]>
}




export type VipDataRelatorioSemanalGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VipDataRelatorioSemanalWhereInput
  orderBy?: Prisma.VipDataRelatorioSemanalOrderByWithAggregationInput | Prisma.VipDataRelatorioSemanalOrderByWithAggregationInput[]
  by: Prisma.VipDataRelatorioSemanalScalarFieldEnum[] | Prisma.VipDataRelatorioSemanalScalarFieldEnum
  having?: Prisma.VipDataRelatorioSemanalScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VipDataRelatorioSemanalCountAggregateInputType | true
  _min?: VipDataRelatorioSemanalMinAggregateInputType
  _max?: VipDataRelatorioSemanalMaxAggregateInputType
}

export type VipDataRelatorioSemanalGroupByOutputType = {
  id: string
  unitId: string
  semanaInicio: Date
  semanaFim: Date
  titulo: string | null
  conteudo: runtime.JsonValue
  criadoPor: string | null
  createdAt: Date
  updatedAt: Date
  _count: VipDataRelatorioSemanalCountAggregateOutputType | null
  _min: VipDataRelatorioSemanalMinAggregateOutputType | null
  _max: VipDataRelatorioSemanalMaxAggregateOutputType | null
}

export type GetVipDataRelatorioSemanalGroupByPayload<T extends VipDataRelatorioSemanalGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VipDataRelatorioSemanalGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VipDataRelatorioSemanalGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VipDataRelatorioSemanalGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VipDataRelatorioSemanalGroupByOutputType[P]>
      }
    >
  >



export type VipDataRelatorioSemanalWhereInput = {
  AND?: Prisma.VipDataRelatorioSemanalWhereInput | Prisma.VipDataRelatorioSemanalWhereInput[]
  OR?: Prisma.VipDataRelatorioSemanalWhereInput[]
  NOT?: Prisma.VipDataRelatorioSemanalWhereInput | Prisma.VipDataRelatorioSemanalWhereInput[]
  id?: Prisma.StringFilter<"VipDataRelatorioSemanal"> | string
  unitId?: Prisma.StringFilter<"VipDataRelatorioSemanal"> | string
  semanaInicio?: Prisma.DateTimeFilter<"VipDataRelatorioSemanal"> | Date | string
  semanaFim?: Prisma.DateTimeFilter<"VipDataRelatorioSemanal"> | Date | string
  titulo?: Prisma.StringNullableFilter<"VipDataRelatorioSemanal"> | string | null
  conteudo?: Prisma.JsonFilter<"VipDataRelatorioSemanal">
  criadoPor?: Prisma.StringNullableFilter<"VipDataRelatorioSemanal"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VipDataRelatorioSemanal"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VipDataRelatorioSemanal"> | Date | string
}

export type VipDataRelatorioSemanalOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  semanaInicio?: Prisma.SortOrder
  semanaFim?: Prisma.SortOrder
  titulo?: Prisma.SortOrderInput | Prisma.SortOrder
  conteudo?: Prisma.SortOrder
  criadoPor?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.VipDataRelatorioSemanalOrderByRelevanceInput
}

export type VipDataRelatorioSemanalWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VipDataRelatorioSemanalWhereInput | Prisma.VipDataRelatorioSemanalWhereInput[]
  OR?: Prisma.VipDataRelatorioSemanalWhereInput[]
  NOT?: Prisma.VipDataRelatorioSemanalWhereInput | Prisma.VipDataRelatorioSemanalWhereInput[]
  unitId?: Prisma.StringFilter<"VipDataRelatorioSemanal"> | string
  semanaInicio?: Prisma.DateTimeFilter<"VipDataRelatorioSemanal"> | Date | string
  semanaFim?: Prisma.DateTimeFilter<"VipDataRelatorioSemanal"> | Date | string
  titulo?: Prisma.StringNullableFilter<"VipDataRelatorioSemanal"> | string | null
  conteudo?: Prisma.JsonFilter<"VipDataRelatorioSemanal">
  criadoPor?: Prisma.StringNullableFilter<"VipDataRelatorioSemanal"> | string | null
  createdAt?: Prisma.DateTimeFilter<"VipDataRelatorioSemanal"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VipDataRelatorioSemanal"> | Date | string
}, "id">

export type VipDataRelatorioSemanalOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  semanaInicio?: Prisma.SortOrder
  semanaFim?: Prisma.SortOrder
  titulo?: Prisma.SortOrderInput | Prisma.SortOrder
  conteudo?: Prisma.SortOrder
  criadoPor?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.VipDataRelatorioSemanalCountOrderByAggregateInput
  _max?: Prisma.VipDataRelatorioSemanalMaxOrderByAggregateInput
  _min?: Prisma.VipDataRelatorioSemanalMinOrderByAggregateInput
}

export type VipDataRelatorioSemanalScalarWhereWithAggregatesInput = {
  AND?: Prisma.VipDataRelatorioSemanalScalarWhereWithAggregatesInput | Prisma.VipDataRelatorioSemanalScalarWhereWithAggregatesInput[]
  OR?: Prisma.VipDataRelatorioSemanalScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VipDataRelatorioSemanalScalarWhereWithAggregatesInput | Prisma.VipDataRelatorioSemanalScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VipDataRelatorioSemanal"> | string
  unitId?: Prisma.StringWithAggregatesFilter<"VipDataRelatorioSemanal"> | string
  semanaInicio?: Prisma.DateTimeWithAggregatesFilter<"VipDataRelatorioSemanal"> | Date | string
  semanaFim?: Prisma.DateTimeWithAggregatesFilter<"VipDataRelatorioSemanal"> | Date | string
  titulo?: Prisma.StringNullableWithAggregatesFilter<"VipDataRelatorioSemanal"> | string | null
  conteudo?: Prisma.JsonWithAggregatesFilter<"VipDataRelatorioSemanal">
  criadoPor?: Prisma.StringNullableWithAggregatesFilter<"VipDataRelatorioSemanal"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"VipDataRelatorioSemanal"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"VipDataRelatorioSemanal"> | Date | string
}

export type VipDataRelatorioSemanalCreateInput = {
  id?: string
  unitId: string
  semanaInicio: Date | string
  semanaFim: Date | string
  titulo?: string | null
  conteudo: Prisma.JsonNullValueInput | runtime.InputJsonValue
  criadoPor?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VipDataRelatorioSemanalUncheckedCreateInput = {
  id?: string
  unitId: string
  semanaInicio: Date | string
  semanaFim: Date | string
  titulo?: string | null
  conteudo: Prisma.JsonNullValueInput | runtime.InputJsonValue
  criadoPor?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VipDataRelatorioSemanalUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  semanaInicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  semanaFim?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  titulo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conteudo?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  criadoPor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VipDataRelatorioSemanalUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  semanaInicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  semanaFim?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  titulo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conteudo?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  criadoPor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VipDataRelatorioSemanalCreateManyInput = {
  id?: string
  unitId: string
  semanaInicio: Date | string
  semanaFim: Date | string
  titulo?: string | null
  conteudo: Prisma.JsonNullValueInput | runtime.InputJsonValue
  criadoPor?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type VipDataRelatorioSemanalUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  semanaInicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  semanaFim?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  titulo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conteudo?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  criadoPor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VipDataRelatorioSemanalUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitId?: Prisma.StringFieldUpdateOperationsInput | string
  semanaInicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  semanaFim?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  titulo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conteudo?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  criadoPor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VipDataRelatorioSemanalOrderByRelevanceInput = {
  fields: Prisma.VipDataRelatorioSemanalOrderByRelevanceFieldEnum | Prisma.VipDataRelatorioSemanalOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type VipDataRelatorioSemanalCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  semanaInicio?: Prisma.SortOrder
  semanaFim?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  conteudo?: Prisma.SortOrder
  criadoPor?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VipDataRelatorioSemanalMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  semanaInicio?: Prisma.SortOrder
  semanaFim?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  criadoPor?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VipDataRelatorioSemanalMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  unitId?: Prisma.SortOrder
  semanaInicio?: Prisma.SortOrder
  semanaFim?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  criadoPor?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type VipDataRelatorioSemanalSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  unitId?: boolean
  semanaInicio?: boolean
  semanaFim?: boolean
  titulo?: boolean
  conteudo?: boolean
  criadoPor?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["vipDataRelatorioSemanal"]>



export type VipDataRelatorioSemanalSelectScalar = {
  id?: boolean
  unitId?: boolean
  semanaInicio?: boolean
  semanaFim?: boolean
  titulo?: boolean
  conteudo?: boolean
  criadoPor?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type VipDataRelatorioSemanalOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "unitId" | "semanaInicio" | "semanaFim" | "titulo" | "conteudo" | "criadoPor" | "createdAt" | "updatedAt", ExtArgs["result"]["vipDataRelatorioSemanal"]>

export type $VipDataRelatorioSemanalPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VipDataRelatorioSemanal"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    unitId: string
    semanaInicio: Date
    semanaFim: Date
    titulo: string | null
    conteudo: runtime.JsonValue
    criadoPor: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["vipDataRelatorioSemanal"]>
  composites: {}
}

export type VipDataRelatorioSemanalGetPayload<S extends boolean | null | undefined | VipDataRelatorioSemanalDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload, S>

export type VipDataRelatorioSemanalCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VipDataRelatorioSemanalFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VipDataRelatorioSemanalCountAggregateInputType | true
  }

export interface VipDataRelatorioSemanalDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VipDataRelatorioSemanal'], meta: { name: 'VipDataRelatorioSemanal' } }
  /**
   * Find zero or one VipDataRelatorioSemanal that matches the filter.
   * @param {VipDataRelatorioSemanalFindUniqueArgs} args - Arguments to find a VipDataRelatorioSemanal
   * @example
   * // Get one VipDataRelatorioSemanal
   * const vipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VipDataRelatorioSemanalFindUniqueArgs>(args: Prisma.SelectSubset<T, VipDataRelatorioSemanalFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VipDataRelatorioSemanalClient<runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VipDataRelatorioSemanal that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VipDataRelatorioSemanalFindUniqueOrThrowArgs} args - Arguments to find a VipDataRelatorioSemanal
   * @example
   * // Get one VipDataRelatorioSemanal
   * const vipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VipDataRelatorioSemanalFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VipDataRelatorioSemanalFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VipDataRelatorioSemanalClient<runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VipDataRelatorioSemanal that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipDataRelatorioSemanalFindFirstArgs} args - Arguments to find a VipDataRelatorioSemanal
   * @example
   * // Get one VipDataRelatorioSemanal
   * const vipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VipDataRelatorioSemanalFindFirstArgs>(args?: Prisma.SelectSubset<T, VipDataRelatorioSemanalFindFirstArgs<ExtArgs>>): Prisma.Prisma__VipDataRelatorioSemanalClient<runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VipDataRelatorioSemanal that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipDataRelatorioSemanalFindFirstOrThrowArgs} args - Arguments to find a VipDataRelatorioSemanal
   * @example
   * // Get one VipDataRelatorioSemanal
   * const vipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VipDataRelatorioSemanalFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VipDataRelatorioSemanalFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VipDataRelatorioSemanalClient<runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VipDataRelatorioSemanals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipDataRelatorioSemanalFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VipDataRelatorioSemanals
   * const vipDataRelatorioSemanals = await prisma.vipDataRelatorioSemanal.findMany()
   * 
   * // Get first 10 VipDataRelatorioSemanals
   * const vipDataRelatorioSemanals = await prisma.vipDataRelatorioSemanal.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vipDataRelatorioSemanalWithIdOnly = await prisma.vipDataRelatorioSemanal.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VipDataRelatorioSemanalFindManyArgs>(args?: Prisma.SelectSubset<T, VipDataRelatorioSemanalFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VipDataRelatorioSemanal.
   * @param {VipDataRelatorioSemanalCreateArgs} args - Arguments to create a VipDataRelatorioSemanal.
   * @example
   * // Create one VipDataRelatorioSemanal
   * const VipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.create({
   *   data: {
   *     // ... data to create a VipDataRelatorioSemanal
   *   }
   * })
   * 
   */
  create<T extends VipDataRelatorioSemanalCreateArgs>(args: Prisma.SelectSubset<T, VipDataRelatorioSemanalCreateArgs<ExtArgs>>): Prisma.Prisma__VipDataRelatorioSemanalClient<runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VipDataRelatorioSemanals.
   * @param {VipDataRelatorioSemanalCreateManyArgs} args - Arguments to create many VipDataRelatorioSemanals.
   * @example
   * // Create many VipDataRelatorioSemanals
   * const vipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VipDataRelatorioSemanalCreateManyArgs>(args?: Prisma.SelectSubset<T, VipDataRelatorioSemanalCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a VipDataRelatorioSemanal.
   * @param {VipDataRelatorioSemanalDeleteArgs} args - Arguments to delete one VipDataRelatorioSemanal.
   * @example
   * // Delete one VipDataRelatorioSemanal
   * const VipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.delete({
   *   where: {
   *     // ... filter to delete one VipDataRelatorioSemanal
   *   }
   * })
   * 
   */
  delete<T extends VipDataRelatorioSemanalDeleteArgs>(args: Prisma.SelectSubset<T, VipDataRelatorioSemanalDeleteArgs<ExtArgs>>): Prisma.Prisma__VipDataRelatorioSemanalClient<runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VipDataRelatorioSemanal.
   * @param {VipDataRelatorioSemanalUpdateArgs} args - Arguments to update one VipDataRelatorioSemanal.
   * @example
   * // Update one VipDataRelatorioSemanal
   * const vipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VipDataRelatorioSemanalUpdateArgs>(args: Prisma.SelectSubset<T, VipDataRelatorioSemanalUpdateArgs<ExtArgs>>): Prisma.Prisma__VipDataRelatorioSemanalClient<runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VipDataRelatorioSemanals.
   * @param {VipDataRelatorioSemanalDeleteManyArgs} args - Arguments to filter VipDataRelatorioSemanals to delete.
   * @example
   * // Delete a few VipDataRelatorioSemanals
   * const { count } = await prisma.vipDataRelatorioSemanal.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VipDataRelatorioSemanalDeleteManyArgs>(args?: Prisma.SelectSubset<T, VipDataRelatorioSemanalDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VipDataRelatorioSemanals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipDataRelatorioSemanalUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VipDataRelatorioSemanals
   * const vipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VipDataRelatorioSemanalUpdateManyArgs>(args: Prisma.SelectSubset<T, VipDataRelatorioSemanalUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one VipDataRelatorioSemanal.
   * @param {VipDataRelatorioSemanalUpsertArgs} args - Arguments to update or create a VipDataRelatorioSemanal.
   * @example
   * // Update or create a VipDataRelatorioSemanal
   * const vipDataRelatorioSemanal = await prisma.vipDataRelatorioSemanal.upsert({
   *   create: {
   *     // ... data to create a VipDataRelatorioSemanal
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VipDataRelatorioSemanal we want to update
   *   }
   * })
   */
  upsert<T extends VipDataRelatorioSemanalUpsertArgs>(args: Prisma.SelectSubset<T, VipDataRelatorioSemanalUpsertArgs<ExtArgs>>): Prisma.Prisma__VipDataRelatorioSemanalClient<runtime.Types.Result.GetResult<Prisma.$VipDataRelatorioSemanalPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VipDataRelatorioSemanals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipDataRelatorioSemanalCountArgs} args - Arguments to filter VipDataRelatorioSemanals to count.
   * @example
   * // Count the number of VipDataRelatorioSemanals
   * const count = await prisma.vipDataRelatorioSemanal.count({
   *   where: {
   *     // ... the filter for the VipDataRelatorioSemanals we want to count
   *   }
   * })
  **/
  count<T extends VipDataRelatorioSemanalCountArgs>(
    args?: Prisma.Subset<T, VipDataRelatorioSemanalCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VipDataRelatorioSemanalCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VipDataRelatorioSemanal.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipDataRelatorioSemanalAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VipDataRelatorioSemanalAggregateArgs>(args: Prisma.Subset<T, VipDataRelatorioSemanalAggregateArgs>): Prisma.PrismaPromise<GetVipDataRelatorioSemanalAggregateType<T>>

  /**
   * Group by VipDataRelatorioSemanal.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipDataRelatorioSemanalGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VipDataRelatorioSemanalGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VipDataRelatorioSemanalGroupByArgs['orderBy'] }
      : { orderBy?: VipDataRelatorioSemanalGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VipDataRelatorioSemanalGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVipDataRelatorioSemanalGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VipDataRelatorioSemanal model
 */
readonly fields: VipDataRelatorioSemanalFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VipDataRelatorioSemanal.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VipDataRelatorioSemanalClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VipDataRelatorioSemanal model
 */
export interface VipDataRelatorioSemanalFieldRefs {
  readonly id: Prisma.FieldRef<"VipDataRelatorioSemanal", 'String'>
  readonly unitId: Prisma.FieldRef<"VipDataRelatorioSemanal", 'String'>
  readonly semanaInicio: Prisma.FieldRef<"VipDataRelatorioSemanal", 'DateTime'>
  readonly semanaFim: Prisma.FieldRef<"VipDataRelatorioSemanal", 'DateTime'>
  readonly titulo: Prisma.FieldRef<"VipDataRelatorioSemanal", 'String'>
  readonly conteudo: Prisma.FieldRef<"VipDataRelatorioSemanal", 'Json'>
  readonly criadoPor: Prisma.FieldRef<"VipDataRelatorioSemanal", 'String'>
  readonly createdAt: Prisma.FieldRef<"VipDataRelatorioSemanal", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"VipDataRelatorioSemanal", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VipDataRelatorioSemanal findUnique
 */
export type VipDataRelatorioSemanalFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
  /**
   * Filter, which VipDataRelatorioSemanal to fetch.
   */
  where: Prisma.VipDataRelatorioSemanalWhereUniqueInput
}

/**
 * VipDataRelatorioSemanal findUniqueOrThrow
 */
export type VipDataRelatorioSemanalFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
  /**
   * Filter, which VipDataRelatorioSemanal to fetch.
   */
  where: Prisma.VipDataRelatorioSemanalWhereUniqueInput
}

/**
 * VipDataRelatorioSemanal findFirst
 */
export type VipDataRelatorioSemanalFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
  /**
   * Filter, which VipDataRelatorioSemanal to fetch.
   */
  where?: Prisma.VipDataRelatorioSemanalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VipDataRelatorioSemanals to fetch.
   */
  orderBy?: Prisma.VipDataRelatorioSemanalOrderByWithRelationInput | Prisma.VipDataRelatorioSemanalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VipDataRelatorioSemanals.
   */
  cursor?: Prisma.VipDataRelatorioSemanalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VipDataRelatorioSemanals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VipDataRelatorioSemanals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VipDataRelatorioSemanals.
   */
  distinct?: Prisma.VipDataRelatorioSemanalScalarFieldEnum | Prisma.VipDataRelatorioSemanalScalarFieldEnum[]
}

/**
 * VipDataRelatorioSemanal findFirstOrThrow
 */
export type VipDataRelatorioSemanalFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
  /**
   * Filter, which VipDataRelatorioSemanal to fetch.
   */
  where?: Prisma.VipDataRelatorioSemanalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VipDataRelatorioSemanals to fetch.
   */
  orderBy?: Prisma.VipDataRelatorioSemanalOrderByWithRelationInput | Prisma.VipDataRelatorioSemanalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VipDataRelatorioSemanals.
   */
  cursor?: Prisma.VipDataRelatorioSemanalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VipDataRelatorioSemanals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VipDataRelatorioSemanals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VipDataRelatorioSemanals.
   */
  distinct?: Prisma.VipDataRelatorioSemanalScalarFieldEnum | Prisma.VipDataRelatorioSemanalScalarFieldEnum[]
}

/**
 * VipDataRelatorioSemanal findMany
 */
export type VipDataRelatorioSemanalFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
  /**
   * Filter, which VipDataRelatorioSemanals to fetch.
   */
  where?: Prisma.VipDataRelatorioSemanalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VipDataRelatorioSemanals to fetch.
   */
  orderBy?: Prisma.VipDataRelatorioSemanalOrderByWithRelationInput | Prisma.VipDataRelatorioSemanalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VipDataRelatorioSemanals.
   */
  cursor?: Prisma.VipDataRelatorioSemanalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VipDataRelatorioSemanals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VipDataRelatorioSemanals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VipDataRelatorioSemanals.
   */
  distinct?: Prisma.VipDataRelatorioSemanalScalarFieldEnum | Prisma.VipDataRelatorioSemanalScalarFieldEnum[]
}

/**
 * VipDataRelatorioSemanal create
 */
export type VipDataRelatorioSemanalCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
  /**
   * The data needed to create a VipDataRelatorioSemanal.
   */
  data: Prisma.XOR<Prisma.VipDataRelatorioSemanalCreateInput, Prisma.VipDataRelatorioSemanalUncheckedCreateInput>
}

/**
 * VipDataRelatorioSemanal createMany
 */
export type VipDataRelatorioSemanalCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VipDataRelatorioSemanals.
   */
  data: Prisma.VipDataRelatorioSemanalCreateManyInput | Prisma.VipDataRelatorioSemanalCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VipDataRelatorioSemanal update
 */
export type VipDataRelatorioSemanalUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
  /**
   * The data needed to update a VipDataRelatorioSemanal.
   */
  data: Prisma.XOR<Prisma.VipDataRelatorioSemanalUpdateInput, Prisma.VipDataRelatorioSemanalUncheckedUpdateInput>
  /**
   * Choose, which VipDataRelatorioSemanal to update.
   */
  where: Prisma.VipDataRelatorioSemanalWhereUniqueInput
}

/**
 * VipDataRelatorioSemanal updateMany
 */
export type VipDataRelatorioSemanalUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VipDataRelatorioSemanals.
   */
  data: Prisma.XOR<Prisma.VipDataRelatorioSemanalUpdateManyMutationInput, Prisma.VipDataRelatorioSemanalUncheckedUpdateManyInput>
  /**
   * Filter which VipDataRelatorioSemanals to update
   */
  where?: Prisma.VipDataRelatorioSemanalWhereInput
  /**
   * Limit how many VipDataRelatorioSemanals to update.
   */
  limit?: number
}

/**
 * VipDataRelatorioSemanal upsert
 */
export type VipDataRelatorioSemanalUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
  /**
   * The filter to search for the VipDataRelatorioSemanal to update in case it exists.
   */
  where: Prisma.VipDataRelatorioSemanalWhereUniqueInput
  /**
   * In case the VipDataRelatorioSemanal found by the `where` argument doesn't exist, create a new VipDataRelatorioSemanal with this data.
   */
  create: Prisma.XOR<Prisma.VipDataRelatorioSemanalCreateInput, Prisma.VipDataRelatorioSemanalUncheckedCreateInput>
  /**
   * In case the VipDataRelatorioSemanal was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VipDataRelatorioSemanalUpdateInput, Prisma.VipDataRelatorioSemanalUncheckedUpdateInput>
}

/**
 * VipDataRelatorioSemanal delete
 */
export type VipDataRelatorioSemanalDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
  /**
   * Filter which VipDataRelatorioSemanal to delete.
   */
  where: Prisma.VipDataRelatorioSemanalWhereUniqueInput
}

/**
 * VipDataRelatorioSemanal deleteMany
 */
export type VipDataRelatorioSemanalDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VipDataRelatorioSemanals to delete
   */
  where?: Prisma.VipDataRelatorioSemanalWhereInput
  /**
   * Limit how many VipDataRelatorioSemanals to delete.
   */
  limit?: number
}

/**
 * VipDataRelatorioSemanal without action
 */
export type VipDataRelatorioSemanalDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipDataRelatorioSemanal
   */
  select?: Prisma.VipDataRelatorioSemanalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipDataRelatorioSemanal
   */
  omit?: Prisma.VipDataRelatorioSemanalOmit<ExtArgs> | null
}
